### ISSUE TITLE
GetPortfolio - фьючерсы [bug]

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#1]
неправильно отображается информация о фьючерсе в методе getPortfolio

  {
      "figi": "",
      "instrumentType": "",
      "quantity": -15,
      "averagePositionPrice": {
        "currency": "",
        "units": "0",
        "nano": 0
      },
      "expectedYield": -2929.03,
      "currentNkd": {
        "currency": "",
        "units": "0",
        "nano": 0
      },
      "averagePositionPricePt": {
        "units": "468",
        "nano": 120000000
      }
    },

**Comment by betslus1** [comment]
Так же народ жалуется на отсутствие figi в операциях, в т.ч. для валюты.

**Comment by AlexanderVolkovTCS** [comment]
>фьючерсе 

исправлено


>отсутствие figi в операциях
в некоторых операциях, таких как удержание комиссии или начисление вариационной маржи, figi отсутствует.
