### ISSUE TITLE
Очень тяжело найти по коду ошибки описание что же пошло не так

### ISSUE THREAD

**Issue by S-DyX** [Tinkoff/investAPI#100]
Очень тяжело найти по коду ошибки описание что же пошло не так.

**Comment by betslus1** [comment]
Тоже не сразу нашёл, но в метатэгах ответа есть текстовое описание ошибок почти на русском языке.

**Comment by AlexanderVolkovTCS** [comment]
Мы опубликовали json со списком ошибок: https://github.com/Tinkoff/investAPI/blob/main/src/docs/errors/api_errors.json
