### ISSUE TITLE
Обработка WebResponse https://api-invest.tinkoff.ru/openapi/portfolio?brokerAccountId=...

### ISSUE THREAD

**Issue by morvan1980** [Tinkoff/investAPI#102]
Добрый день.
Делаю GET по портфелю. В ответе получаю вместо русских названий нечитаемый набор символов. Очевидно что проблема с кодировкой.

HttpWebRequest := HttpWebRequest.Create(Url);
HttpWebRequest.Method := 'GET';
HttpWebRequest.ContentLength := 0;
HttpWebRequest.Headers.Add('Authorization','Bearer ' + AccessToken);
HttpWebRequest.Accept('application/json');
HttpWebResponse := HttpWebRequest.GetResponse;

Получаю:
{"trackingId":"46e58902ba413f7f","payload":{"positions":[{"figi":"BBG005F1DK91","ticker":"GTHX","isin":"US3621LQ1099","instrumentType":"Stock","balance":5.8E+2,"lots":580,"expectedYield":{"currency":"USD","value":-3093.9},"averagePositionPrice":{"currency":"USD","value":14.95},"name":"G1 Therapeutics Inc"},{"figi":"BBG0013HGFT4","ticker":"USD000UTSTOM","instrumentType":"Currency","balance":15858.2,"lots":15,"expectedYield":{"currency":"RUB","value":8870.93},"averagePositionPrice":{"currency":"RUB","value":76.74},"name":"њФњ‹њ€њ€њќА њбњињР"}]},"status":"Ok"}
Каким образом получить читаемый ответ?
HttpWebResponse.CharacterSet пустой. Не ясно в какой кодировке приходит ответ.

Аналогичная проблема у меня при чтении выполненных операций:
https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperations
Если были операции по российским акциям, то не читается, вместо русских наименований нечитаемый набор символов.

**Comment by malyginvv** [comment]
Добрый день!
Предполагаю, что `HttpWebResponse.CharacterSet` использует кодировку по умолчанию `ISO-8859-1`, но все ответы API, имеющие заголовок `content-type: application/json`, используют кодировку `UTF-8`, поскольку это кодировка по-умолчанию для JSON: https://tools.ietf.org/id/draft-ietf-json-rfc4627bis-09.html#rfc.section.8.1
Попробуйте обработать тело ответа как строку с кодировкой `UTF-8`.
