### ISSUE TITLE
Нет одной операции с комиссией по сделке в выдаче GetOperations

### ISSUE THREAD

**Issue by kostarev** [Tinkoff/investAPI#107]
Выгружаю всю историю операций по портфелю через GetOperations
Вычисляю через них полный состав портфеля.
Не сходятся остатки по рублям на 0,23р

Обнаружил, что в выдаче GetOperations не хватает одной комиссии по сделке продажи EUR_RUB__TOM ровно 0,23р.
В отчёте брокера в Excel эта комиссия присутствует.

Могу выслать токен и другие данные для демонстрации ошибки. Куда отправить?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, проблемы отсутствующих операций решаются в рамках обращения в техподдержку приложения.

**Comment by kostarev** [comment]
> Добрый день, проблемы отсутствующих операций решаются в рамках обращения в техподдержку приложения.

Какого приложения? Тинькофф Инвестиции?
