### ISSUE TITLE
Ошибки и вопросы

### ISSUE THREAD

**Issue by MURSHIG** [Tinkoff/investAPI#108]
Во-первых openapi python не работает на MacBook с m1, решается использованием arch -x86_64, но все же нативные пакеты лучше, во-вторых не ясно откуда брать figi бумаги, было бы хорошо что бы на сайте с тикером указывался figi

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, про питон лучше написать в соответствующий репозитарий sdk,
а получить список figi можно в методах сервиса инструментов, возвращающий списки бумаг:
https://tinkoff.github.io/investAPI/instruments/#shares
https://tinkoff.github.io/investAPI/instruments/#bonds
и тд
