### ISSUE TITLE
GetDividendsRequest from/to fields

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#110]
Не очень понятно даты чего используются в запросе GetDividendsRequest
https://tinkoff.github.io/investAPI/instruments/#getdividendsrequest

> Начало запрашиваемого периода в часовом поясе UTC.
> Окончание запрашиваемого периода в часовом поясе UTC.

По какому полю идет фильтрация `created_at`, `declared_date`, `last_buy_date`? Или алгоритм более сложный?

**Comment by serejhaaa** [comment]
Фильтрация идёт по полю record_date (дата фиксации реестра). В документацию информацию добавлю
