### ISSUE TITLE
В ответе GetPortfolio в поле expected_yield нет валюты

### ISSUE THREAD

**Issue by irishrover** [Tinkoff/investAPI#113]
```
expected_yield {
     units: -983     
     nano: -300000000   
}
```

tracking-id: c3f9656919f460e4868ebd9b5c20c613

**Comment by AlexanderVolkovTCS** [comment]
Спасибо, обновим документацию, это процентная доходность.

**Comment by irishrover** [comment]
> Спасибо, обновим документацию, это процентная доходность.

Судя по числам, это все-таки не проценты, а абсолютные значения.
