### ISSUE TITLE
Не закрылись короткие позиции

### ISSUE THREAD

**Issue by PavelVlasenko** [Tinkoff/investAPI#114]
Через АПИ были открыты короткие позиции по тикерам SBER на 2670 лотов  и GAZP на 4410 лотов.
При попытке закрыть эти позиции, те выставить ордер на покупку возникала ошибка с кодом io.grpc.StatusRuntimeException: INVALID_ARGUMENT: 30042
Время 22.02.2022 14:03:45 UTC

После этого успешно закрылось через старое апи,  id операции  30532571365.

**Comment by AlexanderVolkovTCS** [comment]
Вероятнее всего, проблема была временная. Можете уточнить,
* не пробовали ли закрыть через мобильное приложение?
* такая ошибка возникала только один раз или несколько?
* сколько времени прошло между неудачной попыткой закрыть шорт и успешной через старое апи?
