### ISSUE TITLE
Ребята у меня куча проектов которые еще на net 4.5 соберите библиотеку и на 4.5 версию так как все проекты преводить на 6 версию не вариант

### ISSUE THREAD

**Issue by cibermax** [Tinkoff/investAPI#117]
Ребята у меня куча проектов которые еще на net 4.5 соберите пожалуйста библиотеку и на 4.5 версию так как все проекты переводить на 6 версию dotnet не вариант

**Comment by rus-art** [comment]
К сожалению, не получится. .NET Framework 4.5 [выходит из поддержки](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/) 26 апреля. В любом случае, основная зависимость SDK - библиотека [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client). Минимальная версия, которую они поддерживают - netstandard2.0, что соответствует .NET Framework 4.6.2. Добавить рантайм на эту версию еще возможно.

**Comment by cibermax** [comment]
Хотя бы так соберите есть 4.6.2 и есть 4.7

**Comment by rus-art** [comment]
Добавил TargetFramework netstandard2.0
К сожалению нет возможности проверить работоспособность, если будут ошибки, пишите

**Comment by cibermax** [comment]
Ок спасибо как проверю отпишусь

**Comment by cibermax** [comment]
Ребята все проверил скачал с nuget все ок спасибо работает !!!
