### ISSUE TITLE
Сделайте пожалуйста пример использования ApiClient на С# без использования DepencyInjection 

### ISSUE THREAD

**Issue by cibermax** [Tinkoff/investAPI#120]
Сделайте пожалуйста пример использования ApiClient на С# без использования DepencyInjection 

Пример 

var InvestClient = new InvestApiClient()
и дальше дергать в классе InvestClient 

var accounts = InvestClient.accounts;
var bnds = InvestClient.Bonds;

**Comment by cibermax** [comment]
не получается проект собран на версии Net Framework 4.6.1 
Ребята пересобрали Tinkoff.InvestApi на Net Standart 2.0
но в зависимостях есть Net 6
![image](https://user-images.githubusercontent.com/7147503/159547202-1410b167-542a-41cd-9c38-747845ef4613.png)

и соответственно сборка не происходит ругается на new ServiceCollection()

Ошибка	CS0433	Тип "ServiceCollection" существует как в "Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60", так и в "Microsoft.Extensions.DependencyInjection, Version=3.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".	OsEngine	D:\NET.PROJECTS\OsEngine2\project\OsEngine\Market\Servers\TCSG	D:\NET.PROJECTS\OsEngine2\project\OsEngine\Market\Servers\TCSG\TCSGClient.cs

![image](https://user-images.githubusercontent.com/7147503/159547635-eb0a3a57-cb7f-444a-b38a-76725f255969.png)

**Comment by cibermax** [comment]
Спасибо отпишусь что получилось

**Comment by Magneto82** [comment]
У меня такая же проблема, но похоже ошибка в grpc-dotnet.
https://github.com/grpc/grpc-dotnet/issues/1481

**Comment by cibermax** [comment]
Я удалил все ссылки на Microsoft.Extensions.DependencyInjection.Abstractions и на Microsoft.Extensions.DependencyInjection
заново уствновил через nuget Microsoft.Extensions.DependencyInjection и все заработало стало собираться 

_client = new ServiceCollection().AddInvestApiClient((_, x) => x.AccessToken = "token").BuildServiceProvider().GetService<InvestApiClient>();
все норм вроде работает....

но при первом запуске приложения когда идет первый запрос к серверу вылетает ошибка 

gRPC requires extra configuration on .NET implementations that don't support gRPC over HTTP/2. An HTTP provider must be specified using GrpcChannelOptions.HttpHandler.The configured HTTP provider must either support HTTP/2 or be configured to use gRPC-Web. See https://aka.ms/aspnet/grpc/netstandard for details.

что то в сборке net2 standart что то не так

**Comment by cibermax** [comment]
еще вопрос не по теме есть ли метод в вашем sdk который возвращает статус подключения к бирже?

**Comment by rus-art** [comment]
Судя по [этому](https://docs.microsoft.com/ru-ru/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework) гайду, нужно установить пакет System.Net.Http.WinHttpHandler и сделать дополнительную настройку
```C#
.ConfigurePrimaryHttpMessageHandler(
        () => new GrpcWebHandler(new HttpClientHandler()));
```

Сейчас такой вызов написать не получится, но можно написать альтернативный вариант
```c#
var investApiClient = new ServiceCollection()
    .AddInvestApiClient((_, x) => x.AccessToken = "...")
    .Configure<HttpClientFactoryOptions>("", options =>
        {
            options.HttpMessageHandlerBuilderActions.Add(b => b.PrimaryHandler = new WinHttpHandler());
        });
    .BuildServiceProvider()
    .GetService<InvestApiClient>();
```

**Comment by rus-art** [comment]
> еще вопрос не по теме есть ли метод в вашем sdk который возвращает статус подключения к бирже?

Что подразумевается под статусом подключения? Unary методы вызываются по запросу, создают подключение, если его нет. У Stream методов статус подключения можно узнать, подскажу если про это вопрос. Или речь о расписании биржы?

**Comment by rus-art** [comment]
Вы на скрине засветили свой токен, отзовите его, иначе люди смогут торговать вашими деньгами от вашего имени

**Comment by cibermax** [comment]
> Вы на скрине засветили свой токен, отзовите его, иначе люди смогут торговать вашими деньгами от вашего имени

Спасибо друг, там денег нет :), они всё у другого брокера через quik  роботы торгуют, как разберусь с вашей либой к вам перелью

**Comment by cibermax** [comment]
> 
если вам не сложно приведите пример использования пары методов

**Comment by cibermax** [comment]
https://docs.microsoft.com/ru-ru/aspnet/core/grpc/netstandard?view=aspnetcore-6.0

**Comment by cibermax** [comment]
> Судя по [этому](https://docs.microsoft.com/ru-ru/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework) гайду, нужно установить пакет System.Net.Http.WinHttpHandler и сделать дополнительную настройку
> 
> ```cs
> .ConfigurePrimaryHttpMessageHandler(
>         () => new WinHttpHandler());
> ```
> 
> Сейчас такой вызов написать не получится, но можно написать альтернативный вариант
> 
> ```cs
> var investApiClient = new ServiceCollection()
>     .AddInvestApiClient((_, x) => x.AccessToken = "...")
>     .Configure<HttpClientFactoryOptions>("", options =>
>         {
>             options.HttpMessageHandlerBuilderActions.Add(b => b.PrimaryHandler = new WinHttpHandler());
>         });
>     .BuildServiceProvider()
>     .GetService<InvestApiClient>();
> ```
> 
> Также там описаны ограничения, то есть потенциально не все может работать

gRPC requires extra configuration on .NET implementations that don't support gRPC over HTTP/2. An HTTP provider must be specified using GrpcChannelOptions.HttpHandler.The configured HTTP provider must either support HTTP/2 or be configured to use gRPC-Web. See https://aka.ms/aspnet/grpc/netstandard for details

тоже не работает выдает такую ошибку

**Comment by cibermax** [comment]
Можно пример как создать объект и дернуть метод

**Comment by Andrey-Solovyh** [comment]
Уже июль, а проблема с gRPC как была, так и осталась
Для галочки API делали?

**Comment by vas7n** [comment]
> Уже июль, а проблема с gRPC как была, так и осталась Для галочки API делали?

пробую вот так решить проблему:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Tinkoff.InvestApi" Version="0.1.6" />
  </ItemGroup>

<!--добавил в файл проекта-->
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Exclude="Microsoft.Extensions.Logging.Abstractions">
      <Aliases>DIConflict</Aliases>
    </Reference>
  </ItemGroup>

</Project>
```

А в коде:

```
extern alias DIConflict;

using DI = DIConflict.Microsoft.Extensions.DependencyInjection;

namespace WinFormsApp1
{
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            var services = new DI.ServiceCollection();

            ApplicationConfiguration.Initialize();
            Application.Run(new Form1());
        }
    }
}
```

проект собрался, как работают зависимости пока не успел проверить, но скорее работают.
