### ISSUE TITLE
Возвращается тип данных string вместо int64 у поля units в типе Quotation

### ISSUE THREAD

**Issue by HiHat** [Tinkoff/investAPI#122]
В документации про тип Quotation указано, что поле units должно иметь тип int64, но в ответах возвращается тип string:
{
  "lastPrices": [
    {
      "figi": "BBG011FJ6573",
      "price": {
        **"units": "69",**
        "nano": 240000000
      },
      "time": "2022-03-22T15:45:24.000694Z"
    }
  ]
}

**Comment by AlexanderVolkovTCS** [comment]
units - это int64.
Но если вы делаете запросы клиентами, типа kreya - то сами клиенты могут менять тип на строку.

**Comment by HiHat** [comment]
Kreya тут не причем!
В примере ответ от swagger!

**Comment by malyginvv** [comment]
Добрый день!
Спецификация openapi предназначена для браузерных клиентов, а в javascript рекомендуется передавать тип int64 как string. 
Подробнее https://github.com/Tinkoff/investAPI/issues/156
