### ISSUE TITLE
Разделить лимиты по получению и выставлению ордеров.

### ISSUE THREAD

**Issue by AlexanderVolkovTCS** [Tinkoff/investAPI#124]
На getOrders сделать лимит в 60 rpm

**Comment by nonamegithub** [comment]
и на GetStopOrders тоже

**Comment by nonamegithub** [comment]
@AlexanderVolkovTCS "Разделить лимиты по получению и выставлению ордеров" почему-то до сих пор без статуса "enhancement"

**Comment by AlexanderVolkovTCS** [comment]
Спасибо, для getOrders уже реализовано,
для GetStopOrders пока не будем.
