### ISSUE TITLE
Пустое поле figi в операциях и информация по внебиржевым бумагам

### ISSUE THREAD

**Issue by hommeideal** [Tinkoff/investAPI#125]
Делаю запрос операций через REST:
https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperations
```
{
  "accountId": "2034027496",
  "from": "2020-07-29T00:00:00.752Z",
  "to": "2020-07-31T23:59:59.752Z",
  "state": "OPERATION_STATE_UNSPECIFIED"
}
```

В ответе среди прочих операций получаю две непонятные операции с пустым полем figi:
```
{
      "id": "149031807270",
      "parentOperationId": "",
      "currency": "usd",
      "payment": {
        "currency": "usd",
        "units": "6",
        "nano": 340000000
      },
      "price": {
        "currency": "usd",
        "units": "6",
        "nano": 340000000
      },
      "state": "OPERATION_STATE_EXECUTED",
      "quantity": "1",
      "quantityRest": "0",
      "figi": "",
      "instrumentType": "",
      "date": "2020-07-31T08:08:02.105Z",
      "type": "Продажа ЦБ",
      "operationType": "OPERATION_TYPE_SELL",
      "trades": [
        {
          "tradeId": "1187148280",
          "dateTime": "2020-07-31T08:08:02.105Z",
          "quantity": "1",
          "price": {
            "currency": "usd",
            "units": "6",
            "nano": 340000000
          }
        }
      ]
    },
    {
      "id": "148456071400",
      "parentOperationId": "",
      "currency": "usd",
      "payment": {
        "currency": "usd",
        "units": "-6",
        "nano": -580000000
      },
      "price": {
        "currency": "usd",
        "units": "6",
        "nano": 580000000
      },
      "state": "OPERATION_STATE_EXECUTED",
      "quantity": "1",
      "quantityRest": "0",
      "figi": "",
      "instrumentType": "",
      "date": "2020-07-29T14:34:38.657Z",
      "type": "Покупка ЦБ с карты",
      "operationType": "OPERATION_TYPE_BUY_CARD",
      "trades": [
        {
          "tradeId": "1175373140",
          "dateTime": "2020-07-29T14:34:38.858Z",
          "quantity": "1",
          "price": {
            "currency": "usd",
            "units": "6",
            "nano": 580000000
          }
        }
      ]
    },
```
В первой версии API этих операций вообще нет в результатах запроса.

И ещё один вопрос чтобы не создавать новый issue. В портфеле есть акции Mallinckrodt PLC, в результатах запроса по операциям эта бумага присутствует, figi заполнен BBG002BHBHM1, но в результатах запроса списка акций этой бумаги нет. Хоть она и торгуется на внебирже и операции по ней ограничены, всё равно для вывода исторических данных информация по инструменту нужна. В первой версии API она присутствовала:
```
      {
        "figi": "BBG002BHBHM1",
        "ticker": "MNK",
        "isin": "IE00BBGT3753",
        "minPriceIncrement": 0.01,
        "lot": 1,
        "currency": "USD",
        "name": "Mallinckrodt PLC",
        "type": "Stock"
      },
```

**Comment by hommeideal** [comment]
Вопрос с отсутствующей информацией по акции Mallinckrodt PLC в результатах запроса по всем акциям InstrumentsService/Shares решился отдельным запросом InstrumentsService/ShareBy по figi BBG002BHBHM1. Немного неудобно конечно, приходится сначала получать все акции и операции, а потом по отсутствующим инструментам делать дополнительные запросы. Но здесь могу понять логику - старые инструменты снятые с торгов не должны присутствовать в списке акций. Можно этот вопрос считать закрытым.

Вопрос по пустому полю figi в операциях открыт.

**Comment by AlexanderVolkovTCS** [comment]
По второму вопросу - в методе получения списка инструментов есть параметр: https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/instruments.proto#L439
Если вам нужны все бумаги - укажите INSTRUMENT_STATUS_ALL 

А по первому вопросу с отсутствующей figi разбираемся

**Comment by hommeideal** [comment]
Со статусом INSTRUMENT_STATUS_ALL получилось, спасибо!

**Comment by hommeideal** [comment]
Нашел эти операции в приложении. Это была покупка/продажа акций General Electric. Может эта информация поможет.

![Screenshot_20220405-121504](https://user-images.githubusercontent.com/72801104/161722481-a03c5bb5-3db4-40ee-8881-62ce98c021df.png)
![Screenshot_20220405-121521](https://user-images.githubusercontent.com/72801104/161722487-251f6457-ef77-4a89-82dc-2efe5c9cd746.png)

**Comment by kuznetsov-v** [comment]
И у казахстанского тенге тоже figi отсутствует. id операций: 24873409886, 24864494317

**Comment by allexme** [comment]
@AlexanderVolkovTCS Добрый день!
Прошел уже не один месяц, как о данном баге стало известно и он до сих пор не исправлен. Стоит ли вообще ждать исправлений? В одном из аккаунтов аж 354 операции без FIGI, а всего известно о 575 подобных операциях на разных аккаунтах. Если это как-то поможет, вот их список: [скачать](https://investstats.ru/_temp/operations_figi_bug.txt)

**Comment by AlexanderVolkovTCS** [comment]
Если проблема актуальна, прошу переоткрыть тикет.
