### ISSUE TITLE
GetOperations не выдает некоторые операции

### ISSUE THREAD

**Issue by progamer75** [Tinkoff/investAPI#127]
GetOperations не выгружает 3 операции "Пополнение счета" и "Налоги". В брокерском отчете они есть. Операции от 04.01.2021 и 08.01.2021.

**Comment by AlexanderVolkovTCS** [comment]
Проблема не только в api, наблюдается в мобильном приложении?

если да - рекомендуем написать запрос в техподдержку через приложение,
если нет - то укажите треккинг запроса, пожалуйста.

**Comment by progamer75** [comment]
Да, в мобильном приложении таже проблема. Написал в техподдержку. Крайне печально что некоторые операции теряются.

**Comment by AlexanderVolkovTCS** [comment]
Вопрос должен решиться в техподдержке
