### ISSUE TITLE
Не получается совершить покупку инструмента

### ISSUE THREAD

**Issue by ivlevnikita** [Tinkoff/investAPI#128]
Работаю через счет песочницы, выставляю заявку на покупку инструмента:

print(self.client.sandbox.post_sandbox_order(
    figi=share_figi, // share_figi получаю по тикеру из метода instruments.shares
    quantity=1, // 1 штука
    price=Quotation(units=price.units, nano=price.nano), // цену получаю из стрима SubscribeLastPriceRequest
    direction=OrderDirection(1), // покупка
    account_id=self.acc_id, // токен счета-песочницы
    order_type=OrderType(2), // рыночная заявка
    order_id=str(datetime.utcnow().timestamp()))) // идемпотентность
    
Получают в ответ:

PostOrderResponse(order_id='31089126-34f7-4dcf-8600-614df9937799', execution_report_status=<OrderExecutionRe
portStatus.EXECUTION_REPORT_STATUS_NEW: 4>, lots_requested=1, lots_executed=0, initial_order_price=MoneyValu
e(currency='usd', units=0, nano=0), executed_order_price=MoneyValue(currency='usd', units=0, nano=0), total_
order_amount=MoneyValue(currency='usd', units=1119, nano=730000000), initial_commission=MoneyValue(currency=
'usd', units=0, nano=0), executed_commission=MoneyValue(currency='usd', units=0, nano=0), aci_value=MoneyVal
ue(currency='', units=0, nano=0), figi='BBG000N9MNX3', direction=<OrderDirection.ORDER_DIRECTION_BUY: 1>, in
itial_security_price=MoneyValue(currency='usd', units=1119, nano=730000000), order_type=<OrderType.ORDER_TYP
E_MARKET: 2>, message='', initial_order_price_pt=Quotation(units=0, nano=0))

То есть заявка выставляется, но не выполняется (lots_executed=0). Далее пробую выводить список ордеров:

GetOrdersResponse(orders=[OrderState(order_id='31089126-34f7-4dcf-8600-614df9937799', execution_report_statu
s=<OrderExecutionReportStatus.EXECUTION_REPORT_STATUS_NEW: 4>, lots_requested=1, lots_executed=0, initial_or
der_price=MoneyValue(currency='usd', units=1119, nano=730000000), executed_order_price=MoneyValue(currency='
usd', units=0, nano=0), total_order_amount=MoneyValue(currency='usd', units=1119, nano=730000000), average_p
osition_price=MoneyValue(currency='', units=1119, nano=730000000), initial_commission=MoneyValue(currency='u
sd', units=0, nano=0), executed_commission=MoneyValue(currency='usd', units=0, nano=0), figi='BBG000N9MNX3',
 direction=<OrderDirection.ORDER_DIRECTION_BUY: 1>, initial_security_price=MoneyValue(currency='usd', units=
1119, nano=730000000), stages=[], service_commission=MoneyValue(currency='usd', units=0, nano=0), currency='
usd', order_type=<OrderType.ORDER_TYPE_MARKET: 2>, order_date=datetime.datetime(2022, 4, 5, 15, 20, 3, 22704
7, tzinfo=datetime.timezone.utc))])  

Заявка висит, но через некоторое время пропадает, так и не исполнившись.

Пробовал покупать инструменты $TSLA, $AAPL, $HAL - самые популярные, но результат один и тот же. Может быть я что-то не понимаю? Или через счёт песочницы нельзя производить покупку инструментов? Буду рад помощи.

**Comment by betslus1** [comment]
Кстати обратил внимание, что для в рыночной заявке не нужно Price указывать. Возможно это сломало логику работы песочницы которую тестировали разработчики и вызвало баг.

price=Quotation(units=price.units, nano=price.nano), // цену получаю из стрима SubscribeLastPriceRequest

Для лимитной заявки сделка по цене lastPrice не гарантирует выполнение, там надо стакан смотреть и выставлять по лучшей цене, это надежнее.

**Comment by ivlevnikita** [comment]
Закомментировал строчку с ценой, ничего не изменилось, проблема осталась

**Comment by hondasmx** [comment]
Мы делали много правок по работе песочницы 
Данная проблема не должна больше проявляться

Если проблема все еще присутствует - переоткройте issue
