### ISSUE TITLE
Можно пример, как правильно сгенерировать grpc модуль в Golang?

### ISSUE THREAD

**Issue by vodolaz095** [Tinkoff/investAPI#129]
Раньше я использовал официальную библиотеку https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk
но теперь похоже она перестала работать. При попытке авторизации с только что сгенерированным токеном получаю такой ответ
```
TrackingID: b6987e17dd008fe2, Status: Error, Message: Invalid token scopes, Code: GATEWAY_REQUEST_DATA_ERROR, Hint:  : while connecting to rest api
```

Я пытаюсь разобраться с новой, этой, библиотекой:

```
[vodolaz095@steel contracts]$ protoc --go_out=.  common.proto 
google/protobuf/timestamp.proto: File not found.
common.proto:12:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
common.proto:62:3: "google.protobuf.Timestamp" is not defined.
```
но в документации о генерации клиента для Go ничего не объяснено.

Я буду признателен, если мне объяснят, как правильно сгенерировать обёрку для Go из `proto` файлов
Какие версии protoc устанавливать? Какой именно командой правильно генерировать golang модуль?
Какие-то потуги сгенерировать модуль на го в коде я нашёл,
https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/common.proto#L5
но всё равно не понятно, как это делать правильно

Как клиент вашего банка (брокерский счёт 2102667835) я очень опечален уровнем сервиса и качеством документации к вашим продуктам.

С уважением, Анатолий

**Comment by vodolaz095** [comment]
вродебы весь инструментарий установлен, но не взлетает

```
[vodolaz095@steel contracts]$ protoc --go_out=. --go_opt=paths=source_relative     --go-grpc_out=. --go-grpc_opt=paths=source_relative     common.proto 
google/protobuf/timestamp.proto: File not found.
common.proto:12:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
common.proto:62:3: "google.protobuf.Timestamp" is not defined.
[vodolaz095@steel contracts]$ protoc --version
libprotoc 3.17.3
[vodolaz095@steel contracts]$ which protoc-gen-go 
~/go/bin/protoc-gen-go
[vodolaz095@steel contracts]$ 
```

**Comment by SinnerUfa** [comment]
В bat я сделал так:
@echo off
protoc --proto_path=./contracts --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./contracts/*.proto
pause

**Comment by SinnerUfa** [comment]
Вот тут посмотрите:
https://grpc.io/docs/languages/go/quickstart/

**Comment by SinnerUfa** [comment]
В документации Тинькофф в общем-то указаны ссылки (https://tinkoff.github.io/investAPI/grpc/).
Вот по этому адресу можно найти всю документацию по Go (https://grpc.io/docs/languages/go/ )
В частности необходимо :
1 Установить Protocol Buffer Compiler (https://grpc.io/docs/protoc-installation/), при этом файлы .proto (папка include, там же timestamp.proto) лучше чтобы находились в той же директории что и protoc (наиболее простое решение, если protoc их не находит, из-за не тех переменных окружения например).
2 Установить плагины
$ go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
$ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
Хотя лучше без указания версий, то есть так:
$ go install google.golang.org/protobuf/cmd/protoc-gen-go 
$ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
3 Обновить переменные окружения)
4 Запустить генерацию файлов Go
В свое время так же пришлось разбираться, хоть и не под иксы, но вроде все работает:)

**Comment by SinnerUfa** [comment]
Собственно вот Readme от варианта для иксов, и вроде бы все понятно:
Protocol Buffers - Google's data interchange format
Copyright 2008 Google Inc.
https://developers.google.com/protocol-buffers/

This package contains a precompiled binary version of the protocol buffer
compiler (protoc). This binary is intended for users who want to use Protocol
Buffers in languages other than C++ but do not want to compile protoc
themselves. To install, simply place this binary somewhere in your PATH.

**If you intend to use the included well known types then don't forget to
copy the contents of the 'include' directory somewhere as well, for example
into '/usr/local/include/'.**

Please refer to our official github site for more installation instructions:
  https://github.com/protocolbuffers/protobuf

**Comment by vodolaz095** [comment]
Я сделал репозиторий с обвязкой на go, которая генерируется из *.proto файлов: 

https://github.com/vodolaz095/go-investAPI

Также там есть скрипт `generate.sh` который клонирует исходный код https://github.com/Tinkoff/investAPI 
и заново генерирует код обвязки.

хотя, я не уверен, что сгерерированный код клиента должен использоваться именно так, как я указал в примере.
Но он вродебы работает. 

Я буду признателен, если кто-либо сможет улучшить мой код или официальные представители банка Тинькофф сделают пример, как тут https://github.com/Tinkoff/invest-openapi-go-sdk/blob/master/examples/main.go для стабильной библиотеки.

С уважением, Анатолий.

**Comment by SinnerUfa** [comment]
О, спасибо, не видел этой ссылки в списке официальных SDK. М-да, в общем те же сгенерированные файлы и обвязка в примере (что собственно и должно было быть SDK :) ).  По большому счету при использовании gRPC SDK (под Go во всяком случае) не особо то и нужен, разве что как пример.
