### ISSUE TITLE
в https://www.tinkoff.ru/invest/settings/ нет возможности создать Read Only токен

### ISSUE THREAD

**Issue by GregoryPletnev** [Tinkoff/investAPI#13]
в документации https://tinkoff.github.io/investAPI/token/   описано 4 типа токенов (скрин ниже). Однако по указанной там ссылке возможности получить например токен read only или токен для  конкретного счета - нет.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/54290989/148831292-f59b26d7-2f6f-44c3-aceb-05fe044112d1.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/54290989/148831688-40646726-bf7d-4969-af93-a7fad494568f.png">

Как получит токен только для чтения ?

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер, обновление формы выпуска токена планируется в ближайшем релизе web-а (ориентировочно на следующей неделе).

**Comment by GregoryPletnev** [comment]
Спасибо)
Думал искал не там, но так тоже хорошо

**Comment by allexme** [comment]
@AlexanderVolkovTCS 
Приветствую! Будет ли Readonly token работать с первой версией API?

**Comment by AlexanderVolkovTCS** [comment]
>Приветствую! Будет ли Readonly token работать с первой версией API?

Добрый день, нет, токен выпускаемый как readonly, будет работать только со второй версией. В первой с ним не получится сделать никаких запросов.
