### ISSUE TITLE
Не выставляются заявки в облигациях

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#130]
Ругается что цена меньше 62.84 при цене заявки 67.798

REQ:
{"account_id":"2088918905","quantity":91,"price":{"units":67,"nano":798000000},"direction":"ORDER_DIRECTION_SELL","order_type":"ORDER_TYPE_LIMIT","order_id":"e3b5c0de-6a17-4eab-bee4-e4ff9aab2ec1","figi":"BBG011MLGP84","isDebug":false,"isEncodeRequest":false}

RES:
{"type":"error","descr":"tinkoff_v2.js: Не удалось выполнить : Orders.PostOrder({\"account_id\":\"2088918905\",\"quantity\":91,\"price\":{\"units\":67,\"nano\":798000000},\"direction\":\"ORDER_DIRECTION_SELL\",\"order_type\":\"ORDER_TYPE_LIMIT\",\"order_id\":\"e3b5c0de-6a17-4eab-bee4-e4ff9aab2ec1\",\"figi\":\"BBG011MLGP84\",\"isDebug\":false,\"isEncodeRequest\":false})","resp":"Error: 3 INVALID_ARGUMENT: 30049 \n tracking-id: 14861a458bfcbd0c967f2191176ea1b5 \n message: \"post order error: Dlya vy`brannogo finansovogo instrumenta czena dolzhna by`t` ne men`she 62.8400\" \n date: \"Wed, 06 Apr 2022 12:21:43 GMT\" \n x-ratelimit-limit: \"300, 300;w=60\" \n x-ratelimit-remaining: \"299\" \n x-ratelimit-reset: \"20\""}

{
  "figi": "BBG011MLGP84",
  "depth": 1,
  "bids": [
    {
      "price": {
        "units": "67",
        "nano": 601000000
      },
      "quantity": "6"
    }
  ],
  "asks": [
    {
      "price": {
        "units": "67",
        "nano": 783000000
      },
      "quantity": "2"
    }
  ],
  "limitUp": {
    "units": "73",
    "nano": 122000000
  },
  "limitDown": {
    "units": "62",
    "nano": 840000000
  }
}

**Comment by nonamegithub** [comment]
https://github.com/Tinkoff/investAPI/issues/9

**Comment by betslus1** [comment]
> https://github.com/Tinkoff/investAPI/issues/9

Ну я работаю с пунктами, без использования рублей. ЛимитАп в пунктах/ошибка в пунктах/ ордербук в пунктах и я передаю в пунктах .

**Comment by betslus1** [comment]
> сделай в рублях - пройдет. там черт ногу сломит, че разрабы наворотили.

Офигеть

**Comment by nonamegithub** [comment]
офигеть можно будет, когда до стоп-ордеров дойдешь. вот в них в пунктах цену надо указывать.

**Comment by betslus1** [comment]
> офигеть можно будет, когда до стоп-ордеров дойдешь. вот в них в пунктах цену надо указывать.

😂 

У меня свои стопы... 

Но функции перевода quotation <-> money буду писать ещё для фьючерсов и валют, там вероятно точно офигею.
Ибо разные размеры лота, номинала,  плавающий номинал и плавающий инкремент...

**Comment by AlexanderVolkovTCS** [comment]
#132
