### ISSUE TITLE
IllegalArgumentException при вызове api.getOperationsService().getPortfolioSync(id)

### ISSUE THREAD

**Issue by ivanglushnev** [Tinkoff/investAPI#134]
при вызове метода api.getOperationsService().getPortfolioSync(id) выбрасывается исключение IllegalArgumentException.

x-tracking-id = e29a43a4effc66d1112a7140a3fe9288

происходит при обработке figi BBG004731489

в отладке и логах нет информации, которая помогла бы понять, в чем причина.

**Comment by hondasmx** [comment]
Проблема была исправлена 08.04.2022
