### ISSUE TITLE
Описание поля uid (версия 1.06)

### ISSUE THREAD

**Issue by SinnerUfa** [Tinkoff/investAPI#136]
В связи с вводом в версии 1.06 поля уникального идентификатора для инструментов (uid), хотелось бы уточнить следующее для него:
1. Принцип формирования
2. Отношение с полем figi
3. Источник (где формируется, хранится и время его хранения)
И, если возможно, то добавить в документацию его подробное описание.

**Comment by Fi1osof** [comment]
Что-то сейчас вообще в ответе поле uid - пустая строка. То есть он даже не null. В итоге при попытке использовать upsert по этому полю просто перетипается одна запись. Не круто...

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер, пока поле пустое, в дальнейшем будет идентификатором инструмента либо актива, необходимо для будущей поддержки опционов. В документацию будет добавлено по старту заполнения поля.
