### ISSUE TITLE
Что случилось с названиями ценных бумаг?

### ISSUE THREAD

**Issue by hommeideal** [Tinkoff/investAPI#138]
Со вчерашнего дня заметил что в результате запроса по акциям https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.InstrumentsService/Shares вместо привычных названий ценных бумаг вижу что-то типа BASF SE ORDSHS, паи БПИФ рфи ТинькНасдакТех, Apple Inc ORD SHS, ВТБ ПАО ао07, Сбербанк ПАО ап03 и т.п. Это так и задумано? Раньше было красиво и наименования инструментов соответствовали наименованиям в официальном приложении Тинькофф.

**Comment by AlexanderVolkovTCS** [comment]
Смена поставщика данных. Названия уже приведены в старое значение.
