### ISSUE TITLE
Дополнить поток сформированными свечами (минутные, пятиминутные, часовые, дневные)

### ISSUE THREAD

**Issue by HappyManRus** [Tinkoff/investAPI#141]
Добрый день.

**Как сейчас:**
В протоколе есть SubscribeCandlesRequest. Сейчас в этом потоке идут данные каждые несколько секунд, и происходит формирование текущей свечи. Понять когда закончила формироваться предыдущая и начала формироваться новая свеча можно примерно, отлавливая данные на границе временных диапазонов.

**Как ожидалось:**
В каждый момент времени приходит информация по готовой и сформированной свече (раз в таймфрейм).
Например если у меня стоит подписка на часовые свечи, то в начале каждого часа я получаю информацию о закрытой в предыдущем часе свече. Также по минутным, пятиминутным свечам и суточным.
Возможна реализация в виде флага, когда в потоке некоторые сообщения промаркированы как итоговые по данному таймфрейму (следующие сообщения будут формировать новую свечу).
Или сделать отдельный поток, где будут приходить готовые свечи сразу по нескольким таймфреймам (поток сформированных свечей).

Если эта фича кому-то нужна кроме меня - прошу рассмотреть возможность добавления её в бэклог. (Не критично)
Спасибо!

**Comment by AlexanderVolkovTCS** [comment]
Не видим смысла транслировать часовые или суточные свечи - их проще запросить одиночными unary запросами.

С вариантом однократной отправки свечи при закрытии минуты есть сложность - биржа не гарантирует очередность отправки, поэтому сделка за 10:30:59 может прийти и в 10:31:01. И каждая такая сделка будет заново "перезакрывать" минуту. Есть вариант в таких случаях высылать свечу повторно, либо делать большую задержку.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
добавлен флаг ожидания свечи https://tinkoff.github.io/investAPI/marketdata/#subscribecandlesrequest

**Comment by nonamegithub** [comment]
> По минутным свечам описанный функционал был бы очень полезен, отлавливать свечи, завершающие минутный интервал, не очень удобно.

[Надо помочь убедить разработчиков в необходимости создания функционала)](https://github.com/Tinkoff/investAPI/issues/388)
