### ISSUE TITLE
Признак обязательности полей

### ISSUE THREAD

**Issue by Fi1osof** [Tinkoff/investAPI#144]
В сваггере первой версии АПИ в схемах были указаны обязательные поля звездочками (без звездочек - необязательные). Сваггер 2 версии нигде не указаны обязательные поля. Будет ли дополнена эта информация?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, на данный момент swagger является proxy-надстройкой над grpc сервисом и все поля являются обязательными.

**Comment by Fi1osof** [comment]
Я чуть расширю вопрос: имел ввиду обязательные не только по наличию самого поля, а в том числе и по значению. У вас сейчас не все поля в ответе содержат значения. То есть если я в поле ожидаю согласно схеме строку, то и предполагаю, что получу ответ и точно с ним смогу выполнить какие-то действия, типа value.toUpperCase(). В вашем же случае умеет прилетать пустое значение и  value.toUpperCase() вызовет ошибку.
Второй момент: это база данных. Там я указываю признак nullable. Согласно текущей схеме я не могу этого сделать. Выставлять все в nullable = true - вообще не вариант.

**Comment by olsh** [comment]
Вопрос актуален не только для swagger, в основной документации тоже непонятно какие поля обязательные.
К примеру запрос PostOrder
https://tinkoff.github.io/investAPI/orders/#postorderrequest

С основными полями все относительно понятно, они обязательные. Но допустим такие поля как `order_id`, `account_id` - не совсем ясно.

**Comment by inferrna** [comment]
Надо всего лишь научиться читать документацию между строк. Вот, например, намёк на то, что не все поля необязательные:
![2022-08-22_23-52](https://user-images.githubusercontent.com/4245277/186006874-93444ec1-0bf6-4e3b-85c6-b356e6281bc7.png)

А если серьёзно, дорогие разработчики, пора бы перестать валять дурака.
