### ISSUE TITLE
Превышение лимитов tradesStream

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#145]
Добрый день, 
Прошу рассмотреть техническую возможность (вдруг это очень легко сделать) при превышении лимита по tradesStream,
Отключать не самый свежий, а самый старый стрим.
Не получается корректно его завершать (не обрывать), и надо ждать минуту между запусками.

**Comment by AlexanderVolkovTCS** [comment]
Увеличили на 1 максимальное количество открытых tradeStream на период серверного таймаута.
