### ISSUE TITLE
Шаг цены фьючерса - min_price_increment

### ISSUE THREAD

**Issue by brkly** [Tinkoff/investAPI#149]
Перевод цены фьючерса в валюту
Стоимость фьючерсов так же предоставляется в пунктах, для пересчёта можно воспользоваться формулой:
    price / min_price_increment * min_price_increment_amount
Где
    price — текущая котировка ценной бумаги;
    min_price_increment — шаг цены;
    min_price_increment_amount — стоимость шага цены.

По фьючерсу FUTBR0522000, GetFuturesMargin возвращает:
min_price_increment=Quotation(units=0, nano=10000000)
min_price_increment_amount=Quotation(units=7, nano=648450000)
Так, согласно формуле, цена 104,92 / 0.1 * 7.6484 = 8024,70 что ниже любого из ГО
initial_margin_on_buy=MoneyValue(currency='rub', units=28377, nano=120000000)
initial_margin_on_sell=MoneyValue(currency='rub', units=28578, nano=810000000)

**Согласно биржевой спецификации и торгов должно быть 0.01**

В команде Futures возвращается (вероятно по всем) -min_price_increment=Quotation(units=0, nano=0)

**Comment by AlexanderVolkovTCS** [comment]
>min_price_increment=Quotation(units=0, nano=10000000)

это и есть 0.01.

104,92 / 0.01 * 7.6484 = 80247
