### ISSUE TITLE
70001 - StatusCode.INTERNAL - при вызове GetPositions

### ISSUE THREAD

**Issue by alexanderkmd** [Tinkoff/investAPI#15]
Вывод grpc python:

status = StatusCode.INTERNAL
details = "70001"
debug_error_string = "{"created":"@1641994452.248349000","description":"Error received from peer ipv4:91.194.227.80:443","file":"src/core/lib/surface/call.cc","file_line":1075,"grpc_message":"70001","grpc_status":13}"

**Comment by AlexanderVolkovTCS** [comment]
Укажите, пожалуйста, trackingID операции.

**Comment by alexanderkmd** [comment]
Уже разрешилось. Трекинг не записал. 
была больше чем пол часа по Москве с 1605 до далее чем 1640.

**Comment by AlexanderVolkovTCS** [comment]
Да, в это время был инцидент.
