### ISSUE TITLE
required поля

### ISSUE THREAD

**Issue by inferrna** [Tinkoff/investAPI#155]
В соответствии со спецификацией swagger поля, не помеченные required, не являются обязательными. Соответственно, согласно вашей спецификации, можно передать, к примеру
`v1GenerateBrokerReportRequest {}`
и это будет валидным запросом. Вы уверены, что так и надо? В прежней версии required был расставлен для всех полей, прошу исправить.

В текущем виде, вкупе с #154, это больше похоже на API для торговли не ценными бумагами, а, простите, колбасой.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
Invest API построено на gRPC, swagger прокси является шлюзом поверх него и swagger контракт генерируется на основе protobuf контрактов.

Но в protobuf 3 в нет понятия обязательного поля, все поля необязательные, чтобы упростить обеспечение двусторонней совместимости, поэтому и в сваггер оно импортируется аналогично.

Но спасибо за предложение, раз у клиентов есть запрос на required поля, то мы подумаем, как можно реализовать их поддержку автоматически.

**Comment by AlexanderVolkovTCS** [comment]
optional появился в protobuf версии 3.12.0 и все клиенты, которые пользуются более старым компилятором protoc (думаю у нас такие есть) могут испытывать проблемы с генерацией исходников
https://github.com/grpc/grpc-java/issues/7051

Также возможны проблемы со старыми версиями некоторых библиотек или grpc-плагином для protoc
https://github.com/vert-x3/vertx-grpc/issues/75


Но в сваггер в любом случае подумаем, как затащить.
