### ISSUE TITLE
GetWithdrawLimits и ИИС

### ISSUE THREAD

**Issue by alexanderkmd** [Tinkoff/investAPI#16]
Запрос выдает список валют на счету, однако, на сколько я помню, для ИИС вывод не предусмотрен без закрытия счета.

А для получения позиций валют с блокировками есть метод GetPositions. 

Это баг или фича? Не должен ли GetWithdrawLimits давать пустой ответ в ИИС?

**Comment by AlexanderVolkovTCS** [comment]
Метод должен единообразно работать для всех типов счетов.
Хоть метод и частично дублируется позициями, но позволяет быстро узнать, какое есть количество свободных средств на счету для покупки активов.
