### ISSUE TITLE
API v2 метод GetDividendsForeignIssuer дублирующиеся строчки

### ISSUE THREAD

**Issue by polkila** [Tinkoff/investAPI#160]
Часто последняя или предпоследняя запись за период одного месяца дублируется в начале следующего месяца.
Даты указываю от первого числа до первого числа: 2022-04-01 — 2022-05-01 или 2022-09-01 — 2022-10-01 .
Примерно 7 случаев из 11 переходов на следующий месяц.
<img width="514" alt="2022-05-01_14-59-09" src="https://user-images.githubusercontent.com/5267172/166144884-5c9a4edd-b4a9-4919-9cbc-caeb8b513d3f.png">
<img width="533" alt="2022-05-01_14-59-47" src="https://user-images.githubusercontent.com/5267172/166144892-cd6f4a1d-62e7-4760-82d5-d4372d964618.png">
<img width="502" alt="2022-05-01_15-02-03" src="https://user-images.githubusercontent.com/5267172/166144996-ae247b99-088e-4c05-ad11-65ddb76883e6.png">
<img width="540" alt="2022-05-01_15-02-55" src="https://user-images.githubusercontent.com/5267172/166145006-9beb9e0c-bf53-43f8-9e27-4923896c34c1.png">
<img width="497" alt="2022-05-01_15-10-07" src="https://user-images.githubusercontent.com/5267172/166145265-f463ec93-517c-43f8-b38b-d42f8812191e.png">
<img width="499" alt="2022-05-01_15-10-39" src="https://user-images.githubusercontent.com/5267172/166145272-7a0b3ea0-fbe9-4bc1-869d-30e0a9acbe12.png">

**Comment by malyginvv** [comment]
Добрый день!
Подскажите пожалуйста, каким образом Вы формируете запрос? Используете ли SDK?

Отчет формируется на даты от `from` до `to` включительно.
Также обратите внимание, что параметры `from` и `to` ожидаются в часовом поясе UTC.
Например, если указать дату `2022-05-01T00:00:00+03:00`, то она будет преобразована в `google.protobuf.Timestamp`
```json
{
  "seconds": 1651352400,
  "nanos": 0
}
```
На сервере API число секунд `1651352400` будет обработано как `2022-04-30T00:00:00+00:00`, и будет применена дата `2022-04-30`.

**Comment by polkila** [comment]
Отправлял без SDK следующий запрос:
```
  generate_div_foreign_issuer_report: {
    account_id: 'ччч',
    from: { seconds: 1619827200, nanos: 0 },
    to: { seconds: 1622505600, nanos: 0 }
  }
```
Это получаются такие даты:
2021-05-01T00:00:00.000Z
2021-06-01T00:00:00.000Z

Правильно ли я понял, что в отчёт будет включён весь день 1 июня?

Сейчас сервер возвращает пустой результат. На момент создания issue возвращал отчёт за май.

**Comment by AlexanderVolkovTCS** [comment]
>Правильно ли я понял, что в отчёт будет включён весь день 1 июня?

Да, верно

>Сейчас сервер возвращает пустой результат

Может быть был превышен лимит на запросы?

**Comment by polkila** [comment]
> Может быть был превышен лимит на запросы?

Нет.

```
{
  "generateDivForeignIssuerReport": {
    "accountId": "ччч",
    "from": "2021-05-01T00:00:00.000Z",
    "to": "2021-06-01T00:00:00.000Z"
  }
}
```
x-tracking-id: 5da211070dc79554acd76c96e531c035
date: Wed, 11 May 2022 10:27:23 GMT
x-ratelimit-remaining: 4

**Comment by polkila** [comment]
Обращаю ваше внимание на то, что отчёт не выгружается.

**Comment by polkila** [comment]
@AlexanderVolkovTCS 
Каким образом дублируется запись с датой 2021-06-02T00:00:00.000Z не подскажете?
Указываю даты:
2021-05-01T00:00:00.000Z
2021-06-01T00:00:00.000Z
И в следующем запросе указываю даты на месяц больше:
2021-06-01T00:00:00.000Z
2021-07-01T00:00:00.000Z
```
  generate_div_foreign_issuer_report: {
    account_id: 'ччч',
    from: { seconds: 1619827200, nanos: 0 },
    to: { seconds: 1622505600, nanos: 0 }
  }
```

**Comment by polkila** [comment]
Сегодня повторяю любой из 12 запросов, отправленных ранее, например:
```
{
  "generateDivForeignIssuerReport": {
    "accountId": "ччч",
    "from": "2021-02-01T00:00:00.000Z",
    "to": "2021-03-01T00:00:00.000Z"
  }
}
```
x-tracking-id: a5d0b9e18e91038405dda6ff442aa695

Получаю пустой результат.
```
{
  "divForeignIssuerReport": {
    "dividendsForeignIssuerReport": [],
    "itemsCount": 0,
    "pagesCount": 0,
    "page": 0
  }
}
```

Далее меняю дату на 1 день и отправляю снова:
```
{
  "generateDivForeignIssuerReport": {
    "accountId": "xxx",
    "from": "2021-02-01T00:00:00.000Z",
    "to": "2021-02-28T00:00:00.000Z"
  }
}
```
x-tracking-id: f8afa647cd5dbaddfc42d3107d3522c5

Получаю task_id, затем список за месяц.
```
{
  "generateDivForeignIssuerReportResponse": {
    "taskId": "272850e1-851c-4761-bf1a-6c7af4ff6481"
  }
}
```

**Comment by polkila** [comment]
@AlexanderVolkovTCS
