### ISSUE TITLE
API v2 метод GetDividendsForeignIssuer. Пропускаются строчки

### ISSUE THREAD

**Issue by polkila** [Tinkoff/investAPI#161]
При проверке обнаружил, что в отчёте выгруженном через api, не достаёт одной позиции. Добавил её вручную.
```
    {
        "record_date": "2021-12-01T00:00:00.000Z",
        "payment_date": "2021-12-27T00:00:00.000Z",
        "security_name": "eBay Inc._ORD SHS",
        "isin": "US2786421030",
        "issuer_country": "США",
        "quantity": 9,
        "dividend": 0.18,
        "external_commission": 0,
        "dividend_gross": 1.62,
        "tax": 0.16,
        "dividend_amount": 1.46,
        "currency": "USD"
    },
```
<img width="1124" alt="2022-05-01_21-03-22" src="https://user-images.githubusercontent.com/5267172/166158617-05215ef6-a348-42c9-9818-ae3e6163a008.png">

**Comment by hondasmx** [comment]
Добрый день!
Напишите мне в телеграмме (@againanov) в личку свой siebel + accountId,

**Comment by hondasmx** [comment]
Мы сделали несколько правок для данного метода.
Есть ли еще проблема?
