### ISSUE TITLE
GetBondCoupons возвращает купоны с неправильным figi

### ISSUE THREAD

**Issue by RainManVays** [Tinkoff/investAPI#162]
При запросе купонов по облигации  с figi": "BBG00V92X4F6"
возвращаются купоны с "figi": "TCS00A101QF7"

GetBondCoupons
{
  "figi": "BBG00V92X4F6",
  "from": "1970-01-01T00:02:03.000000123Z",
  "to": "2070-01-01T00:02:03.000000123Z"
}

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за репорт, исправлено.
