### ISSUE TITLE
70001 Внутренняя ошибка сервиса

### ISSUE THREAD

**Issue by AleksGelvides** [Tinkoff/investAPI#165]
Добрый день! Столкнулся с такой проблемой
Взял из примера randomFigi, мой код:
```
var figi = api.getInstrumentsService().getTradableSharesSync()
                    .stream()
                    .filter(el -> Boolean.TRUE.equals(el.getApiTradeAvailableFlag()))
                    .map(Share::getFigi)
                    .limit(5)
                    .collect(Collectors.toList());
```
Так же не работает простое получение котировок:
```
api.getMarketDataService()
                .getCandlesSync(figi, Instant.now().minus(1, ChronoUnit.DAYS), Instant.now(), CandleInterval.CANDLE_INTERVAL_5_MIN);
```
Подскажите пожалуйста, что я делаю не так?
Использую Java 17, SpringBoot 2.6.7

**Comment by hondasmx** [comment]
Добрый день!
При возникновении ошибки в логе должна быть запись с tracking_id. Напишите его сюда, пожалуйста.

Так же, проверьте, что верно указан токен при создании экземпляра InvestApi

**Comment by AleksGelvides** [comment]
Добрый вечер. Да, ошибка была в токене. Спасибо!
