### ISSUE TITLE
GetBondsCoupon выдает ошибку при запросе купонов для конкретного бонда

### ISSUE THREAD

**Issue by RainManVays** [Tinkoff/investAPI#166]
При запросе купонов по TCS878009866
возвращается 70001

x-tracking-id:  3d4898228b619cb020a27737c0a4e295
{
  "figi": "TCS878009866",
  "from": "2020-01-01T00:02:03.000000123Z",
  "to": "2022-06-20T00:02:03.000000123Z"
}

**Comment by AlexanderVolkovTCS** [comment]
Проблема решена
