### ISSUE TITLE
Открытие ордера в шорт

### ISSUE THREAD

**Issue by bugagashkovich** [Tinkoff/investAPI#168]
Добрый день! Не могу найти в документации как открыть шорт. 
Поиск по документации выдает только комментарий по данному вопросу в разделе FAQ песочницы.

**Comment by polkila** [comment]
> Добрый день! Не могу найти в документации как открыть шорт. Поиск по документации выдает только комментарий по данному вопросу в разделе FAQ песочницы.

1. Включите маржинальную торговлю.
2. [Выставите заявку](https://tinkoff.github.io/investAPI/orders/#postorder) с направлением [SELL](https://tinkoff.github.io/investAPI/orders/#orderdirection).
