### ISSUE TITLE
PortfolioPosition, возвращаемое getPortfolio, не включает тикер и название бумаги.

### ISSUE THREAD

**Issue by irishrover** [Tinkoff/investAPI#17]
Из-за этого приходится делать лишние запросы.

**Comment by betslus1** [comment]
Там же figi есть?

**Comment by alexanderkmd** [comment]
инструмент все равно придется подтягивать.
Там номинал, например, для расчета стоимости облигации. Да и других десяток параметров, отдельные - пригождаются в анализе.
А для просто трейдинга- figi - предостаточно.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, 
верно, подробную информацию по бумаге из портфолио можно подтянуть из сервиса инструментов.
Пока менять эту схему не планируем.
