### ISSUE TITLE
Метод GetSandboxPortfolio отдаёт неверное значение поля валюта (currency)

### ISSUE THREAD

**Issue by ako2345** [Tinkoff/investAPI#170]
После покупки 238 акций по $146,46 (всего на $34857,48) метод GetSandboxPortfolio возвращает:
```
  "totalAmountShares": {
    "currency": "rub",
    "units": "34857",
    "nano": 480000000
  }
```
Значения units и nano верные, а вот в качестве валюты (currency) должно быть "usd".
Возможно, такая же ошибка есть и в боевом методе.

**Comment by betslus1** [comment]
Не буду отдельный тикет создвать

в этом методе отсутсвует quantity_lot

Т.е. нельзя сейчас переключать sandbox <-> real

**Comment by AlexanderVolkovTCS** [comment]
>Значения units и nano верные, а вот в качестве валюты (currency) должно быть "usd".

Нет, стоимость портфеля рассчитывается в рублях как на боевом методе, так и в sandbox, это не ошибка.

>в этом методе отсутсвует quantity_lot

сейчас quantity_lot есть, контракт ответа метода PortfolioResponse одинаковый и для боевого метода и для песочницы
