### ISSUE TITLE
В объектах Future отсутствует поле min_price_increment

### ISSUE THREAD

**Issue by YellowOrWhite** [Tinkoff/investAPI#171]
В соответствии с документацией: https://tinkoff.github.io/investAPI/instruments/#future
должно быть поле min_price_increment, но сервер его не возвращает.

**Comment by inferrna** [comment]
Разработчики пока не определились, являются ли все поля обязательными, или все поля необязательные, или необязательные лишь только некоторые из них. И не решат, покуда в одной далёкой галактике кто-то использует старую версию protobuf, которую эти джедаи зачем-то обязались поддерживать.
 https://github.com/Tinkoff/investAPI/issues/155

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, для фьючерсов текущий min_price_increment возвращает функция https://tinkoff.github.io/investAPI/instruments/#getfuturesmarginresponse

**Comment by YellowOrWhite** [comment]
> Добрый день, для фьючерсов текущий min_price_increment возвращает функция https://tinkoff.github.io/investAPI/instruments/#getfuturesmarginresponse
Да, возвращает, но какое это имеет отношение к данному тикету? Я написал о несоответствии реализации и документации, что очевидно приводит к ошибкам. Например, [python-tinkoff](https://github.com/Tinkoff/invest-python) отдает ноль в min_price_increment фьючерсов.

Также, вопрос, почему Вы называете min_price_increment текущим? Это же шаг цены из спецификации фьючерса и меняется он также "часто" как размер лота.
