### ISSUE TITLE
Цена в LastPrice по облигациям в OrderBook меньше в 10 раз при лотности 1

### ISSUE THREAD

**Issue by kirimedia** [Tinkoff/investAPI#172]
Запрашиваю MarketDataService/GetOrderBook с {"depth": 1, "figi": BBG003TTSBB1}
В ответе в LastPrice.Units = 98, в доке написано, что нужно умножить на лотность, но лотность иструмента 1, это видно в интерфейса, а также если запросить InstrumentsService.GetInstrumentBy или BondBy с этим Figi.
При этом реальная цена в 10 раз больше (980 с копейками)

**Comment by kirimedia** [comment]
Пример
```
$ curl -X 'POST' 'https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"depth":1,"figi":"BBG003TTSBB1"}' -H 'Authorization: Bearer t.XXX'
{
  "figi": "BBG003TTSBB1",
  "depth": 1,
  "bids": [],
  "asks": [],
  "lastPrice": {
    "units": "98",
    "nano": 5000000
  },
  "closePrice": {
    "units": "98",
    "nano": 5000000
  },
  "limitUp": {
    "units": "100",
    "nano": 686000000
  },
  "limitDown": {
    "units": "95",
    "nano": 412000000
  }
}
```
lastPrice = 98.005 // цена

```
$ curl -X 'POST' 'https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInstrumentBy' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"idType":"INSTRUMENT_ID_TYPE_FIGI","id":"BBG003TTSBB1"}' -H 'Authorization: Bearer t.XXX'
{
  "instrument": {
    "figi": "BBG003TTSBB1",
    "ticker": "SU26211RMFS1",
    "classCode": "TQOB",
    "isin": "RU000A0JTJL3",
    "lot": 1,
    "currency": "rub",
    "klong": {
      "units": "2",
      "nano": 0
    },
    "kshort": {
      "units": "2",
      "nano": 0
    },
    "dlong": {
      "units": "0",
      "nano": 300000000
    },
    "dshort": {
      "units": "0",
      "nano": 300000000
    },
    "dlongMin": {
      "units": "0",
      "nano": 163300000
    },
    "dshortMin": {
      "units": "0",
      "nano": 140200000
    },
    "shortEnabledFlag": false,
    "name": "ОФЗ 26211",
    "exchange": "MOEX_PLUS",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "instrumentType": "bond",
    "tradingStatus": "SECURITY_TRADING_STATUS_BREAK_IN_TRADING",
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "minPriceIncrement": {
      "units": "0",
      "nano": 1000000
    },
    "apiTradeAvailableFlag": true,
    "uid": "",
    "realExchange": "REAL_EXCHANGE_MOEX"
  }
}
```

lot = 1 // Лотность

Итого цена: 98.005 * 1 = 98.005
Но цена этой облигации около 980.

**Comment by nonamegithub** [comment]
[При работе с облигациями следует принимать во внимание  пунктность цены.](https://github.com/Tinkoff/investAPI/issues/9)

**Comment by kirimedia** [comment]
Было бы здорово, если в описании подобных местах было бы указано, что помимо лотности для облигаций надо умножить на 100/номинал.

Сейчас так в доке.
```
Quotation close_price = 6; //Цена закрытия за 1 инструмент. Для получения стоимости лота требуется умножить на лотность инструмента.
```

**Comment by betslus1** [comment]
фьючи еще не смотрел, для остального экспериментально подобрал следующие формулы.

```
function getPriceRaw(opt){
    const max_nanos = 1000000000;
    if (opt.inst.type == 'shares'){
        return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * opt.inst.lot );
    }else
    if (opt.inst.type == 'bonds'){
        return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * opt.inst.nominal / 100 );
    }else
    if (opt.inst.type == 'currency'){
        return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * opt.inst.lot  / opt.inst.nominal);
    }else{
        return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * opt.inst.lot );
    }
}
```

**Comment by b1ng0o** [comment]
https://tinkoff.github.io/investAPI/head-marketdata/

**Comment by betslus1** [comment]
> https://tinkoff.github.io/investAPI/head-marketdata/

У себя исправил уже, но формула для облигаций котрую писал ранее была не совсем верной :)
Новая правильная (иначе не сойдется баланс)

    if (opt.inst.type == 'bonds'){
    	if (opt?.withNKD == 'No'){
        	return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * (parseFloat(opt.inst.nominal) )/ 100 );
    	}else
    	if (opt?.withNKD == 'Yes'){
        	return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * (parseFloat(opt.inst.nominal) + parseFloat(opt.inst.aciValue) )/ 100 );
    	}else{
        	return fixFloat( (parseInt(opt.price.units) + opt.price.nano / max_nanos) * (parseFloat(opt.inst.nominal) + parseFloat(opt.inst.aciValue) )/ 100 );	
    	}
    }

**Comment by b1ng0o** [comment]
Согласен, для  подсчета с учетом НКД надо его считать :) добавлю в доку отдельной формулой)

**Comment by betslus1** [comment]
> Согласен, для подсчета с учетом НКД надо его считать :) добавлю в доку отдельной формулой)

Не все так просто)
неправильно  `price + current_nkd / 100 * nominal`
правильно `price / 100 * nominal + current_nkd `

**Comment by b1ng0o** [comment]
Да, все верно, уже в глазах песок под вечер)
