### ISSUE TITLE
Почему в песочнице ордеру присваивается другой ID?

### ISSUE THREAD

**Issue by ako2345** [Tinkoff/investAPI#173]
![Снимок](https://user-images.githubusercontent.com/2760291/168846605-d7a3842d-084a-4501-859d-56b1a9c98382.PNG)

**Comment by vitalets** [comment]
Из чата:

> Ivan Bezyazychnyy, [13 мая 2022 г., 16:58:34]:
> Привет! Я правильно понял, что в методе PostOrder аргументы PostOrderRequest.order_id и PostOrderResponse.order_id - это разные order_id?
> 
> Vitaliy Potapov, [13 мая 2022 г., 17:11:47]:
> Тоже с этим столкнулся. Я ожидал, что в ответе придет тот же order_id. Alexander , не проясните?
> 
> Vitaliy, [13 мая 2022 г., 17:20:19 (13 мая 2022 г., 17:22:08)]:
> order_id это поле идемпотентности (уникальное на запрос, чтоб исключить повторную отправку), а order_id это id биржевое, и с ним потом и нужно работать
> 
> Если поле идемпотентности не нужно, можно туда просто слать случайный uuidv4 и не сохранять локально
> 
> Ivan Bezyazychnyy, [13 мая 2022 г., 17:33:37]:
> Спасибо. То, что поля с одним и тем же именем имеют разную семантику в запросе и ответе не очевидно. Складывается впечатление, что это подход с client generated id. Было бы понятнее, если бы в запросе это поле называлось по другому, например, client_order_id/idempotency_id/idempotency_key.

**Comment by b1ng0o** [comment]
Так же данная ситуация описана здесь  https://tinkoff.github.io/investAPI/head-orders/
