### ISSUE TITLE
Торговля бумагами Тинькофф

### ISSUE THREAD

**Issue by DiktatorDNS3018** [Tinkoff/investAPI#18]
В итоге, будет ли доступна торговля БПИФ тинькофф через API? Писали "в ближайшее время".

![2022-01-13_18-01-25](https://user-images.githubusercontent.com/44921491/149354534-9e796825-be62-4a6f-a87a-f1682325d76a.png)

Спасибо за новую версию, будем тестировать

**Comment by AlexanderVolkovTCS** [comment]
Да, скоро паи откроются.
