### ISSUE TITLE
Как узнать, что акция включена в котировальные списки?

### ISSUE THREAD

**Issue by Antonboom** [Tinkoff/investAPI#182]
И для работы с ней нужно пройти тест от Тинькофф.

<img src="https://user-images.githubusercontent.com/17127404/169979901-9fd6e555-8f39-4145-b7c2-41c944e8b242.jpg" width="300">

**Comment by AlexanderVolkovTCS** [comment]
Признак вхождения в котировальные списки в апи не выгружается, но вы можете узнать статус прохождения тестов н возможность работы с разными типами бумаг через метод UserService.GetInfo()
