### ISSUE TITLE
У заблокированных по решению ЦБ бумаг не отображается figi в ответе метода AccountsService/GetPositions

### ISSUE THREAD

**Issue by btmc** [Tinkoff/investAPI#187]
Для заблокированных позиций получаю примерно такое в списке `securities`:

```
{
  "figi": "",
  "blocked": "7",
  "balance": "0"
}
{
  "figi": "",
  "blocked": "15",
  "balance": "0"
}
{
  "figi": "",
  "blocked": "3",
  "balance": "0"
}
{
  "figi": "",
  "blocked": "1",
  "balance": "0"
}
```
.

**Comment by SEA99** [comment]
Кстати, если бы figi был заполнен это не позволило бы идентифицировать запись в списке инструментов, так как там в одном списке и заблокированные и незаблокированные и figi не является уникальным идентификатором записи

**Comment by SEA99** [comment]
Есть по 2 записи в результатах getPortfolio и getPositions, но какая к какой относится надо или по порядку ориентироваться или по нулевой сумме у средневзвешенной стоимости. В общем, сильно лучше не стало

надо или 
1) отказаться от разделения на getPortfolio - getPositions или продублировать информацию в getPortfolio для совместимости или
2) идентификатор позиции в портфеле (не figi) и из securities ссылаться на него или
3) разделить по портфелям

**Comment by AlexanderVolkovTCS** [comment]
Вариант решения - продублировать поле blocked в getPortfolio(), аналогично GetPositions()

**Comment by SEA99** [comment]
Ещё одна связанная проблема - не всегда получается правильно определить заблокированные бумаги даже если бумага в портфеле одна - у некоторых бумаг цена покупки 0, так как эти бумаги переехали от другого брокера. Так вот, если выставить лимитную заяку, то эта бумага становится неотличимой от заблокированных ЦБ бумаг, что плохо.
Надо бы добавить отдельный признак для таких бумаг.

**Comment by AlexanderVolkovTCS** [comment]
Поле blocked было добавлено

**Comment by allexme** [comment]
У меня наоборот пропал FIGI и instrumentType у заблокированных бумаг в методе GetPositions. До вчерашний исправлений все работало и баланс считал именно по этим полям. 
`{
	"securities": [
		{
			"blocked": "15",
			"exchangeBlocked": true
		}
	]
}`

Где истина?

**Comment by hondasmx** [comment]
@allexme Добрый день!
Вы можете подсказать ticker/figi или любой другой идентификатор бумаги, которая не отображается?

**Comment by allexme** [comment]
> @allexme Добрый день! Вы можете подсказать ticker/figi или любой другой идентификатор бумаги, которая не отображается?

Бумага AYX (BBG000BGZT72). Рядом запись по той же бумаге (не заблокированная часть), там все в порядке.
