### ISSUE TITLE
Operation.type не типизирован (в openApi - enum)

### ISSUE THREAD

**Issue by GregoryPletnev** [Tinkoff/investAPI#19]
Операция в списке операций имеет свойство Тип (Operation.type), это свойство определено как строка, что несколько неудобно с точки зрения анализа операций. 

В openApi operationType определен как OperationTypeWithCommissionstringEnum:[ Buy, BuyCard, Sell, BrokerCommission, ExchangeCommission, ServiceCommission, MarginCommission, OtherCommission, PayIn, PayOut, Tax, TaxLucre, TaxDividend, TaxCoupon, TaxBack, Repayment, PartRepayment, Coupon, Dividend, SecurityIn, SecurityOut ]

Возможно ли появление специального типа для операций или их справочника (и соответственно ссылки на тип в операции) ?

**Comment by GregoryPletnev** [comment]
пока попробовал собрать таблицу соответствия, но она выглядит грустно:
```
openApi - investAPI
-------------------
Buy - 'Покупка ЦБ', 
BuyCard  - не знаю,
Sell  - не знаю, 
BrokerCommission  - не знаю, 
ExchangeCommission  - не знаю, 
ServiceCommission  - не знаю, 
MarginCommission - 'Удержание комиссии за непокрытую позицию', 
OtherCommission - не знаю, 
PayIn - 'Завод денежных средств', 
PayOut - 'Вывод денежных средств', 
Tax - 'Удержание налога', 
TaxLucre - 'Удержание комиссии за операцию', 
TaxDividend - 'Удержание налога по дивидендам', 
TaxCoupon  - не знаю, 
TaxBack  - не знаю, 
Repayment -'Полное погашение облигаций', 
PartRepayment - 'Частичное погашение облигаций', 
Coupon - 'Выплата купонов', 
Dividend - 'Выплата дивидендов', 
SecurityIn  - не знаю,
SecurityOut  - не знаю,
не знаю -'Доход по сделке РЕПО овернайт',
не знаю - 'accruing_varmargin';
```

**Comment by serejhaaa** [comment]
Добавили в вывод метода enum со списком операций, описание значений есть в контракте: 
https://tinkoff.github.io/investAPI/operations#operationtype
