### ISSUE TITLE
Документация по MarketDataServerSideStream

### ISSUE THREAD

**Issue by vitalets** [Tinkoff/investAPI#196]
Хотелось бы из документации понимать для чего появился `MarketDataServerSideStream` наряду с `MarketDataStream`. Запросы подписки у них похоже одинаковые.

**Comment by AlexanderVolkovTCS** [comment]
Верно, одинаковые.
ServerSideStream необходим для корректной трансляции маркетдаты в браузерные клиенты по gRPC-web, 
который не поддерживает bidirection стримы.
