### ISSUE TITLE
Что с телеграмм каналом? Почему он вдруг отметку "Scam" получил? (вопрос не по API)

### ISSUE THREAD

**Issue by OdCheban** [Tinkoff/investAPI#199]
![image](https://user-images.githubusercontent.com/29703030/173187630-f701c20d-6077-4c51-952e-02bda8cf228e.png)

**Comment by AlexanderVolkovTCS** [comment]
Недоразумение урегулировано, сообщение с пометкой о снятии SCAM отправлено в Телеграм, ждем снятия.
