### ISSUE TITLE
При попытке подписаться на OrderBook всегда возвращается ошибка SUBSCRIPTION_STATUS_DEPTH_IS_INVALID

### ISSUE THREAD

**Issue by igyrus** [Tinkoff/investAPI#20]
Пробую сделать клиента gRPC на C# (.NET 5, VS 2019). 
Подписки на стримы candles, trades и info работают нормально. Но при попытке подписаться на order_book всегда возвращается ошибка, что задана неправильная глубина стакана, какую бы глубину не запрашивал.
Пример кода клиента:

        public async Task SubscribeOrderBookStream(string figi, int depth)
        {
            try
            {
                using (var stream = marketDataStreamServiceClient.MarketDataStream(headers))
                {
                    await stream.RequestStream.WriteAsync(
                        new MarketDataRequest
                        {
                            SubscribeOrderBookRequest = new SubscribeOrderBookRequest()
                            {
                                SubscriptionAction = SubscriptionAction.Subscribe,
                                Instruments =
                                {
                                    new OrderBookInstrument()
                                    {
                                        Figi = figi,
                                        Depth = depth
                                    }
                                }
                            }
                        });

                    var cancellationToken = new CancellationTokenSource(TimeSpan.FromSeconds(15));

                    await foreach (var data in stream.ResponseStream.ReadAllAsync(
                        cancellationToken: cancellationToken.Token))
                    {
                        Console.WriteLine(data.SubscribeOrderBookResponse.OrderBookSubscriptions.First()
                            .SubscriptionStatus);
                    }
                }
            }
            catch (RpcException ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

Возвращается:

    {{ 
	"subscribeOrderBookResponse": { 
		"trackingId": "61e067b00ff20e3b1ab19b3e139da7bc", 
		"orderBookSubscriptions": [ { 
			"figi": "BBG000B9XRY4", 
			"depth": 5, 
			"subscriptionStatus": "SUBSCRIPTION_STATUS_DEPTH_IS_INVALID" 
		} ] 
	} 
    }}

**Comment by malyginvv** [comment]
Добрый день!
В настоящее время поддерживаются следующие значения глубины: 10, 20, 30, 40, 50.

**Comment by igyrus** [comment]
Понял. Спасибо. Просто я ориентировался на фразу в документации "целое число от 1 до 50"

**Comment by AlexanderVolkovTCS** [comment]
Документацию поправим, спасибо!

**Comment by MaximPr** [comment]
@igyrus ,  буду благодарен если скинете свой пример авторизации на c# сюда https://github.com/Tinkoff/investAPI/issues/48 или подскажите что не так
