### ISSUE TITLE
Не хватает лимитов getOrders с ростом числа используемых счетов

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#203]
Добрый день,
если используется 1 счет, то роботы получают информация об активных ордерах каждую секунду, (60 рпм)
с ростом числа счетов задержка начинает увеличиваться (до 6 рпм на 10 счетов) до 10 сек

Прошу рассмотреть различные варианты, как можно увеличить рост активных рабочих счетов (что для робота удобно в плане тестирования алгоритма, разнесения типа активов и тд) не ухудшая показатели лага в обновлении списка заявок.

Возможные варианты: 
1) динамические лимиты getOrders в зависимости от количества активных счетов (условные 20-30 рпм на счет, чтобы был лаг 2-3 секунды в обновлении списка активных ордеров)
2) стрим изменений getOrders (предпочтительный вариант), тогда можно легко будет отказаться от unary запросов и рост счетов не будет влиять на скорость получения информации по статусу оредров. Так же упростится проблема, когда заявка снималась с биржи до получения ее роботом через getOrders при высоком размере лага.
3) При технической возможности стоит рассмотреть вариант, когда getOrders бы возвращал все активные orders по всем счетам, тогда не пришлось бы отправлять 10 getOrders на 10 счетов, а хватило бы одного

**Comment by AlexanderVolkovTCS** [comment]
Повышен до 200 рпм
