### ISSUE TITLE
Изменение значение поля figi в ответах по запросу GetOperations

### ISSUE THREAD

**Issue by SinnerUfa** [Tinkoff/investAPI#205]
Здравствуйте уважаемые разработчики,
в ходе проверок некоторых функций обработки данных по совершенным операциям (функция GetOperations) было обнаружено изменение значения поля figi в операциях по инструменту   с "Figi": "BBG000HJTMS9" на   "Figi": "BBGDEUTSCHET".
Пример ответа до изменения (Время запроса  "Date": "2022-06-19T09:29:45Z", id запроса "ID": "561ac8dc0081e69010e9de7f2083c2e8"):
`  {
   "Id": "226930776280",
   "Currency": "eur",
   "Payment": {
    "Currency": "eur",
    "Units": -34,
    "Nano": -500000000,
    "Value": -34.5
   },
   "Price": {
    "Currency": "eur",
    "Units": 17,
    "Nano": 250000000,
    "Value": 17.25
   },
   "State": "OPERATION_STATE_EXECUTED",
   "Quantity": 2,
   "Figi": "BBG000HJTMS9",
   "InstrumentType": "share",
   "Date": "2021-03-31T10:21:44.643Z",
   "Type": "Покупка ценных бумаг",
   "OperationType": "OPERATION_TYPE_BUY",
   "Trades": [
    {
     "TradeId": "3919110720",
     "DateTime": "2021-03-31T10:21:44.643Z",
     "Quantity": 1,
     "Price": {
      "Currency": "eur",
      "Units": 17,
      "Nano": 250000000,
      "Value": 17.25
     }
    },
    {
     "TradeId": "3919110710",
     "DateTime": "2021-03-31T10:21:44.643Z",
     "Quantity": 1,
     "Price": {
      "Currency": "eur",
      "Units": 17,
      "Nano": 250000000,
      "Value": 17.25
     }
    }
   ]
  },
`
Пример ответа после изменения ( Время запроса   "Date": "2022-06-20T03:56:18Z", id запроса "ID": "4ad736a21c9c757d30eaa2c965992343"):
 `{
   "Id": "226930776280",
   "Currency": "eur",
   "Payment": {
    "Currency": "eur",
    "Units": -34,
    "Nano": -500000000,
    "Value": -34.5
   },
   "Price": {
    "Currency": "eur",
    "Units": 17,
    "Nano": 250000000,
    "Value": 17.25
   },
   "State": "OPERATION_STATE_EXECUTED",
   "Quantity": 2,
   "Figi": "BBGDEUTSCHET",
   "InstrumentType": "share",
   "Date": "2021-03-31T10:21:44.643Z",
   "Type": "Покупка ценных бумаг",
   "OperationType": "OPERATION_TYPE_BUY",
   "Trades": [
    {
     "TradeId": "3919110720",
     "DateTime": "2021-03-31T10:21:44.643Z",
     "Quantity": 1,
     "Price": {
      "Currency": "eur",
      "Units": 17,
      "Nano": 250000000,
      "Value": 17.25
     }
    },
    {
     "TradeId": "3919110710",
     "DateTime": "2021-03-31T10:21:44.643Z",
     "Quantity": 1,
     "Price": {
      "Currency": "eur",
      "Units": 17,
      "Nano": 250000000,
      "Value": 17.25
     }
    }
   ]
  },` 

При этом в одном из ответов изменение поля было только по операциям покупка/продажа, и не затронула операции дивидендов. В других ответах, более поздних, все типы операций были с измененным полем.

В дополнение к этому, не могли бы Вы ответить на следующие вопросы:
1. Являются ли изменения поля figi валидными?
2. Возможные изменения поля figi инструмента влияют на историческую информацию по нему?;
3. Каким образом правильно определять по текущему значению поля figi его старое значение и собственно момент что оно изменилось? (Вероятно это как то связано с полем Uid или использованием запроса поиска инструмента)
4. Есть ли ограничения на количество или время хранения операций по конкретному счету? Если есть, то какие.
Заранее спасибо за ответ.

**Comment by hondasmx** [comment]
Добрый день!
Сделаем фикс в ближайшее время и проблема будет исправлена
