### ISSUE TITLE
Отсутствует FIGI в GetOperations для акций

### ISSUE THREAD

**Issue by allexme** [Tinkoff/investAPI#207]
Доброго дня!
При запросе списка операций для некоторых операций в ответе нет FIGI, привязать к конкретному инструменту такую операцию не возможно. 

Например акция MOMO, которая ранее была переименована (возможно менялся FIGI и(ли) ISIN):
OperaionId: 257921565200, 256633612860 и т.д.
AccountId: 2007321280
`{
	"id": "256633612860",
	"currency": "usd",
	"payment": {
		"currency": "usd",
		"units": "-139"
	},
	"price": {
		"currency": "usd",
		"units": "13",
		"nano": 900000000
	},
	"state": "OPERATION_STATE_EXECUTED",
	"quantity": "10",
	"date": "2021-06-04T11:37:01.365Z",
	"type": "Покупка ценных бумаг",
	"operationType": "OPERATION_TYPE_BUY",
	"trades": [
		{
			"tradeId": "4627996450",
			"dateTime": "2021-06-04T13:34:44.982Z",
			"quantity": "10",
			"price": {
				"currency": "usd",
				"units": "13",
				"nano": 900000000
			}
		}
	]
}`
PS: предполагаю, что на MOMO данная проблема не заканчивается.

В приложении данные операции отображаются корректно с привязкой к инструменту.
PS: В первой версии API данные операции просто отсутствуют в выдаче. 

Можно это как то исправить?

**Comment by WhiteRj** [comment]
Подтверждаю проблему
причём, ранее эти же самые сделки содержали фиги, но теперь это поле пустое

**Comment by hondasmx** [comment]
Добрый день!
Проблема исправлена

**Comment by allexme** [comment]
> Добрый день! Проблема исправлена

Проблема актуальна!
https://github.com/Tinkoff/investAPI/issues/125#issuecomment-1254729460

**Comment by allexme** [comment]
**Счет №2033885985**

**2500+** операций или **4,64%**! от общего кол-ва операций купли/продажи сейчас без привязки к инструменту в API! Ранее эта привязка у большинства операций была. 

Это провал...

@hondasmx 
@AlexanderVolkovTCS

**Comment by hondasmx** [comment]
@allexme Выкатил небольшое улучшение.
Проверьте, пожалуйста

**Comment by allexme** [comment]
@hondasmx стало значительно лучше! Проверяю дальше. 
Пока заменил, что у "исправленных" операций отсутствует поле **instrument_type**

**Comment by allexme** [comment]
@hondasmx почти у всех операций проблема с отсутствием FIGI была решена! Осталось вернуть instrument_type, но конкретно мне это не так важно.

**Осталось несколько операций, у которых проблема все ещё есть:**
**Счет №2001811104** 
**Операции:** 71112437320, 71207825310, 71287449950, 71287450050, 71287450140, 71287450300, 71287452050, 71287472140, 71383183490, 71388185460, 71394267270

Спасибо!

**Comment by Paulwoop** [comment]
Сегодня столкнулся с данной проблемой. Причем при покупке актива figi был, а при продаже он его не нашел и приложение у меня от этого упало в ошибку
