### ISSUE TITLE
Происходит подмена figi

### ISSUE THREAD

**Issue by Saellali** [Tinkoff/investAPI#208]
По запросу GetPositions:
`{'figi': 'BBG008F2T3T2', 'blocked': '0', 'balance': '10', 'exchangeBlocked': False}`
По запросу GetPortfolio:
`{'figi': 'TCS008F2T3T2', 'instrumentType': 'share', 'quantity': {'units': '10', 'nano': 0}, 'averagePositionPrice': {'currency': 'rub', 'units': '54', 'nano': 510000000}, 'expectedYield': {'units': '1', 'nano': 300000000}, 'currentNkd': {'currency': 'rub', 'units': '0', 'nano': 0}, 'currentPrice': {'currency': 'rub', 'units': '54', 'nano': 635000000}, 'averagePositionPriceFifo': {'currency': 'rub', 'units': '54', 'nano': 505000000}, 'quantityLots': {'units': '1', 'nano': 0}, 'blocked': False}
`
Это один и тот же инструмент но
BBG008F2T3T2 это RUAL
а
TCS008F2T3T2 это RUAL_old и он не торгуется

Также было бы здорово, если бы в GetPositions было добавлено число лотов и цена покупки

**Comment by AlexanderVolkovTCS** [comment]
>если бы в GetPositions было добавлено число лотов и цена покупки

Спасибо за репорт, стоимость покупки отображается в GetPortfolio, с RUAL_old - разберемся.

**Comment by irishrover** [comment]
Никаких прогнозов по фиксу нет?

**Comment by AlexanderVolkovTCS** [comment]
Исправлено
