### ISSUE TITLE
Токен

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/investAPI#21]
Где мне взять token для grpc? В профиле согласно faq  у меня только токены для OpenAPI можно выпустить, а они не подходят.  В Kreya на мои рабочие токены OpenAPI выдаётся "16 Unauthenticated".

**Comment by malyginvv** [comment]
Добрый день!
Токен необходимо передавать следующим образом: в Kreya добавить метаданные с наименованием "Authorization" и значением "Bearer token", где вместо token - ваш токен. Любой активный боевой токен должен работать. Токены от песочницы не работают в новой версии API.
Подробнее в инструкции https://tinkoff.github.io/investAPI/grpc/#kreya

**Comment by kitMP** [comment]
Добрый день.
Делаю как по этой инструкции, и не работает ни боевой токен, ни песочный.  В OpenAPI работают оба токена.

**Comment by AlexanderVolkovTCS** [comment]
При запросе каких методов отдается "16 Unauthenticated"?

**Comment by kitMP** [comment]
UserServices - GetAccounts, GetInfo.

**Comment by AlexanderVolkovTCS** [comment]
>Оказалось, что для других сервисов работает

Значит, вы пользуетесь старым sandbox токеном. 
Он не работает с "боевыми" сервисами, возвращающими реальные данные клиентов.

Попробуйте боевой токен.

**Comment by kitMP** [comment]
Боевой токен пробовал. Специально заново его сгенерировал. GetInfo возвращает "16 Unauthenticated". В свагере get_user_accounts возвращает с этим токеном счета.
