### ISSUE TITLE
При запросе списка облигаций поле с НКД (aci_value) у всех равно нулю.

### ISSUE THREAD

**Issue by vankovp** [Tinkoff/investAPI#210]

**Comment by Ventura27** [comment]
Добрый день.

Судя из названия топика обнаружил похожую проблему с https://tinkoff.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio . Не стал заводить отдельный Issue

Шаги:
1. Отправить запрос https://tinkoff.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio по любой облигации, где НКД !== 0

Ожидаемый результат:
- Поле в респонсе averagePositionPrice.value содержит прайс + НКД

Фактический результат:
- Поле в респонсе averagePositionPrice.value содержит только прайс без НКД. То есть averagePositionPrice.value === averagePositionPriceNoNkd.value

![image](https://user-images.githubusercontent.com/36276658/175529422-ddcc6a67-0be8-4859-824b-7eb4b823adec.png)

**Comment by OdCheban** [comment]
Возможно у с# библиотеки другая реализация, но там подобной проблемы нет

**Comment by AlexanderVolkovTCS** [comment]
Проблема с aci_value устранена,

по https://tinkoff.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio - рекомендуем пользоваться текущей версией, invest-openapi не поддерживается
