### ISSUE TITLE
Разница во времени UTC и New_York

### ISSUE THREAD

**Issue by vbeskrovny** [Tinkoff/investAPI#217]
Добрый день коллеги, поправьте меня, если не прав.

Запрашиваю 15 мин свечи по AAPL за день, и время первой свечи 11:30. Смотрю документацию - время указано в UTC. Конвертирую из UTC в EST (New York) - получаю 7:30, хотя фактическое открытие биржы и первой свечи должно быть в 9:30

Кто-нибудь может объяснить что я не так считаю?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, торговля иностранными бумагами идет через SPB биржу, у нее свое расписание - https://spbexchange.ru/ru/stocks/inostrannye/raspisanie/

**Comment by vbeskrovny** [comment]
Простите непонятно. Вы хотите сказать, что spb открывает торговлю бумагами NYSE в 11:30 UTC, т.е. в 7:30 утра по EST, т.е. на два часа раньше чем сама NYSE?
