### ISSUE TITLE
Ошибка выставления маркет заявки

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#220]
Error: 3 INVALID_ARGUMENT: 30049 
 tracking-id: c836e101b1fb8e89c29af7ab8c4e020b 
 message: "post order error: Tekushhaya czena dlya otkry`tiya korotkoj poziczii po TSLA ne mozhet by`t` nizhe 709.79 USD. Poprobujte vy`stavit` limitnuyu zayavku ne nizhe e`toj czeny`" 

Иногда проскакивают такого плана ошибки для маркет заявок.

**Comment by AlexanderVolkovTCS** [comment]
Распоряжение ЦБ 5636-У обязывает брокера проверять цены заявок на открытие коротких позиций и лимитирует максимальный гэп в 5%. В случае, если цена изменилась сильнее, открытие позиции рыночной заявкой не допускается и клиентам рекомендуем выставлять заявку лимиткой.
