### ISSUE TITLE
Недокументированы поля https://invest-public-api.tinkoff.ru/history-data

### ISSUE THREAD

**Issue by fingoldo** [Tinkoff/investAPI#222]
CSV файлы, возвращаемые в архиве с данной точки доступа, не имеют заголовков.
Понять, где какие поля, затруднительно, гадать не хочется:

BBG000B9XRY4;2020-06-08T07:04:00Z;82.9;82.87;83;82.87;20;

Прошу добавить заголовки в CSV или хотя бы их указать в документации на страничке https://tinkoff.github.io/investAPI/get_history/

**Comment by AlexanderVolkovTCS** [comment]
Дополнил доку порядком следования полей: https://tinkoff.github.io/investAPI/get_history/
