### ISSUE TITLE
FIVE-9.22 X5 RetailGroup BID > ASK

### ISSUE THREAD

**Issue by gbaccount2022** [Tinkoff/investAPI#223]
Периодически появляются проблемы в разных бумагах

Сейчас не наблюдается

**Comment by betslus1** [comment]
аукцион открытия?

**Comment by gbaccount2022** [comment]
> аукцион открытия / дискретный аукцион? там это нормально

я не знаю какой это аукцион, в течении дня таких событий куча, мониторинг через подписку на стакан subscribe_order_book_request

вот еще и таких много...
Wed Aug 17 2022 13:38:50 GMT+0300 (Moscow Standard Time) NOTK-9.22 Новатэк bid 112285, ask = 112223

**Comment by AlexanderVolkovTCS** [comment]
Оптимизировали доставку маркетдаты, должно помочь. 
Если проблема повторится - переоткройте тикет, пожалуйста.

Как правильно сказал [betslus1](https://github.com/betslus1) - для аукционов это нормальная ситуация.

**Comment by gbaccount2022** [comment]
![Снимок экрана 2022-08-31 в 18 44 42](https://user-images.githubusercontent.com/109000329/187721606-a080f8cd-e305-4434-a808-60340855bd4d.png)
проблема постоянная... как в API так и в терминале...
