### ISSUE TITLE
Поддержка и развитие invest-api-csharp-sdk

### ISSUE THREAD

**Issue by BlankaKorvo** [Tinkoff/investAPI#225]
Добрый день!
Вопрос:
    имеются ли какие то планы по развитию и расширению библиотеки [invest-api-csharp-sdk] или она так и останется на всегда 
    "заглушкой" для галки, что оно вроде бы есть?
Спасибо.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день! 
да, взяли в работу и скоро опубликуем с# примеры как асинхронных, так и на синхронных вызовы методов API.

Если есть конкретные пожелания по примерам кода, то укажите их, пожалуйста, в репозитарии  https://github.com/Tinkoff/invest-api-csharp-sdk/issues
