### ISSUE TITLE
Неверные данные по дневным свечам в API

### ISSUE THREAD

**Issue by Ruslan-Asadullin** [Tinkoff/investAPI#226]
По некоторым акциям Мосбиржи API отдает неверные данные на 19.07.22. Некорректные свечи имеют аномально низкий объем, который также не соответствует данным Мосбиржи. 
Например, GMKN: На 2022-07-19 OHLC - 15250.0, 15300.0, 15056.0, 15116.0. Данные Мосбиржи: 15250.0, 15300.0, 14800.0, 14914.0.
По фьючерсам аналогичная ситуация, только расхождение по трем датам, на 2022-07-19, 2022-07-21, 2022-07-25. Например, по MXU2, SiU2, RIU2.

**Comment by AlexanderVolkovTCS** [comment]
Проверил для GMKN, на 19.07.22 (таймстамп 1658214000) отдаем объем 78102, что соответствует бирже: https://www.moex.com/ru/issue.aspx?board=TQBR&code=GMKN

Если у вас отличается объем, проверьте, что используете CANDLE_INTERVAL_DAY в качестве периода запроса.

**Comment by Ruslan-Asadullin** [comment]
Все верно, сейчас данные корректные. На момент публикации issue данные отличались.
