### ISSUE TITLE
В исторических рыночных данных порядок следования полей в выходном файле указан не верно.

### ISSUE THREAD

**Issue by II245** [Tinkoff/investAPI#230]
Добрый день, выкачиваю исторические данные скриптом.

Вижу вот такую строку:
BBG00B8NN386;2022-08-03T07:00:00Z;0.1745;0.174;0.1745;0.174;14;

В соответствии с документацией https://tinkoff.github.io/investAPI/get_history/

Последние три колонки имеют следующее описание.
Минимальная цена за интервал (low)
Максимальная цена за интервал (high)
Объем в лотах (volume)

Получим что high < low

Подскажите, пожалуйста, как такое может быть?

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за репорт, документация обновлена
