### ISSUE TITLE
Кривые limitUp/limitDown

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#233]
<img src="https://habrastorage.org/webt/js/db/pk/jsdbpkgylfx7jhtgvnbkdmunmji.png" />
<img src="https://habrastorage.org/webt/ff/ck/g5/ffckg5xry0h2zfonioubkk4xkws.png" />

FIGI: BBG01016PHF2
method: orderbook stream
фиксируется ежедневно с 9:55 до 10:05

**Comment by AlexanderVolkovTCS** [comment]
- уменьшенный спреда между limitUp и limitDown на аукционе открытия - это норма, так их шлет биржа.
- задержку в доставке лимитов на аукционе открытия оптимизировали.
