### ISSUE TITLE
Ошибки при выставлении заявок перед открытием основной сессии

### ISSUE THREAD

**Issue by andrey-vrn** [Tinkoff/investAPI#234]
Наблюдаю ежедневно, что в период 09:50 - 10:10 возникают ошибки при выставлении некоторых лимитных заявок.
Мой робот выставляет заявку, если:
1) получен статус аукциона открытия по инструменту (стрим)
2) получен стакан по инструменту, и цена заявки для размещения соответствует limit_up / limit_down (стрим)

Сегодня выскакивали ошибки, но в 10:05:47 заявки все-таки выставились по тем ценам, по которым были попытки выставить их изначально.

К сожалению, только сегодня сделал вывод в лог информации о получении изменений в limit_up / limit_down, поэтому не смогу показать эти данные.

Вижу 2 вида ошибок:
1) ошибки статуса инструмента, когда в стриме изменение статуса уже было получено
2) ошибки с limit_up / limit_down.

[errors_20220811.xlsx](https://github.com/Tinkoff/investAPI/files/9308431/errors_20220811.xlsx)

**Comment by andrey-vrn** [comment]
Кстати, по стриму стаканов: при подписке на стакан приходит подтверждение о подписке, но не приходит текущее состояние стакана, поэтому роботу для работы с инструментом приходится ждать первого изменения стакана по инструменту, чтобы получить limit_up / limit_down. Было бы здорово, если бы сразу после подписки приходило бы текущее состояние стакана, как это сделано в стриме статусов.

**Comment by andrey-vrn** [comment]
[errors_20220812.xlsx](https://github.com/Tinkoff/investAPI/files/9315884/errors_20220812.xlsx)

**Comment by AlexanderVolkovTCS** [comment]
>Было бы здорово, если бы сразу после подписки приходило бы текущее состояние стакана

Архитектурно стрим стаканов рассылает только обновления данных. Для получения стакана в моменте лучше пользоваться unary запросом GetOrderbook()

>Сегодня выскакивали ошибки 

Взяли в работу, но кстати отвечу, что в случае шорта по рыночным поручениям есть аналогичная отбивка по цене, и это не ошибка: https://github.com/Tinkoff/investAPI/issues/220

**Comment by andrey-vrn** [comment]
Спасибо! С GetOrderbook() все получилось.

**Comment by andrey-vrn** [comment]
> Взяли в работу, но кстати отвечу, что в случае шорта по рыночным поручениям есть аналогичная отбивка по цене, и это не ошибка: https://github.com/Tinkoff/investAPI/issues/220

В моем случае это лимитные заявки.
Но даже если Ваша гипотеза верна, то все равно данные limit_up / limit_down, полученные в стриме или же методом GetOrderbook, должны быть согласованы с данными, по которым осуществляется проверка при размещении заявки.

**Comment by andrey-vrn** [comment]
[20220815.txt](https://github.com/Tinkoff/investAPI/files/9336996/20220815.txt)
Далее выкладывать каждый день не буду, но ошибки еще воспроизводятся. Пока обошел их путем периодических попыток выставления таких заявок.

**Comment by AlexanderVolkovTCS** [comment]
Должно быть исправлено, как и #233 
Если проблема будет повторяться - прошу переоткрыть тикет
