### ISSUE TITLE
Вопрос - можно ли по сделке понять, что это шорт?

### ISSUE THREAD

**Issue by horovody** [Tinkoff/investAPI#237]
Добрый день!

Подскажите пожалуйста, можно ли как-то по сделке понять что это шорт?

_Метод: GetOperations_

В данный момент такая сделка имеет тип просто продажа, и её никак не отличить.

Спасибо.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день!
В ответе метода нет информации о том, шорт ли это.
Рекомендуем смотреть на актуальные значения в getpositions()
