### ISSUE TITLE
Ошибка отмены ордера 

### ISSUE THREAD

**Issue by VadimSimonov** [Tinkoff/investAPI#239]
Ошибка плавающая, при этом ордер в статусе EXECUTION_REPORT_STATUS_NEW, возможно, ордер был исполнен пока шла отмена но нужно удостовериться.

`Caused by: ru.tinkoff.piapi.core.exception.ApiRuntimeException: 30059 Ошибка метода отмены заявки. Подробнее в тексте ошибки. tracking_id 62ff74dea49d7c44a4266aa490a6c043`

**Comment by AlexanderVolkovTCS** [comment]
Верно, ваша заявка была исполнена на момент отмены, ошибки не видим.

**Comment by VadimSimonov** [comment]
Спасибо!
