### ISSUE TITLE
Поле blocked структуры PortfolioPosition

### ISSUE THREAD

**Issue by inferrna** [Tinkoff/investAPI#242]
В первой версии API это поле возвращало количество заблокированных лотов позиции (например, выставленных на продажу акций). В новой версии тип этого поля **bool**, в чём его смысл теперь?

**Comment by AlexanderVolkovTCS** [comment]
Это поле было добавлено для идентификации заблокированных позиций на СПБ Бирже.

Для получения актуальных блокировок используйте https://tinkoff.github.io/investAPI/operations/#positionsresponse - он быстрее
