### ISSUE TITLE
Ошибки при выставлении заявок перед открытием основной сессии

### ISSUE THREAD

**Issue by andrey-vrn** [Tinkoff/investAPI#244]
Проблема с выставлением заявок перед открытием основной сессии никуда не делась.
Мне теперь понятна причина проблемы, надеюсь на ее устранение.
По ряду акций перед открытием основной сессии для снижения волатильности на открытии сужается допустимый диапазон limit_down, limit_up. Примерно в 10:05 это снижение снимается.

Проблема в том, что в стриме стаканов и в методе GetOrderBook() информация об этом занижении появляется только примерно в 09:55. При выставлении же заявок это занижение диапазона, похоже, учитывается уже с 09:50.

Таким образом, в период в 09:50 - 09:55 (до получения информации о занижении в стриме) робот пытается выставить заявки, не владея реальными значениями limit_down, limit_up, получая при этом ошибки 30049.

Ожидаемое поведение: информация о занижении диапазона limit_down и limit_up должна приходить синхронно с изменением этих значений в модуле контроля выставления заявок.

Пример лога с ошибками прилагаю.
[broker_errors_20220824.txt](https://github.com/Tinkoff/investAPI/files/9413738/broker_errors_20220824.txt)

**Comment by AlexanderVolkovTCS** [comment]
Как временное решение, увеличили периодичность опроса биржи. В низком приоритете завели задачу на точную синхронизацию. 

Но даже с учетом уменьшения спреда в лимитах на аукционе открытия, он все равно обычно больше 20%. 
Позвольте поинтересоваться, зачем выставлять заявки, настолько далекие от lastprice? Они же не исполнятся.

**Comment by andrey-vrn** [comment]
Спасибо! Сделал управление рисками, пока по некоторым инструментам заградительные параметры, корректирую их как раз.

**Comment by betslus1** [comment]
> Они же не исполнятся.

**Comment by AlexanderVolkovTCS** [comment]
>В низком приоритете завели задачу на точную синхронизацию.

реализовали.
