### ISSUE TITLE
Добавить в метод UsersService/GetMarginAttributes вывод скорректированной маржи.

### ISSUE THREAD

**Issue by btmc** [Tinkoff/investAPI#247]
Сейчас в выводе присутствуют только начальная маржа  (startingMargin) и минимальная маржа (minimalMargin), в то время как по факту сейчас для того, чтобы совершить сделку, должны быть выполнены требования по скорректированной марже, а не начальной, которые строже.

Просьба добавить скорректированную маржу в ответ метода.

**Comment by btmc** [comment]
Также добавлю, что amountOfMissingFunds и fundsSufficiencyLevel также считаются к начальной марже, а не к скорректированной, поэтому в действительности не работают (при отрицательном amountOfMissingFunds уже нельзя делать новые сделки).

**Comment by b1ng0o** [comment]
В скором времени добавим  скорректированную маржу в ответ метода.

**Comment by b1ng0o** [comment]
Параметр добавлен https://tinkoff.github.io/investAPI/users/#getmarginattributesresponse
