### ISSUE TITLE
GetPortfolio в PortfolioResponse.PortfolioPosition[].figi для валют заполняет не figi, а ticker

### ISSUE THREAD

**Issue by SEA99** [Tinkoff/investAPI#25]
сабж.

**Comment by SEA99** [comment]
В getOperations то же самое

**Comment by SEA99** [comment]
Либо в инструментах надо прописать figi как ticker, раз это всё равно не настоящий figi

**Comment by serejhaaa** [comment]
Будет исправлено в ближайших релизах

**Comment by serejhaaa** [comment]
Будет исправлено в ближайших релизах

**Comment by serejhaaa** [comment]
Будет исправлено в ближайших релизах

**Comment by serejhaaa** [comment]
Исправлено
