### ISSUE TITLE
Интервалы свечей 2, 3, 10, 30 минут

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#251]
В предыдущей версии API были интервалы свече 2, 3, 10, 30 минут.
Планируется ли добавление таких интервало в новый API?

**Comment by AlexanderVolkovTCS** [comment]
В GetCandles() указаны интервалы так, как они хранятся у нас https://tinkoff.github.io/investAPI/marketdata/#candleinterval

Любые производные значения интервалов  (2, 3, 10, 30 и тд) можно получить, "склеив" несколько запросов меньшего интервала.
