### ISSUE TITLE
[Bug] GetBondCoupons возвращает 504

### ISSUE THREAD

**Issue by Gor** [Tinkoff/investAPI#253]
Добрый день!

При вызове метода GetBondCoupons (REST) периодически падает ошибка:

Exception: Request failed for https://invest-public-api.tinkoff.ru returned code 504. Truncated server response: {"code":4,"message":null,"description":null}

Кроме того, периодически метод возвращает числа с "." в units

**Comment by OdCheban** [comment]
У меня тоже самое, раньше такого не было

**Comment by AlexanderVolkovTCS** [comment]
>периодически падает ошибка

По какой-то одной бумаге или по разным?

>Кроме того, периодически метод возвращает числа с "." в units

При использования сваггера воспроизводилась? Аналогично, по какой бумаге?

**Comment by Gor** [comment]
> По какой-то одной бумаге или по разным?
По разным

> При использования сваггера воспроизводилась? Аналогично, по какой бумаге?
Сваггер не пробовал, дергал методы напрямую.

Комбинации пробовал разные, от бумаг не зависит. Вчера обе проблемы перестали воспроизводиться

**Comment by AlexanderVolkovTCS** [comment]
>Вчера обе проблемы перестали воспроизводиться

Спасибо. Проблем больше не должно быть, если что - переоткройте тикет.

**Comment by OdCheban** [comment]
Возвращаем тикет?
