### ISSUE TITLE
Пустой figi в getOrders

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#254]
Периодически в getOrders не возвращается figi инструмента,  в результате чего останавливаются торги, так как ответ не проходит валидацию роботом.
<img src="https://habrastorage.org/webt/-w/iq/it/-wiqitoj-qb7vxhylmeusxvrgt8.png" />

[ordersSyncOff]: Ошибка заявок: 6
 {"type":"error","resp":"tinkoff_v2:getPrice:Инструмент не найден undefined","o":"{\"stages\":[],\"order_id\":\"32493368581\",\"execution_report_status\":\"EXECUTION_REPORT_STATUS_NEW\",\"lots_requested\":11,\"lots_executed\":0,\"initial_order_price\":\"11289.96 rub\",\"executed_order_price\":\"0 rub\",\"total_order_amount\":\"11289.96 rub\",\"average_position_price\":\"0 rub\",\"initial_commission\":\"2.21 rub\",\"executed_commission\":\"0 rub\",\"figi\":\"\",\"direction\":\"ORDER_DIRECTION_SELL\",\"initial_security_price\":\"100.02 rub\",\"service_commission\":\"0 rub\",\"currency\":\"RUB\",\"order_type\":\"ORDER_TYPE_LIMIT\",\"order_date\":\"2022-09-05T07:11:05.022Z\"}"}

**Comment by AlexanderVolkovTCS** [comment]
Исправлно
