### ISSUE TITLE
не могу получить информацию о дивидендах

### ISSUE THREAD

**Issue by vodolaz095** [Tinkoff/investAPI#255]
Я вызываю этот метод https://tinkoff.github.io/investAPI/instruments/#getdividends
таким кодом (с помощью библиотеки своей https://github.com/vodolaz095/go-investAPI)

```go

			res, errD := tg.Client.InstrumentsServiceClient.GetDividends(ctx, &investapi.GetDividendsRequest{
				Figi: s.Figi,
				From: timestamppb.New(from),
				To:   timestamppb.New(to),
			})
```
и в ответ получаю ошибку

`rpc error: code = ResourceExhausted desc =  `

Я прочитал коды ошибок https://tinkoff.github.io/investAPI/errors/
 но они не выглядят соответствующими случаю, так как я НЕ ОТКРЫВАЮ stream соединения, я просто хочу получить календарь дивидендов

прошу устранить ошибку, с уважением, Анатолий.

**Comment by AlexanderVolkovTCS** [comment]
ResourceExhausted возвращается в случае ошибок с превышением rate-limits

Недавно из-за ddos мы временно ограничили количество вызовов 10ю в минуту.
Как проведем работы по оптимизации, вернем лимиты обратно.

Пока рекомендуем анализировать код ответа либо количество доступных на эту минуту запросов в заголовке ответа сервера.

**Comment by vodolaz095** [comment]
понял, спасибо... подумаю,что с этим делать
