### ISSUE TITLE
Пропали идентификаторы у некоторых типов операций

### ISSUE THREAD

**Issue by Wolfer** [Tinkoff/investAPI#257]
Примерно 6-7 сентября в ответах на GetOperations как минимум в следующих типах операций поле id перестало заполняться, приходит пустое. parent_operation_id также пустое

OPERATION_TYPE_COUPON
OPERATION_TYPE_BOND_TAX
OPERATION_TYPE_OUTPUT
OPERATION_TYPE_DIVIDEND
OPERATION_TYPE_DIVIDEND_TAX
OPERATION_TYPE_INPUT
OPERATION_TYPE_TAX_CORRECTION
OPERATION_TYPE_BOND_REPAYMENT_FULL
OPERATION_TYPE_BOND_REPAYMENT
OPERATION_TYPE_TAX

пример, 

`{"id":"","parent_operation_id":"","currency":"rub","payment":{"currency":"rub","units":16,"nano":80000000},"price":{"currency":"","units":0,"nano":0},"state":"OPERATION_STATE_EXECUTED","quantity":0,"quantity_rest":0,"figi":"BBG00HKB9SR5","instrument_type":"bond","date":{"seconds":1661430486,"nanos":0},"type":"Выплата купонов","operation_type":"OPERATION_TYPE_COUPON"}`

Это ошибка или запланированное изменение?

**Comment by mild-delirium** [comment]
В список операций с пустым полем id можно ещё смело добавить OPERATION_TYPE_BROKER_FEE. Вообще по ощущениям теперь всё кроме BUY/SELL приходит без id.

Есть сильное подозрение, что следующее произошло в рамках этой же проблемы, поэтому добавлю сбда, что в некоторых типах операций теперь помимо пустого поля id приходит ещё и пустое поле figi, например в OPERATION_TYPE_DIVIDEND_TAX. Раньше оно было.

**Comment by SEA99** [comment]
У комиссии тоже пропали идентификаторы

**Comment by AlexanderVolkovTCS** [comment]
> пустое поле figi

эта проблема решилась для большинства инструментов.
