### ISSUE TITLE
Разъяснение по limits_loading_in_progress

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#258]
В документации [PositionsResponse](https://tinkoff.github.io/investAPI/operations/#positionsresponse) указано
> Признак идущей в данный момент выгрузки лимитов.

Но это мало о чем говорит. Можно более подбробно описать куда и какие лимиты выгружаются?

**Comment by AlexanderVolkovTCS** [comment]
Поле означает, что в моменте производится работа по изменению/переносу позиций, если limits_loading_in_progress = true, то количество позиций может быть неконсистентным.

При принятии торговых решений рекомендуем опираться на позиции с limits_loading_in_progress=false
