### ISSUE TITLE
GetClosePrices() возвращает некорректные данные.

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#260]
Для начала хотел поблагодарить за создание [GetClosePrices()](https://github.com/Tinkoff/investAPI/issues/153). Осталось одно небольшое пожелание - увеличить точность выходных данных.
Для примера: 
GetClosePrices() для BBG011FHF1F7 возвращает 89.436, фактическое закрытие 89.5,
для BBG000000001 получаем через GetClosePrices() 5,72 , фактическое же закрытие 5,73

**Comment by AlexanderVolkovTCS** [comment]
Кажется, данные совпадают с сайтом https://www.moex.com/ru/issue.aspx?board=TQTF&code=TRUR&utm_source=www.moex.com&utm_term=trur

BBG000000001, в апи 5,72
<html><body>


Цена последней сделки | 5,73
-- | --
Цена закрытия | 5,72


</body>
</html>

**Comment by nonamegithub** [comment]
Если с бумагами, которые стали торговаться в вечернюю сессию, все более или менее понятно, то касательно BBG000000001 могу сказать, что заметил расхождения сравнив "свой" портфель с портфелем из терминала Тинькофф. Видимо там ориентируются на те данные, что отображаются, в том числе, и в графике терминала. Впрочем ничего удивительного: у команды разработчиков терминала дела в плане достоверности отображаемых данных обстоят еще хуже чем у вас - мне больше неохота по терминалу тикеты открывать, а ошибок, кроме меня, похоже никто не замечает.
