### ISSUE TITLE
Необходима возможность запрашивать через GetCandles() определенное количество свечей 

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#262]
Идея, собственно говоря, [не нова](https://github.com/Tinkoff/invest-openapi/issues/427). Пользователи API вынуждены [костылить](https://github.com/vitalets/tinkoff-invest-api#%D0%BA%D0%B5%D1%88%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D0%B2%D0%B5%D1%87%D0%B5%D0%B9) код для получения данного функционала. Как я понимаю, особых проблем со стороны разработчиков возникнуть не должно, всего лишь одна-две дополнительных строки кода в SQL-запросе для получения столь очевидно необходимого функционала.

**Comment by AlexanderVolkovTCS** [comment]
Архитектура брокера на данный момент позволяет быстро получать свечи с минимальной задержкой только за указанные интервалы времени. Как посоветовали в треде https://github.com/Tinkoff/invest-openapi/issues/427, рекомендуем предварительно локально загрузить всю историю в БД и оттуда делать произвольные селекты.

Для более быстрой загрузки истории предусмотрен скрипт https://github.com/Tinkoff/investAPI/blob/main/src/marketdata/download_md.sh

**Comment by nonamegithub** [comment]
сомнительная отговорка

**Comment by olsh** [comment]
> рекомендуем предварительно локально загрузить всю историю в БД и оттуда делать произвольные селекты.

Что мешает сделать это на стороне API и предоставить конечным пользвателям удобный интерфейс? :)

**Comment by cpp4ever** [comment]
> Мой кейс - получить последние 50 минутных свечей чтобы построить нужные индикаторы.
> Качать для этого целый год истории скриптом и заливать в БД - сомнительное удовольствие.

По Вашему кейсу самое простое решение - получить сделки за последний час `GetLastTradesRequest` и свечи построить самостоятельно какие надо.

**Comment by nonamegithub** [comment]
Все верно подмечено про выходные и праздники, и отсутствие сделок за период. А по итогу вырисовывается такая странная логика разработчиков: для обеспечения клиентскому приложению возможности "получать свечи с минимальной задержкой"  брокер идет, в итоге, на кратное увеличение вычислительной нагрузки на свою инфраструктуру, плюс происходит кратный рост потраченного на выполнение запросов времени  со стороны клиента, для получения требуемого количества свечей.
