### ISSUE TITLE
Добавить свойство blocked_lots в PortfolioPosition

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#265]
В предыдущей версии API при получении портфеля было удобно сразу получать кол-во заблокированных лотов которые выставлены на продажу.
Респонсу PositionsSecurities в свою очередь не достает свойств `average_position_price`.

Поэтому чтобы получить эти данные, приходится делать 2 запроса в новом API, вместо 1 запроса в старом.

**Comment by olsh** [comment]
Вижу что в [PortfolioPosition](https://tinkoff.github.io/investAPI/operations/#portfolioposition) было добавлено свойство `blocked_lots`. Но в Release notes не нашел уведомления об этом. Можно ли уже использовать это свойство? Если да, то имеет смысл закрыть эту issue.

**Comment by AlexanderVolkovTCS** [comment]
Да, можно его использовать.
