### ISSUE TITLE
Методу `GetCandles` добавить поддержку параметра `uid`

### ISSUE THREAD

**Issue by AndreySheka** [Tinkoff/investAPI#266]
В [V1.0.12](https://github.com/Tinkoff/investAPI/releases/tag/v1.0.12) добавлен новый тип [идентификаторов инструмента ](https://tinkoff.github.io/investAPI/faq_identification/)- `instrument_uid` или просто `uid`. Однако, метод [GetCandles](https://tinkoff.github.io/investAPI/marketdata/#getcandlesrequest) поддерживает только `figi`. Без поддержки `uid` невозможно получить исторические данные методом  [GetCandles](https://tinkoff.github.io/investAPI/marketdata/#getcandlesrequest) для опционов.

**Comment by AlexanderVolkovTCS** [comment]
Да, добавим в ближайшем релизе
