### ISSUE TITLE
Курс валюты инструмента для метода GetPortfolio()

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#267]
Насколько трудно будет для разработчиков добавить для нерублевых инструментов в портфеле курс валюты в возвращаемом GetPortfolio() ответе? На данный момент, для вычисления рублевой стоимости таких позиций в момент формирования портфеля, приходиться дополнительно запрашивать котировки валют.

**Comment by AlexanderVolkovTCS** [comment]
Прокидывать курс валют пока архитектурно не планируется, однако есть возможность добавить параметр - валюта портфеля - и отдавать все цены в указанной валюте. Также, как и в мобильном приложении. Это решит проблему?

**Comment by nonamegithub** [comment]
Не совсем - обратным ходом придется стоимость инструмента в валюте высчитывать. Если только дополнительными полями отразить цены в валюте портфеля.

**Comment by AlexanderVolkovTCS** [comment]
Пока курс валют возвращать не планируется. Сделали возможность выбора валюты, в которой вернется стоимость портфеля.
