### ISSUE TITLE
Длительное время выставления лимитных заявок на покупку

### ISSUE THREAD

**Issue by TSemenchuk** [Tinkoff/investAPI#269]
Начальные условия:
1. Включена маржинальная торговля
2. Торги осуществляются бумагами московской биржы, валюта которых - российский рубль
3. На счету практически отсутствуют рублевые активы (их значение минимальное). Только позиция "доллар США"
4. Большинство заявок выставляется на открытии (в первые несколько минут). Для выставления заявок используется официальная версия API на Java версии 1.0.12
5. Пинг до сервера составляет не более 20 мс

Описание проблемы:
При параллельном выставлении нескольких лимитных заявок на покупку значительная часть из них выполняется слишком длительное время (от 0.5 секунд до 10 секунд).

Дата и время: 2022-09-19 10:16
Время, с: 0.235, 0.346, 0.470, 0.610, 6.318, 6.426, 6.615, 6.662, 6.788

Дата и время: 2022-09-15 10:05
Время, с: 0.245, 0.364, 0.464, 0.559, 0.675, 0.756, 0.874, 0.992, 1.129

Дата и время: 2022-09-14 10:00
Время, с: 0.377,  0.571, 0.935, 0.952, 1.011, 1.085, 1.215, 1.448, 3.001

Время указано в рамках выставления заявок по одному инструменту 
Обратите внимание на метрику 19 сентября - такое ощущение, что одна из заявок тормознула секунд на 6 и оставшиеся также выполнились с задержкой. Как будто при параллельном выставлении заявок все они где-то консолидируются и выставляются последовательно... Тоже самое заметно 14 сентября (но менее очевидно). Также по метрике от 15 сентября видно, что интервалы между выставлениям примерно одинаковые, что косвенно свидетельствует в пользу теории о последовательном исполнении заявок.

Для скальпинга с помощью торгового бота время реакции (т.е. выставления заявки) должно составлять не более половины секунды, в противном случае задержки могут повлиять на результат торговли (и вряд ли в лучшую сторону).
В моем случае почти все указанные в примере заявки были выставлены со значительным опозданием, а задержки более 6 секунд вообще являются катастрофическими.

Мне неизвестно, где возникают эти задержки - вполне возможно сами заявки выставляются на бирже быстро, но долго идет ответ от брокера (в силу каких-либо технических операций). Чтобы это проверить, нужны метрики на стороне брокера.
Например, можно реализовать простой код, который в случае длительных задержек (более секунды), логирует соответствующую информацию.

**Comment by TSemenchuk** [comment]
Сегодня снова были дикие задержки.
Прямо на открытии время выставления заявок было такое: 10.8, 10.5, 7.4, 5.7, 5.6, 0.4, 0.3.
Т.е. из 7 заявок только две выставились за более-менее адекватное время.
Не знаю на какой стороне проблема (у брокера или у биржи или где-то еще), но при таких задержках торговля через API становится невозможной.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, рекомендации по ускорению выставления поручений https://tinkoff.github.io/investAPI/speedup/
Основная рекомендация - отключить маржинальную торговлю, в этом случае скорость исполнения должна быть ~200-400мс в 99 персентиле.

>одна из заявок тормознула секунд на 6 и оставшиеся также выполнились с задержкой.

верно, при включенной маржиналке есть такая зависимость.

**Comment by TSemenchuk** [comment]
А давайте подробнее разберем эти "рекомендации"?

1. Предложение по отключению маржинальной торговли ведет к кратному уменьшению объемов возможных торгов в среднем в 2.5 раза -> уменьшается прибыль брокера за счет комиссий из-за падения объемов торгов
2. Предложение по открытию новых брокерских счетов также ведет к уменьшению объемов торгов: 
- это ведет к невозможности использования единого пула средств для торговли - фактически часть средств будет простаивать -> уменьшается прибыль брокера за счет комиссий из-за падения объемов торгов
- маржинальная торговля работает только в рамках одного брокерского счета, опять падают объемы торгов и, как следствие, прибыль брокера за счет комиссий
- "Задержки в скорости выставлении ордеров пропорциональны количеству сделок, проведенных на данном аккаунте в течение торгового дня" - здесь я вообще не могу подобрать слова, чтобы описать мои эмоции. Время выполнения операции по выставлению заявок не должно зависеть от исторических данных. К тому же у меня полно примеров, когда время выставления даже первых заявок сильно превышает все нормы (длится несколько секунд, вместо нормальных 300-400 миллисекунд)
3. Предложение параллельного выставления ордеров также бесполезно - у меня уже так работает и как показывает метрика, на стороне сервера эти параллельные ордера все равно выполняются последовательно. 

Я понимаю, что кто-то серьезно накосячил, разрабатывая серверную часть брокера. Лично мне все равно кто - текущий архитектор, предыдущий или потому что так сошлись звезды. Но давайте не будем отнекиваться и предлагать бесполезные варианты решения проблемы.
Ведь это API создается в надежде повысить прибыль брокера, а не для галочки? Так сделайте все, чтобы повысить объем торгов, а не ограничить их!

**Comment by TSemenchuk** [comment]
Забыл добавить важную деталь - когда у меня наблюдаются проблемы с задержками, тоже самое испытывают простые пользователи, работающие как с терминалом, так и через мобильное приложение. Откуда я это знаю? Я слежу за пульсом многих трейдеров, которые торгуют внутри дня (скальпинг) и у которых количество сделок в день может исчисляться сотнями, если не тысячами. И вот они тоже пишут о задержках в выставлении заявок и даже при ручном выставлении заявок для них 3-4 секундное выполнение операции это много

**Comment by nonamegithub** [comment]
Все вышеупомянутые проблемы подтверждаю.

> Для скальпинга с помощью торгового бота время реакции (т.е. выставления заявки) должно составлять не более половины секунды, в противном случае задержки могут повлиять на результат торговли (и вряд ли в лучшую сторону).

 Про скальпинг с этим API вообще можно забыть

**Comment by DeryabinSergey** [comment]
Внутри дня задержки бывают, но когда все хорошо - 0.6 квантиль ордеров выставляются до 60мс. А вот при открытии биржи, как видно на скрине 11 ордеров выставлялись 43 секунды, это конечно жестко
![](https://i.imgur.com/SiziGjL.png "")
