### ISSUE TITLE
Для отдельных бумаг GetAccruedInterests возвращает данные, не покрывающие весь период обращения облигации

### ISSUE THREAD

**Issue by nickmarlou** [Tinkoff/investAPI#27]
В попытках разработать инструмент, прогнозирующий входящий денежный поток от купонных выплат по облигациям, столкнулся с тем, что для некоторых бумаг метод `GetAccruedInterests` возвращает данные, которые **покрывают только часть периода обращения облигации**.

Например, есть облигация РЕСО-Лизинг БО-П выпуск 7. FIGI: `BBG00QN37PX1`. Тикер: `RU000A100XU4`. 

Дата погашения облигации: 11.10.2024. При этом метод `GetAccruedInterests` возвращает НКД только до 01.02.2022.

<img width="1269" alt="Screenshot 2022-01-18 at 19 27 45" src="https://user-images.githubusercontent.com/18831863/149977746-0c6a36a1-13ff-46a5-916f-de472c6238bc.png">

Такая же проблема есть ещё с рядом облигаций. Вот список FIGI:
- BBG00QPG1GD8
- RU000A101HU5
- BBG00R05JT04
- TCS00A1029T9
- TCS00A102GY7
- TCS00A101YV8
- BBG00GB81W02
- BBG00RRT3TX4
- BBG00QN37PX1

Это ожидаемое поведение или всё-таки баг? Для многих облигаций НКД нормально расписан вплоть до погашения.

**Comment by serejhaaa** [comment]
Данный метод возвращает не купонные выплаты, а накопленный купонный доход на определённую дату. Информация эта действительно бывает не доступна на весь период обращения, но всегда доступа на ближайшее время, чтобы рассчитать стоимость покупки/продажи. 
Для календаря выплаты купонов по облигации будет добавлен отдельный метод.
