### ISSUE TITLE
Пустое поле figi в операциях налога по купонам облигаций (OPERATION_TYPE_BOND_TAX)

### ISSUE THREAD

**Issue by HiHat** [Tinkoff/investAPI#270]
В операциях налога по купонам облигаций (OPERATION_TYPE_BOND_TAX) запрашиваемых методом GetOperationsByCursor приходит пустое поле figi:
`    {
      "cursor": "1648553655000000550",
      "brokerAccountId": "2000490181",
      "id": "",
      "parentOperationId": "",
      "name": "",
      "date": "2022-03-29T11:34:15Z",
      "type": "OPERATION_TYPE_BOND_TAX",
      "description": "Удержание налога по купонам",
      "state": "OPERATION_STATE_EXECUTED",
      "instrumentUid": "",
      "figi": "",
      "instrumentType": "",
      "instrumentKind": "INSTRUMENT_TYPE_UNSPECIFIED",
` 
Если запрашивать эти же операции через API v1, то figi присутствует!
Возможно, аналогично #257

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, проверьте пжлст, проблема уже должна была решиться. Если нет - переоткройте, пожалуйста, тикет.
