### ISSUE TITLE
orders.get_order_state возвращает ошибку при поиске по order_id

### ISSUE THREAD

**Issue by survexman** [Tinkoff/investAPI#271]
Создаю маркет-ордер с некоторым кустомным order_id. Ордер успешно создается и исполняется. Но после не могу найти состояние ордера (orders.get_order_state) по order_id.

Вот пример кода:

    import uuid
    from time import sleep
    
    from tinkoff.invest import Client, OrderType, PostOrderResponse, OrderDirection
    
    token = '<token>'
    account_id = '<account_id>'
    figi = 'BBG000BBR9P6'  # ticker = FLWS, 1-800-Flowers.com Inc
    order_id = str(uuid.uuid4().hex)
    
    with Client(token) as client:
        po_response: PostOrderResponse = client.orders.post_order(
            figi = figi,
            quantity = 1,
            direction = OrderDirection.ORDER_DIRECTION_BUY,
            order_type = OrderType.ORDER_TYPE_MARKET,
            order_id = order_id,
            account_id = account_id
        )
    
        # Giving some time to store data
        sleep(10)
    
        os_response = client.orders.get_order_state(
            account_id = account_id,
            order_id = order_id
        )
        # throws:
        # tinkoff.invest.exceptions.RequestError: (<StatusCode.NOT_FOUND: (5, 'not found')>,
        # Metadata(message='order not found'))

Это ошибка или я что-то делаю не так?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, в аргументе get_order_state необходимо указывать не ваш идентификатор заявки, а возвращаемый брокером в post_order
