### ISSUE TITLE
В постраничном запросе GetOperationsByCursor выпадают сделки

### ISSUE THREAD

**Issue by kuznetsov-v** [Tinkoff/investAPI#272]
Обнаружил что пропадают сделки на стыках двух запросов. Заметил когда проверял на своём портфеле с лимитом в 10 операций. Легко воспроизвести если сравнивать набор операций, полученных через единичный запрос с лимитом в 1000 с набором операций, полученных поштучно (т.е через запросы с лимитом 1 с указанием курсора)
У меня из ~90 операций выпало 10 операций комиссий и одна конвертация в турецкую лиру

при запросе с флагом without_commissions не воспроизвелось

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, прошу указать trackingID любого запроса на GetOperationsByCursor или номер счета + параметры запроса

**Comment by allexme** [comment]
Подтверждаю.
Воспроизвести баг можно так:
 
**Шаг 1: параметры запроса:**
```
 account_id: 2007321280
 from: 2019-12-19 21:00:00
 to: 2022-10-01 10:02:10
 state: OPERATION_STATE_EXECUTED
 cursor: 1643052359212278538
 limit: 1000
 without_overnights: true
```
Получаем в ответ список операций и следующий курсор:
>  next_cursor=1636034322949401876

, где последняя операция с параметрами:

>  cursor: 1636034378977006453
>  id: 325565191180
>  date: 2021-11-04 16:59:38
>  type: OPERATION_TYPE_SELL
 
 
**Шаг 2: запрашиваем новую партию операций с параметрами:**
```
 account_id: 2007321280
 from: 2019-12-19 21:00:00
 to: 2022-10-01 10:02:10
 state: OPERATION_STATE_EXECUTED
 cursor: 1636034322949401876
 limit: 1000
 without_overnights: true
```
Получаем в ответ список операций, где отсутствуют операции с нужным курсором, а первой идет:
>  cursor: 1636034150865723799
>  id: 325560230150
>  date: 2021-11-04 16:55:51
>  type: OPERATION_TYPE_BROKER_FEE
 
 
**Между шагами 1 и 2 пропущено 2 операции:**
```
 cursor: 1636034322949401876
 id: 325564027710
 date: 2021-11-04 16:58:43
 type: OPERATION_TYPE_BROKER_FEE
и
 cursor: 1636034322949401877
 id: 325564027710
 date: 2021-11-04 16:58:42
 type: OPERATION_TYPE_SELL
```
 
 
**Эти операции есть, есть вызвать getOperationsByCursor с такими параметрами:**
```
 account_id: 2007321280
 from: 2021-11-04 16:55:51
 to: 2021-11-04 16:59:38
 state: OPERATION_STATE_EXECUTED
 limit: 1000
 without_overnights: true
```

**Comment by WhiteRj** [comment]
Подтверждаю проблему

пытаюсь скачать историю сделок с курсором 1000,  и часть сделок в 21 году выпадает

но если запросить сделки исключительно за временной промежуток, когда эти сделки были (чтобы не ходить по курсорам), то апи отдаёт сделки

**Comment by AlexanderVolkovTCS** [comment]
Если еще будут замечания к истории операций - прошу переоткрыть тикет.
