### ISSUE TITLE
upstream request timeout

### ISSUE THREAD

**Issue by mild-delirium** [Tinkoff/investAPI#273]
Запросы:
- TradingSchedules
- GetBondCoupons
- GetAccruedInterests

(может ещё какие-то, у меня проблема только с этими)

Иногда начинают в 80-90% случаев отваливаться с ошибкой типа:

<StatusCode.UNAVAILABLE: (14, 'unavailable')>, 'upstream request timeout', Metadata(tracking_id=None, ratelimit_limit='200, 200;w=60', ratelimit_remaining=198, ratelimit_reset=16, message=None)

В остальных случаях отрабатывают за доли секунды (можно послать, например, 5 запросов подряд, из которых один, не обязательно первый, отработает за 0.1с, а остальные будут висеть по минуте пока не отвалятся с ошибкой выше).

Проблема случается в последнее время всё чаще и продолжается от нескольких часов до **нескольких дней**. То, что это происходит и по ночам и по выходным, наводит на мысли что с нагрузкой эти ошибки не связаны.

**Comment by AlexanderVolkovTCS** [comment]
Проблема достаточно давно не наблюдалась. Если актуально - прошу переоткрыть тикет.
