### ISSUE TITLE
Добавить в инструмент поле индустрии.

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/investAPI#274]
Как, например, сейчас есть в яхе:
![image](https://user-images.githubusercontent.com/62998882/191696144-dd81b292-1097-428f-b226-60436034bb40.png)

**Comment by rus-art** [comment]
Перевел в основной репозиторий, так как вопрос не по C# SDK

**Comment by AlexanderVolkovTCS** [comment]
В сервисе инструментов у бумаг есть поле sector. 
Для опционов оно тоже добавлено.

**Comment by kitMP** [comment]
У вас как вообще с чтением. Я и без вас знаю, что sector есть в свойствах инструмента. Здесь речь идёт о новом свойстве, и его до сих пор нет. Вы похоже, только и можете, что закрывать issue.
