### ISSUE TITLE
Не верный статус или неправильное описание в документации.

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/investAPI#276]
Ответ говорит, что NYSE сегодня не работает.
![image](https://user-images.githubusercontent.com/62998882/191960888-8d5e6cb2-26de-478d-8e9f-c749d061379c.png)
Но это не так:
https://www.nyse.com/markets/hours-calendars#nyse

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер, данный метод возвращает не статус работы реальной биржи, а порядок работы с инструментами этой биржи в брокере Тинькофф, чтобы отображать пользователям время до начала торгов.

Для NYSE все дни помечены как неторговые.
