### ISSUE TITLE
Строка запроса в FindInstrumentRequest.

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/investAPI#278]
Что нужно писать в поле Query для FindInstrumentRequest, если нужно по тикеру найти figi? Описание очень скудное в документации, без примера.

**Comment by hondasmx** [comment]
в это поле можно отправить
- ticker
- figi
- instrument uid
- name
Поиск идет по подстроке по этим полям во всех инструментах

**Comment by kitMP** [comment]
Не работает. Если ввожу тикер C (City Group), подвисает намертво:
![image](https://user-images.githubusercontent.com/62998882/193403500-e0e1747a-a077-4747-9835-9a686eed197e.png)
