### ISSUE TITLE
C++ код не компилируется из-за OperationItemTrades::trades_size поля

### ISSUE THREAD

**Issue by tomsan1987** [Tinkoff/investAPI#279]
[Недавно](https://github.com/Tinkoff/investAPI/commit/7bf27e86114d3e6197f1404205a32cc27f11aaab) в proto файлы добавили новый message:

```C
//Массив с информацией о сделках.
message OperationItemTrades {
  int32 trades_size = 1;
  repeated OperationItemTrade trades = 6;
}
```

C++ код сгенерированный из `operations.proto` - не компилируется:
```
operations.pb.h(8533,30): error C2535: 'int tinkoff::public_::invest::api::contract::v1::OperationItemTrades::trades_size(void) const': member function already defined or declared
```

Проблема в том, что для поля `trades`(как и для всех массивов) автоматически генерируется метод:
```C
int trades_size() const;
```

Который конфликтует с полем номер 1 из `OperationItemTrades` код для которого сгенерился следующим образом:
```C
int32_t trades_size() const;
```

т.е. отличается только тип возвращаемого значения.... 

Варианта решения вижу два:
1. Вообще удалить поле `int32 trades_size = 1`
2. Переименовать в `int32 trades_count = 1`

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за репорт, удалили поле trades_size https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/operations.proto
