### ISSUE TITLE
Пустой FIGI  у разных операций

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#280]
метод getoperationsbycursor возвращает часть операций с пустыми фиги

По наблюдениям, это чаще всего происходит с активами, у которых изменился тикер, произошёл делистинг или что-то такое. но бывает и рандомно

1 кейс - пустой фиги у налога на что-то
<img width="757" alt="image" src="https://user-images.githubusercontent.com/15725406/194003882-026f4c9c-f0bb-4ce1-a46e-496a21fbb87d.png">

2 кейс - пустой фиги у покупки
<img width="989" alt="image" src="https://user-images.githubusercontent.com/15725406/194003769-945cd33b-76f4-4c48-b5f8-69b21e22ae0b.png">

3 кейс - пустой фиги у купона
<img width="536" alt="image" src="https://user-images.githubusercontent.com/15725406/194003639-c4052370-4a8c-4bab-8af7-6ccd21a1f53c.png">

Проблемы начались примерно месяц назад и возникают постоянно на разных аккаунтах

**Comment by allexme** [comment]
Проблема была и год назад, но с новым API (как мне кажется) её масштабы только увеличиваются )
https://github.com/Tinkoff/investAPI/issues/125
https://github.com/Tinkoff/investAPI/issues/207

**Comment by AlexanderVolkovTCS** [comment]
К сожалению, для некоторых старых операций, совершенных по бумагам, прошедших через делистинг или корп действия, инструмент может отсутствовать.

**Comment by AlexanderVolkovTCS** [comment]
Проблема исправлена. Но надо иметь ввиду, что FIGI будет пустым у опционов. У них только uid.
