### ISSUE TITLE
Лимитная политика

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#282]
В методе GetUserTariff я получаю такие данные
```
Limit,Streams
6,"[ ""tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream"" ]"
2,"[ ""tinkoff.public.invest.api.contract.v1.OrdersStreamService/TradesStream"" ]"
2,"[ ""tinkoff.public.invest.api.contract.v1.OperationsStreamService/PortfolioStream"" ]"
2,"[ ""tinkoff.public.invest.api.contract.v1.OperationsStreamService/PositionsStream"" ]"
```

В таблице лимитной политики https://tinkoff.github.io/investAPI/limits/ , я не вижу при каком грейде я могу получить такие лимиты. Это баг или документация не обновлена?
По факту, я могу создать 6 стрим соединений MarketDataStream, 7 уже не дает.

**Comment by nonamegithub** [comment]
да, 6 тащит. похоже разработчикам сюрприз уже сделать не получится

**Comment by olsh** [comment]
По `tinkoff.public.invest.api.contract.v1.MarketDataService` тоже несовпадение с документацией, в документации 300, в GetUserTariff 200.

Еще было бы неплохо указать максимальное кол-во инструментов которое можно передавать на подписку в Stream. 
В документации сказано слещующее:

> Лимитов на количество подписок в рамках одного стрима на торговые статусы инструментов (подписка Info) нет.

По поводу лимитов не проверял, но по всей видимости запрос на эту подписку суммируется с лимитами `MarketDataService`.

То есть, предположим что лимит 300 как сказано в документации. Делаем 100 unary запросов на допустим [GetCandles](https://tinkoff.github.io/investAPI/marketdata/#getcandles), и после этого выполняем 1 запрос на подписку [MarketDataStream](https://tinkoff.github.io/investAPI/marketdata/#marketdatastream) в котором передаем [SubscribeInfoRequest](https://tinkoff.github.io/investAPI/marketdata/#subscribeinforequest) с 250 инструментами. В ответ получим RESOURCE_EXHAUSTED.

**Comment by olsh** [comment]
Еще возникло предоложение что лимиты на стримы шарятся между sandbox и production. Только что локально в sandbox тестировал максимальное кол-во стримов и одновременно с этим production упал с RESOURCE_EXHAUSTED.

**Comment by olsh** [comment]
Еще было бы неплохо указать в документации как быстро сбрасывается счетчик стримов после разъединения. Допустим я создал 1 стрим, счетчик на сервере стал 1, потом я отключился. Вот вопрос, через какое время на сервере счетчик станет 0?

**Comment by b1ng0o** [comment]
> Еще было бы неплохо указать в документации как быстро сбрасывается счетчик стримов после разъединения. Допустим я создал 1 стрим, счетчик на сервере стал 1, потом я отключился. Вот вопрос, через какое время на сервере счетчик станет 0?

https://tinkoff.github.io/investAPI/sla/

Дописали и обновили:
https://tinkoff.github.io/investAPI/limits/
