### ISSUE TITLE
Задокументировать поведение instrument_id совместно с figi

### ISSUE THREAD

**Issue by vitalets** [Tinkoff/investAPI#286]
В релизе [V1.0.14](https://github.com/Tinkoff/investAPI/releases/tag/v1.0.14) добавили в методы marketdata поле instrument_id, в котором можно указывать как figi, так и uid. При этом осталось старое поле figi. Хотелось бы в документации более подробного описания, как эти поля взаимодействуют вместе и какой способ идентификации инструмента предпочтительнее на будущее? Не планируется ли задепрекейтить figi?

Эксперимент c getCandles показал, что при взаимном указании обоих полей приоритет у figi. Возможно тут лучше кидать ошибку, т.к. в ответе figi не присутствует и можно начать оперировать не теми данными.

PS: Возможно более хорошим решением было не добавлять новое поле instrument_id во всем методы, а разрешить указывать uid в существующем поле figi. Меньше полей, проще код. Также например при генерации в typescript оба поля [обязательные](https://github.com/Tinkoff/investAPI/issues/243), и приходится их задавать хотя их одновременное указание не имеет смысла.

**Comment by b1ng0o** [comment]
Описали поведение в https://tinkoff.github.io/investAPI/faq_identification/
