### ISSUE TITLE
Задублированные операции покупки

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#287]
метод getoperationsbycursor возвращает 2 идентичные операции с одним и тем же курсором и ид

<img width="736" alt="Screenshot 2022-10-12 at 14 45 25" src="https://user-images.githubusercontent.com/15725406/195334471-c1339a86-0d7f-43a2-9a3c-f702ceb0a88c.png">

т.е. одна сделка возвращается на одной странице курсора, другая на другой (точнее она же)

**Comment by b1ng0o** [comment]
Добрый день, пришлите пожалуйста tracing id запроса или номер счета на котором воспроизводится данная ситуация

**Comment by WhiteRj** [comment]
> Добрый день, пришлите пожалуйста tracing id запроса или номер счета на котором воспроизводится данная ситуация

2000073441 - номер счёта

повторяется если вытягивать все данные с лимитом 1000 (т.е. ставить даты с 2018 (условно) до сегодня)

**Comment by b1ng0o** [comment]
Добрый день!
Проверьте пожалуйста,  на данный момент проблема устранена?

**Comment by AlexanderVolkovTCS** [comment]
Кажется, проблемы больше не наблюдается.
Если еще будут замечания к истории операций - прошу переоткрыть тикет.
