### ISSUE TITLE
SubscribeCandlesResponse SUBSCRIPTION_STATUS_INSTRUMENT_NOT_FOUND

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#288]
Сегодня в 9:50 по МСК для большинства инструментов при подписке на свечи в [SubscribeCandlesResponse](https://tinkoff.github.io/investAPI/marketdata/#subscribecandlesresponse) возвращался ответ с со статусом SUBSCRIPTION_STATUS_INSTRUMENT_NOT_FOUND.
Вопроизводилось для AAPL например.
Tracking ID к сожалению не залогировал.

**Comment by olsh** [comment]
Сегдня проблема повторилась, залогировал FIGI и tracking IDs

```
"BBG000BJDB15", "6347b425c14e5a847e2f9fee2e2e092c"
"BBG000QXWHD1", "6347b1587106c0a269fdc404586dd34b"
"BBG000R7Z112", "6347b1643ce1ae400480a6ae390f7729"
"BBG001Y2XS07", "6347b181548a32505f7d10631ef33f2b"
"BBG004S683W7", "6347b163c0bf0030285a72de08f34ce7"
"BBG004S686N0", "6347b193c9c40de9079022b1f3f4e54a"
"BBG006G2JVL2", "6347b181548a32505f7d10631ef33f2b"
"BBG006Q0HY77", "6347b20c16b52da67f5b51827f91ae12"
"BBG00B3T3HD3", "6347b1a5e06f7b8971de0a3bc7af101d"
"BBG00K7T3037", "6347b1586280e91d1ac7377dfbe67b9b"

```

**Comment by AlexanderVolkovTCS** [comment]
Проблема уже должна была быть решена, если актуально - прошу переоткрыть тикет
