### ISSUE TITLE
REST API прокси по сваггеру openapi.yaml возвращает ошибку 404

### ISSUE THREAD

**Issue by brandFromNSK** [Tinkoff/investAPI#305]
Здравствуйте!
<img width="682" alt="Снимок экрана 2022-11-12 в 13 39 48" src="https://user-images.githubusercontent.com/12840642/201461343-d51c36a4-2546-4463-9740-69035c478fff.png">
В качестве примера приведен GetAccounts. Аналогично по прочим запросам.
yaml взят с [офф страницы документации](https://github.com/Tinkoff/investAPI/issues/305#issue-1446294617)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, для проверки воспользуйтесь
https://tinkoff.github.io/investAPI/swagger-ui/#/UsersService/UsersService_GetAccounts

Сам файл - 
https://github.com/Tinkoff/investAPI/blob/main/src/docs/swagger-ui/openapi.yaml
