### ISSUE TITLE
Ошибка в поле nominal

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#306]
Отличается номинал между сайтом ТИ и API
https://www.tinkoff.ru/invest/bonds/RU000A1020S0/
https://www.moex.com/ru/issue.aspx?board=TQOD&code=RU000A1020S0

{
        "figi": "BBG00WMMJMN2",
        "ticker": "RU000A1020S0",
        "classCode": "TQCB",
        "isin": "RU000A1020S0",
        "lot": 1,
        "currency": "rub",
        "shortEnabledFlag": false,
        "name": "Первое коллекторское бюро выпуск 2",
        "exchange": "MOEX",
        "couponQuantityPerYear": 4,
        "maturityDate": "2023-08-10T00:00:00Z",
        "nominal": {
          "currency": "rub",
          "units": "666",
          "nano": 800000000
        },

Еще и число какое-то сильно уж странное. 
"666"

**Comment by betslus1** [comment]
Другая бумага RU000A101CB6

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за репорт, была проблема, исправлено.
