### ISSUE TITLE
Получать комиссии согласно тарифам

### ISSUE THREAD

**Issue by Den4ik94** [Tinkoff/investAPI#307]
Было бы супер получить возможность смотреть текущие комиссии согласно тарифам. Т.е. уже в роботе получать и учитывать комиссии, а не вручную обновлять и следить за обновлением тарифных планов.

Мб ЦБ введет заградительные комисии, или Брокер как недавно увеличит комиссии - отслеживать это порой не получается.

Заранее спасибо!

**Comment by olsh** [comment]
https://github.com/Tinkoff/investAPI/issues/298

**Comment by AlexanderVolkovTCS** [comment]
Отдельный метод для получения всех тарифных комиссий делать пока не планируется. 
В рамках #298 попробуем реализовать метод получения полной стоимости заявки, вкл комиссию.
