### ISSUE TITLE
В GetPortoflio поле averagePositionPriceFifo почему-то указано в рублях для Bank Of America и нескольких других заблокированных американских акций

### ISSUE THREAD

**Issue by irishrover** [Tinkoff/investAPI#312]
{
    "figi": "BBG000BCTLF6",
      "instrumentType": "share",
      "quantity": {
        "units": "1",
        "nano": 0
      },
      "averagePositionPrice": {
        "currency": "usd",
        "units": "0",
        "nano": 0
      },
      "expectedYield": {
        "units": "0",
        "nano": 0
      },
      "averagePositionPricePt": {
        "units": "0",
        "nano": 0
      },
      "currentPrice": {
        "currency": "usd",
        "units": "37",
        "nano": 720000000
      },
      "averagePositionPriceFifo": {
        "currency": "rub",
        "units": "0",
        "nano": 0
      },
      "quantityLots": {
        "units": "1",
        "nano": 0
      },
      "blocked": true,
      "positionUid": "266397a4-3901-4a21-9f4f-23cfcd1cedb6",
      "instrumentUid": "8b9f2548-d46a-47ed-9f24-c52502ac26fc",
      "varMargin": {
        "currency": "rub",
        "units": "0",
        "nano": 0
      },
      "expectedYieldFifo": {
        "units": "0",
        "nano": 0
      }
    },

**Comment by irishrover** [comment]
"Wells Fargo & Company", "Realty Income REIT" - аналогично

**Comment by b1ng0o** [comment]
Добрый день, на данный момент для заблокированных бумаг в averagePositionPriceFifo по умолчанию возвращается рубль, исправим в ближайшем релизе
