### ISSUE TITLE
Два разных FIGI для NuBank черезGetPositions и через GetPortfolio

### ISSUE THREAD

**Issue by irishrover** [Tinkoff/investAPI#319]
GetPositions: BBG0136WM1M4 (x-tracking-id: 638f94ead6e98ab088d9ca4d2f0a4cf4)
GetPortfolio: KYG6683N1034 (x-tracking-id: 638f93c4173680e282240272d90efc5c)

**Comment by irishrover** [comment]
Это планируется исправлять?

**Comment by b1ng0o** [comment]
Добрый день, проблему исправили. 

Если ситуация повторится, переоткройте пожалуйста issue или создайте новый
