### ISSUE TITLE
GetPositions и GetPortfolio возвращают некорректные данные

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#320]
Со вчерашнего дня, GetPositions и GetPortfolio стали возвращать некорректные данные. Возьмем за пример `US0079031078`.
![image](https://user-images.githubusercontent.com/3613592/206100116-a2c4c6a2-623e-4be9-aee9-4ff16afddd41.png)

С этим две проблемы:
1. GetPositions показывает ExchangeBlocked == true и это действительно так. Но GetPortfolio показывает что не заблокировано.
2. Помимо этой заблокированной позиции, у меня в портфеле есть и незаблокированная, и не один из методов ее не возвращает. Вторая проблема вероятно связана с #319, т.к. у незаблокированной позиции figi `BBG000BBQCY0`.

**Comment by allexme** [comment]
@olsh 
На сколько понял я, то для заблокированных акций со вчерашнего дня вместо **figi** отдается **isin**.
Каждый день новые приключения...

**Comment by olsh** [comment]
@allexme 
Да, похоже на то. Еще заметил что `InstrumentUid` для заблокированных и незаблокированных позиций одного и того же инструмента отличается.
![image](https://user-images.githubusercontent.com/3613592/206103480-800af58d-5d14-4af2-81e3-706a78017d81.png)

**Comment by irishrover** [comment]
Уважаемые разработчики, это будет исправлено?

**Comment by b1ng0o** [comment]
Добрый день, проблему исправили. 

Если ситуация повторится, переоткройте пожалуйста issue или создайте новый

**Comment by olsh** [comment]
@b1ng0o переоткрывать issue нет прав по всей видимости

> GetPositions показывает ExchangeBlocked == true и это действительно так. Но GetPortfolio показывает что не заблокировано.

Это исправлено

> Помимо этой заблокированной позиции, у меня в портфеле есть и незаблокированная, и не один из методов ее не возвращает. Вторая проблема вероятно связана с https://github.com/Tinkoff/investAPI/issues/319, т.к. у незаблокированной позиции figi BBG000BBQCY0.

Это не исправлено

**Comment by b1ng0o** [comment]
@olsh Напишите пожалуйста номер счет, я проверю

**Comment by olsh** [comment]
@b1ng0o если речь про account_id, то `2020307423`

**Comment by b1ng0o** [comment]
@olsh 

> Помимо этой заблокированной позиции, у меня в портфеле есть и незаблокированная, и не один из методов ее не возвращает. Вторая проблема вероятно связана с https://github.com/Tinkoff/investAPI/issues/319, т.к. у незаблокированной позиции figi BBG000BBQCY0.

В данный момент вижу что у вас в портфеле 2 позиции, заблокированная и не заблокированная. 
Сейчас Ваш портфель должен соотвествовать скриншоту выше. Не заблокированная позиция отображает инструмент с figi BBG000BBQCY0, заблокированная позиция отображается с figi US0079031078. 




>Еще заметил что InstrumentUid для заблокированных и незаблокированных позиций одного и того же инструмента отличается.

InstrumentUid  у разных инструментов разный, даже если они одной позиции принадлежат. Соотвественно и у разных позиций он тоже разный.

Если я Вас не верно понял, поясните пожалуйста что вы ожидаете увидеть в корректном варианте

**Comment by olsh** [comment]
Да, все так как вы написали, только до недавнего времени эти две позиции были одним инструментом (один FIGI). И со стороны пользователя, это тоже один инструмент.
Если это by design, то вопросов нет.

**Comment by b1ng0o** [comment]
Да, второй инструмент с figi US0079031078 является внеберживым, предназначен для торговли заблокированными бумагами.
