### ISSUE TITLE
Неточность в PortfolioResponse в описании total_amount_options

### ISSUE THREAD

**Issue by ErnestMatskevich** [Tinkoff/investAPI#321]
![photo_2022-12-07_17-32-26](https://user-images.githubusercontent.com/58702017/206206127-57ecf4bd-3f27-490f-9328-7d82b75b7f1a.jpg)

Вместо "фьючерсов" должно быть "опицонов", ориентируясь на названия поля options и на уже сущетсвующий метод total_amount_**futures**

**Comment by b1ng0o** [comment]
Добрый день, спасибо, обновим в документе в ближайшем релизе.
