### ISSUE TITLE
Комиссия в OrderState не совпадает с комиссией в мобильном приложении 

### ISSUE THREAD

**Issue by evsamsonov** [Tinkoff/investAPI#322]
При запросе OrderState через метод GetOrderStateRequest по исполненной заявке 1953465067409448010 приходит некорректная комиссия.

В initial_commission значение 168.99, в executed_commission и service_commission пусто. В мобильном приложении комиссия 179.73 

Ответ
```
order_id:"1953465067409448010" execution_report_status:EXECUTION_REPORT_STATUS_FILL lots_requested:30 lots_executed:30 initial_order_price:{currency:"rub" units:422463 nano:600000000} executed_order_price:{currency:"rub" units:421232} total_order_amount:{currency:"rub" units:421232} average_position_price:{currency:"rub" units:14041 nano:66666666} initial_commission:{currency:"rub" units:168 nano:990000000} executed_commission:{currency:"rub"} figi:"FUTSBRF12220" direction:ORDER_DIRECTION_BUY initial_security_price:{currency:"rub" units:14082 nano:120000000} stages:{price:{currency:"rub" units:14041} quantity:5 trade_id:"1953465067408276618"} stages:{price:{currency:"rub" units:14041} quantity:1 trade_id:"1953465067408276619"} stages:{price:{currency:"rub" units:14041} quantity:1 trade_id:"1953465067408276620"} stages:{price:{currency:"rub" units:14041} quantity:3 trade_id:"1953465067408276621"} stages:{price:{currency:"rub" units:14041} quantity:8 trade_id:"1953465067408276622"} stages:{price:{currency:"rub" units:14041} quantity:1 trade_id:"1953465067408276623"} stages:{price:{currency:"rub" units:14041} quantity:10 trade_id:"1953465067408276624"} stages:{price:{currency:"rub" units:14043} quantity:1 trade_id:"1953465067408276625"} service_commission:{currency:"rub"} currency:"rub" order_type:ORDER_TYPE_MARKET order_date:{seconds:1670416614 nanos:900791000} 19:"1f9b2028-6fd8-4cdf-8094-2d95895dbf5f"
````

**Comment by b1ng0o** [comment]
Добрый день!
initial_commission  - Начальная комиссия. Комиссия, рассчитанная на момент подачи заявки.
executed_commission - Фактическая комиссия, по итогам исполнения заявки.

Два этих параметра не обязательно должны быть равны. 

Так как вы исполняете рыночную заявку, то комиссия рассчитывается не сразу, а по факту исполнения сделки, поэтому она приходит с опозданием (как в МП так и в API). в ответе метода PostOrder вам возвращается только начальная комиссия. Если вы вызовете метод GetOrderState после того как будет рассчитана комиссия, то  в executed_commission вернется значение фактической комиссии, такой же как в МП

**Comment by evsamsonov** [comment]
@b1ng0o Спасибо! 
Примерно через какой промежуток времени после исполнения заявки нужно запросить OrderState чтобы получить фактическую комиссию (executed_commission)?

**Comment by b1ng0o** [comment]
К сожалению публичных sla нет, как правило это происходит через небольшой промежуток времени после исполнения заявки

**Comment by evsamsonov** [comment]
Понял. Спасибо
