### ISSUE TITLE
Не корректное значение qty в OrderTrade

### ISSUE THREAD

**Issue by an-52** [Tinkoff/investAPI#323]
В потоковом сервисе OrdersStreamService, в сообщениях OrderTrade - приходит не число лотов в сделке, а число акций, хотя по документации должно приходить число лотов:
Выставленный ордер:
figi:"BBG004730RP0"  quantity:**2**  price:{units:163  nano:550000000}  direction:ORDER_DIRECTION_BUY  account_id:"2025223930"  order_type:ORDER_TYPE_LIMIT  order_id:"fcd08f46-50a6-4067-ad08-bf8dbd7b087d"

Полученный ответ от выставления ордера:
order_id:"**33761841186**"  execution_report_status:EXECUTION_REPORT_STATUS_NEW  lots_requested:**2**  initial_order_price:{currency:"rub"  units:3271}  executed_order_price:{currency:"rub"}  total_order_amount:{currency:"rub"}  initial_commission:{currency:"rub"  units:1  nano:640000000}  executed_commission:{currency:"rub"}  aci_value:{currency:"rub"}  figi:"BBG004730RP0"  direction:ORDER_DIRECTION_BUY  initial_security_price:{currency:"rub"  units:163  nano:550000000}  order_type:ORDER_TYPE_LIMIT  17:"962e2a95-02a9-4171-abd7-aa198dbe643a"

Полученное сообщение в сервисе OrdersStreamService:
order_id:"**33761841186**"  created_at:{seconds:1670419329  nanos:145100537}  direction:ORDER_DIRECTION_BUY  figi:"BBG004730RP0"  trades:{date_time:{seconds:1670419328  nanos:245124000}  price:{units:163  nano:550000000}  quantity:**20**}  account_id:"2025223930"  7:"962e2a95-02a9-4171-abd7-aa198dbe643a"

**Comment by an-52** [comment]
Тикет закрыть? Или пусть весит, чтобы повторных не заводили?

**Comment by b1ng0o** [comment]
Мы закроем тикер после того как обновим документацию
