### ISSUE TITLE
Перестал отвечать стрим биржевых данных

### ISSUE THREAD

**Issue by cpp4ever** [Tinkoff/investAPI#325]
Сегодня 09.12.2022 примерно в 11:35 перестали поступать биржевые данные. При попытках переподписаться получаю ошибку:
```
status=INTERNAL(13)
message=70002
metadata=["date"]->"Fri, 09 Dec 2022 08:52:04 GMT";["message"]->"internal network error";["server"]->"envoy";["x-envoy-upstream-service-time"]->"10003";["x-ratelimit-limit"]->"300, 300;w=60";["x-ratelimit-remaining"]->"294";["x-ratelimit-reset"]->"5";["x-tracking-id"]->"6392ca5ffabed27a451c761246141982"
```

**Comment by cpp4ever** [comment]
Гм... Похоже, это просто пятница. На самом деле, вообще ничего не отвечает.
Хорошей вам пятницы, сотрудники Тинькофф Инвестиции ;)!

**Comment by cpp4ever** [comment]
Зашел на tinkoff.ru - понял, что не только у инвестиций проблемы :(

**Comment by AlexanderVolkovTCS** [comment]
Инцидент исправлен.
