### ISSUE TITLE
Получение исторических рыночных данных  (getHistory)

### ISSUE THREAD

**Issue by OdCheban** [Tinkoff/investAPI#328]
https://tinkoff.github.io/investAPI/get_history/ ввел токен, создал файл для figi
Запустил и получил ошибку "unspecified error with code: 000"

**Comment by AlexanderVolkovTCS** [comment]
Вы пользовались скриптом https://github.com/Tinkoff/investAPI/blob/main/src/marketdata/download_md.sh ?

**Comment by OdCheban** [comment]
> Вы пользовались скриптом https://github.com/Tinkoff/investAPI/blob/main/src/marketdata/download_md.sh ?
да, переписал на другой язык - для меня задача решена
но .sh на тот момент работал не корректно
