### ISSUE TITLE
В операциях погашения облигаций в методе GetOperationsByCursor количество погашаемых бондов указывается как 0

### ISSUE THREAD

**Issue by Ipsilon91** [Tinkoff/investAPI#329]
При погашении облигаций в списке операций метода GetOperationsByCursor в полях количества указывается 0 (см. скриншот, там ответ от официального sdk python). Не могли бы вы, пожалуйста, добавить количество погашаемых бондов?
Без этого не очень удобно считать стоимость портфеля на прошлые даты (что нужно, чтобы посчитать прибыль), потому что нельзя просто как при продаже бумаг вычесть их количество, а нужно сначала определить перед каждой операцией погашения сколько таких бумаг уже есть и только потом обнулить их число.

![photo_2022-12-14_18-04-13 (2)](https://user-images.githubusercontent.com/20323211/207840681-2c9e5649-46d1-4a20-841b-a17c37436af7.jpg)

**Comment by b1ng0o** [comment]
Добрый день, к сожалению такой возможности нет, так как погашение бондов  это денежная операция, а не операция продажи.
