### ISSUE TITLE
Tinkoff Invest API REST - запрос из браузерного клиента (fetch) приводит к ошибке CORS

### ISSUE THREAD

**Issue by AGExpert** [Tinkoff/investAPI#33]
При попытке выполнить запрос из браузерного клиента возникает ошибка 'CORS error'.
Похоже, из-за того, что ответ сервера не содержит в заголовках 
Access-Control-Allow-Origin: *
( https://stackoverflow.com/questions/53684484/posting-to-external-api-throws-cors-but-it-works-from-postman ,
https://developer.mozilla.org/ru/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin )
при этом из того же POSTMAN аналогичный запрос отрабатывает полностью корректно

Можно ли это исправить ?

**Comment by malyginvv** [comment]
Добрый день!
Допустимым значением для Origin является только домен `tinkoff.github.io`, поскольку размещение спецификации в формате OpenAPI v3 официально поддерживается только на нем.
