### ISSUE TITLE
Не могу получить свечи с ценами для заблокированной бумаги KYG6683N1034

### ISSUE THREAD

**Issue by irishrover** [Tinkoff/investAPI#330]
Для NuBank с недавних пор существует два FIGI для заблокированной и незаблокированной версии бумаги: BBG0136WM1M4 и 
KYG6683N1034 (https://github.com/Tinkoff/investAPI/issues/319).

Но я не могу получить свечи с ценами для заблокированной бумаги - KYG6683N1034. Для BBG0136WM1M4 запрос отрабатывает корректно.

```
{
  "figi": "KYG6683N1034",
  "from": "2022-11-01T00:02:03.000000123Z",
  "to": "2023-01-01T00:02:03.000000123Z",
  "interval": "CANDLE_INTERVAL_DAY"
}

```
=>

```
{
  "candles": []
}
```

x-tracking-id: 6392ca58c9a58e5c828fffb667d97101

**Comment by b1ng0o** [comment]
Добрый день! Торговля заблокированными бумагами в рамкам Тинькофф осуществляется как внебиржевая торговля. 
В данном случае позиция является заблокированной, а инструмент внеберживым.
В данный момент TINKOFF INVEST API предполагает работу только с биржевыми инструментами.
