### ISSUE TITLE
Несоответствие документации PortfolioRequest и PortfolioResponse

### ISSUE THREAD

**Issue by inferrna** [Tinkoff/investAPI#331]
В PortfolioRequest появилось поле _currency_, но для PortfolioResponse значения подписаны как "Общая стоимость акций в портфеле в **рублях**."

**Comment by nonamegithub** [comment]
[Сделали возможность выбора валюты возвращаемого портфеля](https://github.com/Tinkoff/investAPI/issues/267) - документацию обновить забыли/не успели.

**Comment by b1ng0o** [comment]
добрый день! Спасибо, поправили .
