### ISSUE TITLE
Проблема с правами токена

### ISSUE THREAD

**Issue by pskucherov** [Tinkoff/investAPI#333]
#### Ситуация:
Создаю токен с полным доступом для одного из счетов.

#### Ожидания:
Токен имеет доступ только к этому счёту и по нему ничего нельзя узнать про остальные счета.

#### Реальность:
По данному токену можно получить список всех счетов. Далее по счетам, к которым якобы нет доступа, узнать баланс.

**Comment by AlexanderVolkovTCS** [comment]
>По данному токену можно получить список всех счетов. 

GetAccounts и должен возвращать все счета, но счета, к которым нет доступа, отображаются со статусом ACCOUNT_ACCESS_LEVEL_NO_ACCESS.

При попытке доступа через GetPortfolio/GetPositions и подобным методам по счетам, к которым нет доступа, будет возвращена ошибка.
