### ISSUE TITLE
Приостановка торгов/делистинг российских акций

### ISSUE THREAD

**Issue by cpp4ever** [Tinkoff/investAPI#334]
Сегодня пополнился список российских акций, по которым нет биржевых данных:
```
BBG000R466J1 - Русполимет (последний день торгов 21 января 2021)
BBG000NL6ZD9 - Иркутскэнерго (последний день торгов 21 февраля 2022)
BBG001BBSZV8 - Мультисистема (последний день торгов 25 февраля 2022)
BBG000F6H7K3 - Квадра (последний день торгов 13 сентября 2022)
BBG004S682J4 - Российские сети (последний день торгов 20 декабря 2022)
BBG000KTF667 - Российские сети - акции привилегированные (последний день торгов 20 декабря 2022)
BBG00475JZZ6 - ФСК Россети (последний день торгов 20 декабря 2022)
```
Возможно, список больше.
В моём понимании, если публичные торги этими бумагами не проходят, то должен быть флаг `otc_flag=true`. Ну и, полагаю, эти бумаги должны быть только для квалов.

Собственно, если бы эти бумаги не расходовали лимит подписки на биржевые данные, меня бы оно не тревожило. Но они расходуют. Что весьма нечестно с вашей стороны.

**Comment by cpp4ever** [comment]
Возможно, для таких инструментов самый правильный флаг `api_trade_available_flag=false`. Сомневаюсь, что этими инструментами можно торговать через API.

**Comment by b1ng0o** [comment]
Добрый день, по данным получаемым с биржи у большинства инструментов статус normal_trading. По ним доступно выставление стоп заявок. Поэтому флаг api_trade_available_flag установлен корректно. С остальными инструментами разберемся, спасибо.

**Comment by cpp4ever** [comment]
> Добрый день, по данным получаемым с биржи у большинства инструментов статус normal_trading. По ним доступно выставление стоп заявок. Поэтому флаг api_trade_available_flag установлен корректно. С остальными инструментами разберемся, спасибо.

Совершенно не понимаю куда выставляются стоп ордера, если рынка нет. Как может работать стоп-ордер, если нет торгов (не определена цена инструмента)..?
Собственно, исходя из того, что цена инструмента неизвестна, я бы ожидал увидеть как минимум `otc_flag=true`. Но это сразу порождает вопрос зачем `api_trade_available_flag=true`..?
И не надо впаривать про `normal_trading` - попробуйте сами поторговать инструментом без цены... Хотя бы вручную.

**Comment by cpp4ever** [comment]
Если вы считаете, что проблема на стороне биржы, то очень правильный шаг - проконсультироваться с биржей. Возможно, это недогляд биржы. Или у них есть осмысленное объяснение и рекомендации для вас как транслировать эту информацию клиентам.
