### ISSUE TITLE
Продолжение про проблему с правами токена

### ISSUE THREAD

**Issue by pskucherov** [Tinkoff/investAPI#336]
Продолжение вот этого #333

@AlexanderVolkovTCS закрывать ишью до окончания дискуссии не ок. Поэтому завожу новый.

> GetAccounts и должен возвращать все счета, но счета, к которым нет доступа, отображаются со статусом ACCOUNT_ACCESS_LEVEL_NO_ACCESS.

Должен... `не баг а фича` ;) 
У меня вот ситуация, что заказчик не хочет, чтобы были видны все его счета при тестировании на его токене. На токене, у которого доступ к одному счёту. 
* В последствии это и вскрыло проблему с тем что был виден баланс всех счетов.

![image](https://user-images.githubusercontent.com/3197868/209237676-fe44ab04-9a2f-4ce0-9db1-33ff4101bafa.png)

Что с этим делать? Говорить пользователям, что GetAccounts и должен возвращать все счета? Или скрывать и делать вид что их не видно? 😂

> При попытке доступа через GetPortfolio/GetPositions и подобным методам по счетам, к которым нет доступа, будет возвращена ошибка.

Баланс по счёту возвращал `GetMarginAttributes`. Очень долго. А после закрытия ишью #333 внезапно нет. Вот так совпадение. Ну, надеюсь вы проведёте аудит безопасности.

**Comment by pskucherov** [comment]
![image](https://user-images.githubusercontent.com/3197868/209312869-74ba46f1-0684-4f30-a295-7505f2179453.png)


Кроме количества счетов и их id видные ещё названия счетов. К которым нет доступа.

![image](https://user-images.githubusercontent.com/3197868/209307753-846a90db-a3ec-49fb-bb89-2ae83e0de9b0.png)

**Comment by AlexanderVolkovTCS** [comment]
>Баланс по счёту возвращал GetMarginAttributes

Проблема с методом была исправлена во вчерашнем релизе v1.1, спасибо.
GetMarginAttributes возвращает не баланс, а маржинальные показатели портфеля (только при включенной маржиналке). 
Для получения баланса нужно вызывать GetPortfolio(). 

>Кроме количества счетов и их id видные ещё названия счетов. К которым нет доступа.

В спецификации метода GetAccounts() сценариями использования предполагалось отображение всех счетов, для этого статус ACCOUNT_ACCESS_LEVEL_NO_ACCESS и добавлен. Про название - обсудим с коллегами и вернусь с ответом, выглядит действительно как лишняя информация.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, решение - вообще исключить оставшиеся счета со статусом ACCOUNT_ACCESS_LEVEL_NO_ACCESS из результатов GetAccounts. Будет в ближайшем релизе.
