### ISSUE TITLE
Некорректный ответ GetPortfolio

### ISSUE THREAD

**Issue by borrispu** [Tinkoff/investAPI#338]
При запросе GetPortfolio иногда (!) вместо одной из позиций приходит пустая. Конкретный пример - пустой figi у акций Газпром в четвертом элементе массива positions. Прилагаю текстовый файл с ответом.
[Response20221226.txt](https://github.com/Tinkoff/investAPI/files/10304217/Response20221226.txt)

Заголовки ответа для уточнения:
"date": "Mon, 26 Dec 2022 17:03:06 GMT"
"grpc-metadata-x-tracking-id": "63a9d3cb6386e8f56373ecad6e5cf3e0"

**Comment by b1ng0o** [comment]
Добрый день, попробуйте обновить контракты, в новых версиях доступны instrument_uid'ы инструментов, они должны заполнять всегда. Это сделано для более точного матчинга инструментов и поддержки опционов, которые не имеют figi.

**Comment by borrispu** [comment]
> Добрый день, попробуйте обновить контракты, в новых версиях доступны instrument_uid'ы инструментов, они должны заполнять всегда. Это сделано для более точного матчинга инструментов и поддержки опционов, которые не имеют figi.

В данном случае у акции должен быть FIGI, но он не приходил в ответе. При каких условиях воспроизводится ошибка, мне не совсем понятно, вчера поймал несколько раз. Переориентируюсь на instrument_uid.

**Comment by b1ng0o** [comment]
Если после обновления контрактов ситуация повториться, переоткройте данное issue и приложите новые данные которые возвращаются в getPortfolio
