### ISSUE TITLE
Ошибка market_data.get_candles

### ISSUE THREAD

**Issue by Pavel26ru** [Tinkoff/investAPI#339]
При попытке получить историю по свечам, возникает такая ошибка: 
File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 496, in grpc._cython.cygrpc.Channel.segregated_call
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 353, in grpc._cython.cygrpc._segregated_call
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 357, in grpc._cython.cygrpc._segregated_call
ValueError: Cannot invoke RPC on closed channel!

Кто сталкивался с таким? 
Как решить эту проблему?

**Comment by irusland** [comment]
Будьте добры прикрепить код воспроизводящий ситуацию, а также прикрепите номер версии SDK, вашу OS, версию питона.

Советую создать issue в соответствующем SDK по шаблону https://github.com/Tinkoff/invest-python/issues/new/choose

**Comment by Pavel26ru** [comment]
Код: 
import json
from tinkoff.invest.constants import INVEST_GRPC_API
from tinkoff.invest import Client, CandleInterval, HistoricCandle, RequestError
from tinkoff.invest.utils import now
from datetime import datetime, timedelta
import pandas as pd
import pandas_ta as ta
import apimoex
import aiohttp
import asyncio
import aiomoex


api_token = 'TOKEN'
# python3 -m grpc_tools.protoc -I=./ --python_out=./pb-py --grpc_python_out=./pb-py ./bchrpc.proto

TIKER = ['TRUR']
taymfraem = 10

# Таймфреймы
# 1 (1 минута),
# 10 (10 минут),
# 60 (1 час),
# 24 (1 день),
# 7 (1 неделя),
# 31 (1 месяц)
# 4 (1 квартал).


async def main():
    async with aiohttp.ClientSession() as session:
        for tiks in TIKER:
            data = await aiomoex.get_market_candles(session, tiks, interval=taymfraem, start='2022-12-01')
            df = pd.DataFrame(data)
            df['ema7'] = ta.ema(close = df.close, length=7)
            df['ema30'] = ta.ema(close = df.close, length=30)
            df['ema200'] = ta.ema(close = df.close, length=200)
            print(df.tail(5)[['close', 'ema7', 'ema30', 'ema200']])
            
            df_candel = client.market_data.get_candles(figi='fi_gi',
                                                       from_=now() - timedelta(weeks=5),
                                                       interval=CandleInterval.CANDLE_INTERVAL_HOUR
                                                       )
            print(df_candel)

instrument = []
tiker_figi = {}
count = 0

with Client(api_token) as client:
    p = client.instruments.shares().instruments
    for i in p:
        tiker_figi = {
            i.ticker : i.figi
        }
        instrument.append(tiker_figi)

for i in instrument:
    for j in i:
        if j == TIKER:
            fi_gi = (instrument[count])
            print(fi_gi)
            fi_gi = fi_gi[TIKER]
            print(fi_gi)

        else:
            count += 1

def analisis():
    pass


if __name__ == '__main__':
    asyncio.run(main())


Версия SDK: tinkoff-investments 0.2.0b44
OS: Windows Server 2016Python:  3.11.0

**Comment by Pavel26ru** [comment]
*Код: *










































































*import jsonfrom tinkoff.invest.constants import INVEST_GRPC_APIfrom
tinkoff.invest import Client, CandleInterval, HistoricCandle,
RequestErrorfrom tinkoff.invest.utils import nowfrom datetime import
datetime, timedeltaimport pandas as pdimport pandas_ta as taimport
apimoeximport aiohttpimport asyncioimport aiomoexapi_token = 'TOKEN'#
python3 -m grpc_tools.protoc -I=./ --python_out=./pb-py
--grpc_python_out=./pb-py ./bchrpc.protoTIKER = ['TRUR']taymfraem = 10#
Таймфреймы# 1 (1 минута),# 10 (10 минут),# 60 (1 час),# 24 (1 день),# 7 (1
неделя),# 31 (1 месяц)# 4 (1 квартал).async def main():    async with
aiohttp.ClientSession() as session:        for tiks in TIKER:
data = await aiomoex.get_market_candles(session, tiks, interval=taymfraem,
start='2022-12-01')            df = pd.DataFrame(data)
df['ema7'] = ta.ema(close = df.close, length=7)            df['ema30'] =
ta.ema(close = df.close, length=30)            df['ema200'] = ta.ema(close
= df.close, length=200)            print(df.tail(5)[['close', 'ema7',
'ema30', 'ema200']])                        df_candel =
client.market_data.get_candles(figi='fi_gi',
                       from_=now() - timedelta(weeks=5),

 interval=CandleInterval.CANDLE_INTERVAL_HOUR
                         )            print(df_candel)instrument =
[]tiker_figi = {}count = 0with Client(api_token) as client:    p =
client.instruments.shares().instruments    for i in p:        tiker_figi =
{            i.ticker : i.figi        }
instrument.append(tiker_figi)for i in instrument:    for j in i:        if
j == TIKER:            fi_gi = (instrument[count])            print(fi_gi)
          fi_gi = fi_gi[TIKER]            print(fi_gi)        else:
    count += 1def analisis():    passif __name__ == '__main__':
asyncio.run(main())*


*Версия SDK:* tinkoff-investments 0.2.0b44
*OS:* Windows Server 2016
*Python:  *3.11.0


issue - создавал пару дней назад. Сегодня увидел ответ. Такой же


ср, 28 дек. 2022 г. в 19:38, Ruslan Sirazhetdinov ***@***.***

**Comment by Pavel26ru** [comment]
Код: 
import json
from tinkoff.invest.constants import INVEST_GRPC_API
from tinkoff.invest import Client, CandleInterval, HistoricCandle, RequestError
from tinkoff.invest.utils import now
from datetime import datetime, timedelta
import pandas as pd
import pandas_ta as ta
import apimoex
import aiohttp
import asyncio
import aiomoex


api_token = 'TOKEN'
# python3 -m grpc_tools.protoc -I=./ --python_out=./pb-py --grpc_python_out=./pb-py ./bchrpc.proto

TIKER = ['TRUR']
taymfraem = 10

# Таймфреймы
# 1 (1 минута),
# 10 (10 минут),
# 60 (1 час),
# 24 (1 день),
# 7 (1 неделя),
# 31 (1 месяц)
# 4 (1 квартал).


async def main():
    async with aiohttp.ClientSession() as session:
        for tiks in TIKER:
            data = await aiomoex.get_market_candles(session, tiks, interval=taymfraem, start='2022-12-01')
            df = pd.DataFrame(data)
            df['ema7'] = ta.ema(close = df.close, length=7)
            df['ema30'] = ta.ema(close = df.close, length=30)
            df['ema200'] = ta.ema(close = df.close, length=200)
            print(df.tail(5)[['close', 'ema7', 'ema30', 'ema200']])
            
            df_candel = client.market_data.get_candles(figi='fi_gi',
                                                       from_=now() - timedelta(weeks=5),
                                                       interval=CandleInterval.CANDLE_INTERVAL_HOUR
                                                       )
            print(df_candel)

instrument = []
tiker_figi = {}
count = 0

with Client(api_token) as client:
    p = client.instruments.shares().instruments
    for i in p:
        tiker_figi = {
            i.ticker : i.figi
        }
        instrument.append(tiker_figi)

for i in instrument:
    for j in i:
        if j == TIKER:
            fi_gi = (instrument[count])
            print(fi_gi)
            fi_gi = fi_gi[TIKER]
            print(fi_gi)

        else:
            count += 1

def analisis():
    pass


if __name__ == '__main__':
    asyncio.run(main())


Версия SDK: tinkoff-investments 0.2.0b44
OS: Windows Server 2016
Python:  3.11.0

**Comment by Pavel26ru** [comment]
r = client.orders.post_order(
        order_id=str(datetime.utcnow().timestamp()),
        figi=fi_gi,
        price=Quotation(units=1, nano=0),
        quantity=1,
        account_id=a_id,
        direction=OrderDirection.ORDER_DIRECTION_BUY,
        order_type=OrderType.ORDER_TYPE_MARKET
    )


При вызове функции выставления ордера, возникает такая же ошибка.

**Comment by Pavel26ru** [comment]
При вызове функции выставления, возникает такая же ошибка:
 r = client.orders.post_order(
        order_id=str(datetime.utcnow().timestamp()),
        figi=fi_gi,
        price=Quotation(units=1, nano=0),
        quantity=1,
        account_id=a_id,
        direction=OrderDirection.ORDER_DIRECTION_BUY,
        order_type=OrderType.ORDER_TYPE_MARKET
    )






































*Traceback (most recent call last):  File
"C:\Users\Administrator\Desktop\IT_Trading\Тинькофф\root.py", line 88, in
<module>    asyncio.run(main())  File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py",
line 190, in run    return runner.run(main)           ^^^^^^^^^^^^^^^^
File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py",
line 118, in run    return self._loop.run_until_complete(task)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py",
line 650, in run_until_complete    return future.result()
 ^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\Desktop\IT_Trading\Тинькофф\root.py", line 41, in
main    return figi(count)           ^^^^^^^^^^^  File
"C:\Users\Administrator\Desktop\IT_Trading\Тинькофф\root.py", line 68, in
figi    return order_type(fi_gi)           ^^^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\Desktop\IT_Trading\Тинькофф\root.py", line 73, in
order_type    r = client.orders.post_order(
^^^^^^^^^^^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinkoff\invest\_errors.py",
line 18, in wrapper    return func(*args, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinkoff\invest\services.py",
line 1238, in post_order    response, call =
self.stub.PostOrder.with_call(
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\grpc\_channel.py",
line 955, in with_call    state, call, = self._blocking(request, timeout,
metadata, credentials,
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File
"C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\grpc\_channel.py",
line 926, in _blocking    call = self._channel.segregated_call(
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File
"src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 496, in
grpc._cython.cygrpc.Channel.segregated_call  File
"src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 353, in
grpc._cython.cygrpc._segregated_call  File
"src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 357, in
grpc._cython.cygrpc._segregated_callValueError: Cannot invoke RPC on closed
channel!*

чт, 29 дек. 2022 г. в 12:36, Павел Дмитриев ***@***.***>:

**Comment by Pavel26ru** [comment]
Подозреваю что проблема с компиляцией proto контрактов. Но не нашёл информации, как их компилировать, и использовать, скриптом установил контракты в директорию  проекта. А дальше не понятно, что и как.

**Comment by Pavel26ru** [comment]
?????????????????????????????????????????????????????????????????????


Есть кто?
Вопрос можно как-то решить?

чт, 29 дек. 2022 г. в 14:27, Павел Дмитриев ***@***.***>:

**Comment by irusland** [comment]
Проблема происходит из-за преждевременного выхода из контекстного менеджера, что способствует закрытию grace соединения.

<img width="1074" alt="Screenshot 2022-12-30 at 18 04 41" src="https://user-images.githubusercontent.com/49832869/210084803-25ce2b98-64d4-45a0-a0b6-8737bc519fe3.png">

Ваша ошибка не относится к нашему SDK, советую почитать про [Context managers](https://book.pythontips.com/en/latest/context_managers.html)

При возникновении еще каких либо проблем просьба открывать issue в репозитории https://github.com/Tinkoff/invest-python/issues а не здесь.

Рабочая версия кода:
```
import asyncio
import os
from datetime import timedelta

from tinkoff.invest import Client, CandleInterval
from tinkoff.invest.utils import now

TIKER = ['TRUR']
taymfraem = 10


async def main():
    for tiks in TIKER:
        df_candel = client.market_data.get_candles(
            figi='fi_gi',
            from_=now() - timedelta(days=2),
            to=now(),
            interval=CandleInterval.CANDLE_INTERVAL_HOUR
        )
        print(df_candel)


instrument = []
tiker_figi = {}
count = 0

client_manager = Client(os.environ['INVEST_TOKEN'])
client = client_manager.__enter__()

p = client.instruments.shares().instruments
for i in p:
    tiker_figi = {
        i.ticker: i.figi
    }
    instrument.append(tiker_figi)

for i in instrument:
    for j in i:
        if j == TIKER:
            fi_gi = (instrument[count])
            print(fi_gi)
            fi_gi = fi_gi[TIKER]
            print(fi_gi)

        else:
            count += 1

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by Pavel26ru** [comment]
Спасибо!



пт, 30 дек. 2022 г. в 18:11, Ruslan Sirazhetdinov ***@***.***
