### ISSUE TITLE
Опять дубли в курсорах

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#340]
Добрый день

опять обнаружились дубли транзакций с разными ИД

<img width="860" alt="Screenshot 2022-12-27 at 18 26 49" src="https://user-images.githubusercontent.com/15725406/209687677-12f978db-0eea-4104-8cd4-2f15f6f1da07.png">

На скрине видно, что 2 эти операции имеют разный ИД, но при этом у них одинаковый курсор (интересно, значит ли это что ИД операции не настоящий?)

обе операции имеют статус Executed и всё остальное абсолютно одинаковое кроме ИД

**Comment by AlexanderVolkovTCS** [comment]
Добрый день

>но при этом у них одинаковый курсор

у них разный курсор

**Comment by WhiteRj** [comment]
> Добрый день
> 
> > но при этом у них одинаковый курсор
> 
> у них разный курсор

Действительно, но тем не менее, одна из сделок - дубль
