### ISSUE TITLE
impossible to install on MAC M1

### ISSUE THREAD

**Issue by pasitiff** [Tinkoff/investAPI#342]
привет. из-за зависимости grpcio невозможно установить API. до сих. пор все шарлатанства нагугленые для установки grpcio не помогают. как вы разрабатывали  api? наверняка же на маках сидите... или просто еще на intel?:).  как чинить?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, если под "установить api" имеете ввиду установить библиотеку на питоне, то 
попробуйте вариант https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop

**Comment by pasitiff** [comment]
> Добрый день, если под "установить api" имеете ввиду установить библиотеку на питоне, то попробуйте вариант https://stackoverflow.com/questions/66640705/how-can-i-install-grpcio-on-an-apple-m1-silicon-laptop

Александр, гуглить я тоже умею:) не помогало. Но буквально вчера я "случайно" решил проблему, решая аналогичную с установкой tables:)))


pip install cython
brew install hdf5
brew install c-blosc
export HDF5_DIR=/opt/homebrew/opt/hdf5
export BLOSC_DIR=/opt/homebrew/opt/c-blosc

после этого pip install tables завершилось без ошибки,
pip install grcpio также завершилось без ошибки.

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за информацию!

**Comment by pasitiff** [comment]
рано я радовался..... в итоге, все действительно устанавливается, вот последние строки:

Successfully installed iso8601-1.1.0 prettytable-3.6.0 tinkoff.invest-1.0.5 ujson-5.7.0
(base) aaaa@MacBook-Pro-Pro ~ %

но на строку 
from tinkoff.invest import Client
интерпретатор дает:

No module named 'tinkoff.invest'
  File "/Users/aaaa/Py/Trade/newtinapi.py", line 1, in <module>
    from tinkoff.invest import Client

**Comment by AlexanderVolkovTCS** [comment]
Попробуйте `invest-python % export PYTHONPATH=.`

**Comment by pasitiff** [comment]
я не понимаю смысла этой строки, и что с ней сделать. это в терминале? конечно же дает ошибку

**Comment by pasitiff** [comment]
Возникло исключение: ModuleNotFoundError
No module named 'tinkoff.invest'

рещультат тот же

**Comment by daxartio** [comment]
Скиньте команду установки пакета

**Comment by daxartio** [comment]
Также результат команды 

`pip list`

Это поможет понять причину

**Comment by pasitiff** [comment]
в pdf
[tin.pdf](https://github.com/Tinkoff/investAPI/files/10460621/tin.pdf)

**Comment by daxartio** [comment]
Удалите пакет tinkoff-invest

Этот пакет также хранит код в tinkoff.invest как и наш 

Заново поставьте tinkoff-investments

**Comment by pasitiff** [comment]
ошибка осталась такой же 
Возникло исключение: ImportError
dlopen(/Users/vromanchuk/miniforge3/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
  File "/Users/vromanchuk/Py/Trade/newtinapi.py", line 1, in <module>
    from tinkoff.invest import Client
ImportError: dlopen(/Users/vromanchuk/miniforge3/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'

pip list теперь такой

tinkoff                           0.1.1
tinkoff-invest-openapi-client     0.0.7
tinkoff-investments               0.2.0b46

**Comment by daxartio** [comment]
Ох, я ошибся

Посмотрел код tinkoff-invest и увидел, что используется пакет tinkoff_invest, а не tinkoff.invest. 
Этот лог меня смутил
> Successfully installed iso8601-1.1.0 prettytable-3.6.0 tinkoff.invest-1.0.5 ujson-5.7.0

**Comment by irusland** [comment]
Подскажите, откуда и как был установлен питон?

Попробуйте выполнить и скажите что выдает
```
python3 -m venv .venv
source .venv/bin/activate
pip3 install tinkoff-investments
```

**Comment by pasitiff** [comment]
Установлено через конду. еще были трюки (выше описаны), как поставить grpcio.

(base) vromanchuk@MacBook-Pro-Pro ~ % python3 -m venv .venv
(base) vromanchuk@MacBook-Pro-Pro ~ % source .venv/bin/activate
(.venv) (base) vromanchuk@MacBook-Pro-Pro ~ % pip3 install tinkoff-investments
Collecting tinkoff-investments
  Using cached tinkoff_investments-0.2.0b46-py3-none-any.whl (182 kB)
Collecting cachetools<6.0.0,>=5.2.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting tinkoff<0.2.0,>=0.1.1
  Using cached tinkoff-0.1.1-py3-none-any.whl (1.0 kB)
Collecting protobuf<4.0.0,>=3.20.2
  Using cached protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
Collecting python-dateutil<3.0.0,>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting grpcio<2.0.0,>=1.39.0
  Using cached grpcio-1.51.1.tar.gz (22.1 MB)
Collecting pydantic<2.0.0,>=1.9.2
  Using cached pydantic-1.10.4-cp39-cp39-macosx_11_0_arm64.whl (2.6 MB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for grpcio, since package 'wheel' is not installed.
Installing collected packages: typing-extensions, six, tinkoff, python-dateutil, pydantic, protobuf, grpcio, cachetools, tinkoff-investments
    Running setup.py install for grpcio ... done
Successfully installed cachetools-5.3.0 grpcio-1.51.1 protobuf-3.20.3 pydantic-1.10.4 python-dateutil-2.8.2 six-1.16.0 tinkoff-0.1.1 tinkoff-investments-0.2.0b46 typing-extensions-4.4.0

**Comment by irusland** [comment]
Вижу что все установилось. Попробуйте прогнать простейший скрипт из примеров библиотеки

**Comment by irusland** [comment]
https://github.com/Tinkoff/invest-python/tree/main/examples

**Comment by pasitiff** [comment]
Руслан, см выше, ошибка актуальна:

File "/Users/vromanchuk/Py/Trade/newtinapi.py", line 1, in
from tinkoff.invest import Client
ImportError: dlopen(/Users/vromanchuk/miniforge3/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'

**Comment by pasitiff** [comment]
с учетом того, что формально, судя по пути либы в ошибке, он ругается на grpc, только что сделал reinstall force. ошибка при исполнении примера вашей библиотеки не изменилась.

vromanchuk@MacBook-Pro-Pro ~ % pip install --upgrade --force-reinstall grpcio
Collecting grpcio
  Using cached grpcio-1.51.1-cp39-cp39-macosx_11_0_arm64.whl
Installing collected packages: grpcio
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.51.1
    Uninstalling grpcio-1.51.1:
      Successfully uninstalled grpcio-1.51.1
Successfully installed grpcio-1.51.1

**Comment by irusland** [comment]
Строчка `vromanchuk@MacBook-Pro-Pro ~ % ` мне подсказывает, что вы не работаете в виртуальном окружении. Попробуйте не устанавливать никаких других библиотек кроме нашей, и запустите код примера. Возникает ли ошибка в чистом виртуальном окружении?

**Comment by irusland** [comment]
Я в сниппете указал название .venv здесь же показывает base. Деактивируйте его и активируйте чистое из моего примера

**Comment by pasitiff** [comment]
Last login: Mon Jan 30 16:07:23 on ttys005
/dev/fd/12:18: command not found: compdef
(base) vromanchuk@MacBook-Pro-Pro ~ % python3 -m venv .venv
(base) vromanchuk@MacBook-Pro-Pro ~ % source .venv/bin/activate
(.venv) (base) vromanchuk@MacBook-Pro-Pro ~ % cd Py/Trade
(.venv) (base) vromanchuk@MacBook-Pro-Pro Trade % python3 newtinapi.py
Traceback (most recent call last):
  File "/Users/vromanchuk/Py/Trade/newtinapi.py", line 1, in <module>
    from tinkoff.invest import Client
  File "/Users/vromanchuk/.venv/lib/python3.9/site-packages/tinkoff/invest/__init__.py", line 1, in <module>
    from .clients import AsyncClient, Client
  File "/Users/vromanchuk/.venv/lib/python3.9/site-packages/tinkoff/invest/clients.py", line 3, in <module>
    import grpc
  File "/Users/vromanchuk/.venv/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/vromanchuk/.venv/lib/python3.9/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/vromanchuk/.venv/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'

**Comment by pasitiff** [comment]
на удивление в .venv  заработало. Я вынужден был заново в другое окружение поставить все библиотеки и оно заработало (основной мой код).  Только если честно, я нихнера не понял технически, откуда у меня взялось это вирт окружение .venv  и в какой момент
