### ISSUE TITLE
Пара проблем с download_md.sh

### ISSUE THREAD

**Issue by SimSonic** [Tinkoff/investAPI#343]
Добрый день.

Скрипт для скачивания исторических данных вылетает на Too many requests. Причём видно, что несколько раз ушёл спать.

![image](https://user-images.githubusercontent.com/2697754/211154703-17ca9b8c-6f13-4eea-b5c8-590519d1e6bc.png)

Вторая проблема: я ожидал, что будут скачаны минутные свечи, но по тем нескольким FIGI, что пока получилось скачать, всё выглядит печально — разрывы многоминутные, иногда часовые:

![image](https://user-images.githubusercontent.com/2697754/211154822-34277b09-4121-4a96-be9b-6e8a0f5c114e.png)

![image](https://user-images.githubusercontent.com/2697754/211154832-a03424db-6d95-4b9f-bfff-71d1e01ee7a3.png)

Нормально ли это?

**Comment by SimSonic** [comment]
Первую проблему поправил, добавив return 0:

```bash
...
  # Если превышен лимит запросов в минуту (30) - повторяем запрос.
  if [ "$response_code" = "429" ]; then
      echo "rate limit exceed. sleep 5"
      sleep 5
      download "$figi" "$year";
      return 0
  fi
...
```

**Comment by hondasmx** [comment]
Пропуски в свечах - это нормально
Значит, что не было торгов в данную минуту

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за пул реквест
