### ISSUE TITLE
выгружаю облигации которые не доступны к покупке

### ISSUE THREAD

**Issue by JonS87** [Tinkoff/investAPI#345]
с помощью метода bonds(instrument_status = 2) выгружаю список облигаций имеющихся в тинькофф, дальше фильтрую полученный результат по следующим критериям:
p.country_of_risk == 'RU'
and p.buy_available_flag == True
and p.sell_available_flag == True
and p.amortization_flag == False
and p.for_qual_investor_flag == False
а на выходе получаю облигации которые в самом тинькофф инвестициях не доступны к торговле по техническим причинам, например RU000A102AK9

**Comment by AlexanderVolkovTCS** [comment]
Ответил в https://github.com/Tinkoff/invest-python/issues/174
