### ISSUE TITLE
Смена FIGI в операциях

### ISSUE THREAD

**Issue by MrStepson** [Tinkoff/investAPI#349]
Не первый раз наблюдаю внезапное изменение FIGI в операциях, возвращаемых методом GetOperationsByCursorRequest, в том числе, выполненных довольно давно.  Пример - пару дней назад FIGI операций с USD поменялась с BBG0013HGFT4 на BBG00QX7QPC3. Сегодня у операций с евро FIGI стал BBG00QX7QP60 (был BBG0013HJJ31). Поясните, пожалуйста, чем вызвана эта смена? Можно ли ее как-то предвидеть или получать информацию о выполненных заменах?

**Comment by sorc1** [comment]
В последних версиях contracts в протобуфах повсюду пометили figi как deprecated. Я после этого перешёл на uid, хотя я и в figi замен не замечал.

**Comment by Agasper** [comment]
Судя по докухе в Operation есть хотя бы asset_uid, но в PortfolioPosition явно какие-то другие uid'ы. Ничего похожего на то как их совместить там нет.

**Comment by sorc1** [comment]
Я говорил о instrument_uid, который есть в PortfolioPosition. Он совпадает, например, с Share.uid. А соотносится ли  Operation.asset_uid с uid инструмента, - я не в курсе.

**Comment by Agasper** [comment]
Только что проверил instrument_id меняется вместе с figi, так что все равно не сопоставить

**Comment by Agasper** [comment]
Конкретный пример, две операции по одной облигации с разным instrument_id и figi
Сейчас одну из них (на покупку) никак нельзя связать с позицией в порфеле, т.к. у нее новые instrument_id и figi

```
OperationItem(cursor='1627268400000000015', broker_account_id='2001993498', id='1407365157', parent_operation_id='', name='Сэтл Групп выпуск 3', date=datetime.datetime(2021, 7, 26, 3, 0, tzinfo=datetime.timezone.utc), type=<OperationType.OPERATION_TYPE_COUPON: 23>, description='Выплата купонов по облигациям Сэтл Групп выпуск 3', state=<OperationState.OPERATION_STATE_EXECUTED: 1>, instrument_uid='3ce6e4a3-39f7-450b-b089-ecf3475a69e4', figi='TCS00A1030X9', instrument_type='bond', instrument_kind=<InstrumentType.INSTRUMENT_TYPE_BOND: 1>, payment=MoneyValue(currency='rub', units=1059, nano=500000000), price=MoneyValue(currency='', units=0, nano=0), commission=MoneyValue(currency='', units=0, nano=0), yield_=MoneyValue(currency='', units=0, nano=0), yield_relative=Quotation(units=0, nano=0), accrued_int=MoneyValue(currency='', units=0, nano=0), quantity=0, quantity_rest=0, quantity_done=0, cancel_date_time=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), cancel_reason='', trades_info=OperationItemTrades(trades=[]), asset_uid='e919bb3d-b6aa-4422-ae0c-ea9164ba9dcd')

OperationItem(cursor='1618993505000000117', broker_account_id='2001993498', id='23657167067', parent_operation_id='', name='Сэтл Групп выпуск 3', date=datetime.datetime(2021, 4, 21, 8, 25, 5, tzinfo=datetime.timezone.utc), type=<OperationType.OPERATION_TYPE_BUY: 15>, description='Покупка 50 облигаций Сэтл Групп выпуск 3', state=<OperationState.OPERATION_STATE_EXECUTED: 1>, instrument_uid='bc5e47e5-df1c-4e7a-a500-cae0c2c03c9b', figi='TCSS0A1030X9', instrument_type='bond', instrument_kind=<InstrumentType.INSTRUMENT_TYPE_BOND: 1>, payment=MoneyValue(currency='rub', units=-50000, nano=0), price=MoneyValue(currency='rub', units=1000, nano=0), commission=MoneyValue(currency='rub', units=-25, nano=0), yield_=MoneyValue(currency='', units=0, nano=0), yield_relative=Quotation(units=0, nano=0), accrued_int=MoneyValue(currency='', units=0, nano=0), quantity=50, quantity_rest=0, quantity_done=50, cancel_date_time=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), cancel_reason='', trades_info=OperationItemTrades(trades=[OperationItemTrade(num='3849828595', date=datetime.datetime(2021, 4, 21, 11, 2, 46, 4000, tzinfo=datetime.timezone.utc), quantity=50, price=MoneyValue(currency='rub', units=1000, nano=0), yield_=MoneyValue(currency='', units=0, nano=0), yield_relative=Quotation(units=0, nano=0))]), asset_uid='e919bb3d-b6aa-4422-ae0c-ea9164ba9dcd')
```

**Comment by Ipsilon91** [comment]
У меня та же проблема. Для операций по покупке\продаже евро часть операций с figi BBG0013HJJ31, а часть с BBG00QX7QP60 (см. скриншот)
![figi change fo tcs](https://user-images.githubusercontent.com/20323211/213454900-4d026e44-468c-4f90-8327-0aa6fec5250c.png)
Запрос: 
[ТКС запрос.txt](https://github.com/Tinkoff/investAPI/files/10457129/default.txt)
Полный ответ:
[ТКС ответ.txt](https://github.com/Tinkoff/investAPI/files/10457131/default.txt)

**Comment by AlexanderVolkovTCS** [comment]
Проблема с евро исправлена, спасибо за репорт.
