### ISSUE TITLE
Привести свечи к одному типу.

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/investAPI#351]
Сейчас исторические свечи  HistoricCandle  и свечи для стримов Сandle отличаются по набору полей. Например, в Сandle есть поле Figi, а в HistoricCandle нет. Зачем выделять исторические свечи в отдельный тип непонятно.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, еще и флаг завершенности различается в этих структурах. В целях сохранения совместимости объединять свечи не планируется
