### ISSUE TITLE
post order error: CZena vne limitov po instrumentu

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#354]
Пытаюсь выставить заявку, получаю такую ошибку.
```
("StatusCode": InvalidArgument), 
("Detail": "30049"), 
("Trailers.message": "post order error: CZena vne limitov po instrumentu"), 
("Trailers.x-tracking-id": "63d2afb7080b9fcd9aac59f05ba41769"), 
("Trailers.x-envoy-upstream-service-time": "259"), 
("Trailers.date": "Thu, 26 Jan 2023 16:52:07 GMT"), 
("Trailers.server": "envoy"), 
("Trailers.x-ratelimit-limit": "300, 300;w=60"), 
("Trailers.x-ratelimit-remaining": "297"), 
("Trailers.x-ratelimit-reset": "53")
```

Можно более подробно объяснить в чем ошибка?
Могу предположить что проблема в этом:
> Биржа ограничивает цену, которую можно указать в лимитной заявке, крайними предложениями в биржевом стакане (параметры limit_up и limit_down).

Но хотелось бы точно знать.

**Comment by AlexanderVolkovTCS** [comment]
Все верно пишете, цена выходит за limitUp/limitDown
