### ISSUE TITLE
Добавить метод GetTrades (получение истории собственных сделок)

### ISSUE THREAD

**Issue by ivan-volnov** [Tinkoff/investAPI#355]
Здравствуйте.

Добавьте пожалуйста метод GetTrades (OrdersService) (RPC вариант TradesStream) для получения истории собственных сделок. Сигнатуру метода можно сделать по аналогии с GetLastTrades (MarketDataService), за исключением лимита в 1 час.

Данный метод необходим для загрузки собственных трейдов в момент старта приложения.

Альтернативы:
- Необходимую информацию можно запрашивать через GetOrderState, если запоминать все order_id.
Но в OrderStage отсутствует необходимое поле date_time. Да и множество запросов по всем ордерам можно избежать новым предлагаемым методом.
- GetBrokerReport мог бы послужить источником необходимых данных но задержка в 3 дня делает его неприемлемым для данных целей.
- GetOperations мог бы помочь. Но он избыточен и есть сложность с фильтрацией ордеров и выяснением direction сделки. Пока попробую его.

**Comment by AlexanderVolkovTCS** [comment]
Источник данных для подобного метода был бы тот же, что и у GetOperations.
Кажется, вашу задачу лучше всего и решить через GetOperations
