### ISSUE TITLE
Добавить кодификацию ошибок выставления ордеров

### ISSUE THREAD

**Issue by sorc1** [Tinkoff/investAPI#358]
Сейчас при ошибке выставления ордера получаем код ошибки "30049" и расширенную причину ошибки транслитом в Trailers.message. Хотелось бы, чтобы каждая расширенная причина ошибки имела свой код, - это позволит реализовывать логику с реакцией на ряд ошибок.

**Comment by AlexanderVolkovTCS** [comment]
Проанализировал unknown ошибки, в ближайшем релизе выделим в отдельные коды следующие ошибки:

Заявка не исполнена биржей
Заявка отклонена, попробуйте повторить позже
Сейчас эта сессия не идёт
Торги по этому финансовому инструменту сейчас не проводятся
Цена вне лимитов по инструменту
Цена должна быть положительной
Для торговли этим инструментом пройдите тестирование

**Comment by AlexanderVolkovTCS** [comment]
В сегодняшнем релизе добавили.
