### ISSUE TITLE
Очень мало информации о режимe торгов, который необходим для поиска инструмента по тикеру

### ISSUE THREAD

**Issue by romdevios** [Tinkoff/investAPI#36]
Так как всё API работает с figi, то у меня возникли трудности с его поиском. Для реквеста instruments.getInstrumentBy при поиске по тикеру обязательно указывать class_code, но в документации нет достаточного (для несведущих) описания что это и как искать. В интернете тоже очень мало информации о возможных значениях.

### Предложение
Есть ли возможность сделать этот поиск гибким и без указания class_code выдавать все подходящие инструменты?

**Comment by ZaValera** [comment]
Поддерживаю! Документация очень скудна на примеры, и до очень многих вещей приходится доходить методом тыка.
Дотыкался, до того, что `class_code`
Санкт-Петербургской биржи - `SPBMX`
Московской биржи - `TQBR`

**Comment by serejhaaa** [comment]
Вы всегда можете получить полный список инструментов нужного типа методами (bonds, shares, etfs и т.п.) и найти там интересующий вас инструмент по тикеру, и найти там его режим торгов (class_code). 
Однако, учитывая количество подобных вопросов мы реализуем удобным метод поиска инструментов по тикеру без указания дополнительных параметров, следите за обновлениями.

**Comment by kdeyko** [comment]
Добрый день!
Есть ли какая-то информация, когда можно ждать метод поиска инструментов по тикеру?

**Comment by HiHat** [comment]
Тоже интересует когда будет реализован поиск?
Приходится пользоваться поиском из старого API :(

**Comment by HiHat** [comment]
> Вы всегда можете получить полный список инструментов нужного типа методами (bonds, shares, etfs и т.п.) и найти там интересующий вас инструмент по тикеру, затем найти там его режим торгов (class_code).
Столкнулся с тем, что этот метод очень сложен для реализации в Google Apps Script, т.к. сохранить эту информацию можно только пользуясь CacheService через множество ключей и то, максимум на 6 часов!

**Comment by HiHat** [comment]
del

**Comment by Rolllab** [comment]
> Так как всё API работает с figi, то у меня возникли трудности с его поиском. Для реквеста instruments.getInstrumentBy при поиске по тикеру обязательно указывать class_code, но в документации нет достаточного (для несведущих) описания что это и как искать. В интернете тоже очень мало информации о возможных значениях.
> 
> ### Предложение
> Есть ли возможность сделать этот поиск гибким и без указания class_code выдавать все подходящие инструменты?
Я, конечно, не специалист...)) А тоже учусь еще... Но что бы получить figi и прочую ерунду я написал вот это:

import pandas as pd
from tinkoff.invest import Client

token = 'fsdf'     #Сюда свой токен

def init():
    try:
        with Client(token) as client:
            info = client.instruments.shares(instrument_status=InstrumentStatus.INSTRUMENT_STATUS_BASE)
            df_ = name(info.instruments)
            figi = list(df_.iloc[:, 0])           # Это все figi
            ticker = list(df_.iloc[:, 1])       # Это весь ticker
            class_code = list(df_.iloc[:, 2])     # Это весь class_code 
            isin = list(df_.iloc[:, 3])                # Это весь isin  
            print(df_)                                    # Это весь df_


    except RequestError as e:
        print(str(e))

def name(instruments):
    df_ = pd.DataFrame([{
        'figi': i.figi,
        'ticker': i.ticker,
        'class_code': i.class_code,
        'isin': i.isin,
    } for i in instruments])
    return df_

**Comment by AlexanderVolkovTCS** [comment]
https://tinkoff.github.io/investAPI/instruments/#findinstrument
