### ISSUE TITLE
В сообщении PortfolioPosition метода GetPortfolio отсутствует blocked_lots

### ISSUE THREAD

**Issue by AleX100050** [Tinkoff/investAPI#360]
Добрый день. в VS2019 (использую C#) установлен последний пакет Tinkoff.InvestApi 0.4.1 из NuGet.
В сообщении PortfolioPosition метода GetPortfolio отсутствует blocked_lots,  хотя в документации на оф. сайте есть описание данного поля. При переходе по ссылке на в VS2019 к классу "public sealed class PortfolioPosition..." переменной blocked_lots так же нет. В чем причина? заранее спасибо...

**Comment by AlexanderVolkovTCS** [comment]
Попробуйте обновиться до последней версии 1.3

**Comment by AleX100050** [comment]
> 

Огромное спасибо облегчили жизнь... обновил... все присутствует!!! А то приходилось самому рассчитывать сколько не перекрыто встречной заявкой, через дополнительный запрос к заявкам.
