### ISSUE TITLE
Реализовать возможность запрашивать и подписываться на свечи с другими таймфреймами (30мин, 4ч, 1н, 1м).

### ISSUE THREAD

**Issue by d7chelovechek** [Tinkoff/investAPI#364]

**Comment by d7chelovechek** [comment]
Спасибо за пример запроса недельных свеч, однако было бы приятно получать 4-х часовые запросом и подпиской, чтобы не заниматься агрегацией.

**Comment by AlexanderVolkovTCS** [comment]
В последнем релизе добавили другие интервалы для GetCandles()

**Comment by nonamegithub** [comment]
А как же "подписываться на свечи с другими таймфреймами..."? SUBSCRIPTION_INTERVAL_ONE_MINUTE и SUBSCRIPTION_INTERVAL_FIVE_MINUTES это ни о чем. 
По подписке нужны как минимум все соответствия для интервалов GetCandles, а именно:
  CANDLE_INTERVAL_1_MIN = 1; //1 минута.
  CANDLE_INTERVAL_5_MIN = 2; //5 минут.
  CANDLE_INTERVAL_15_MIN = 3; //15 минут.
  CANDLE_INTERVAL_HOUR = 4; //1 час.
  CANDLE_INTERVAL_DAY = 5; //1 день.
  CANDLE_INTERVAL_2_MIN = 6; //2 минуты.
  CANDLE_INTERVAL_3_MIN = 7; //3 минуты.
  CANDLE_INTERVAL_10_MIN = 8; //10 минут.
  CANDLE_INTERVAL_30_MIN = 9; //30 минут.
  CANDLE_INTERVAL_2_HOUR = 10; //2 часа.
  CANDLE_INTERVAL_4_HOUR = 11; //4 часа.
  CANDLE_INTERVAL_WEEK = 12; //1 неделя.
  CANDLE_INTERVAL_MONTH = 13; //1 месяц.

**Comment by nonamegithub** [comment]
И еще. Где узнать максимальный запрашиваемый период для каждого из упомянутых выше интервалов, чтобы не ловить "the maximum request period for the given candle interval has been exceeded"? Информация из документации:
_Обратите внимание, что максимально допустимый период получения свечей за один запрос — 1 календарный год. Получение данных за более длинный период возможно поочередным вызовом метода._
явно не актуальна.

**Comment by d7chelovechek** [comment]
@nonamegithub , как мне сообщили, запросов о добавлении новых таймфреймов для стримов очень мало, поэтому реализовывать это в данный момент они не намерены. Предлагаю попытать удачу и открыть еще один ишью)

**Comment by nonamegithub** [comment]
не нужен никакой ишью. мой запрос за сотню обычных идет, поэтому жду реализации в ближайшее время
