### ISSUE TITLE
Проблема взаимодействия методов ReplaceOrder и PositionsStream

### ISSUE THREAD

**Issue by ivan-volnov** [Tinkoff/investAPI#368]
Здравствуйте!

Если использовать метод ReplaceOrder на новую цену заявки то пока заявка изменяется по PositionsStream придет два эвента PositionsMoney с available_value и blocked_value. Одно на возврат available_value по старой цене, другое на установку available_value по новой цене.

В результате этого образуется окно, когда можно выставить новую заявку на свободные деньги и получаем `30042, message: not enough assets for a margin trade`.

Хотя по сути ReplaceOrder - должна выполняться одной транзакцией и вместо двух эвентов PositionsMoney должен прийти один лишь с вычисленной разницей.

Исправьте пожалуйста данное поведение.

**Comment by ivan-volnov** [comment]
Дополняю. В момент выполнения ReplaceOrder в получившееся окно может даже вклиниться другой ордер с PostOrder. И тогда на ReplaceOrder мы получим 30042.
Имхо очень неправильно! Надо исправлять.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день!
На брокере метода ReplaceOrder нет, он был добавлен исключительно в API по просьбе сообщества и представляет собой последовательные операции отмены и создания ордера без блокировки средств. Это не транзакция.

Метод был добавлен 
- для уменьшения сетевых издержек 
- в будущем, как метод будет поддерживаться брокером, он станет работать в режиме одной транзакции.

Спасибо за обращение, допишу эту информацию в документации.

**Comment by ivan-volnov** [comment]
@AlexanderVolkovTCS Теперь ясно, благодарю за ответ!
