### ISSUE TITLE
INVALID_ARGUMENT 30057 после 70002 в PostOrderAsync

### ISSUE THREAD

**Issue by solalx** [Tinkoff/investAPI#369]
Как понять ошибку
 "the order is a duplicate, but the order report was not found, Код: 30057"
INVALID_ARGUMENT 30057 ?

Случаются задвоения лимитных заявок на покупку в Orders.PostOrderAsync, если вызов валится по ошибке (например 70002) и реально заявка была принята, но нигде не появилась ни в заявках ни в заказе ни в журнале и появляется  позже со значительной задержкой.

Начал пользоваться OrderID задавая его новым GUID для каждой удачной (без ошибок) операции  

Но тогда получаю 30057 при попытке повторить заявку с тем же GUID( в OrderID) если предыдущий вызов .PostOrderAsync  отлетел по ошибке  70002
Как я понимаю, если 30057 , то заявка все же дошла.
Но в списке заявок ее нет, и в портфеле акции не появляются

Как контролировать такую ситуацию?
Что такое the order report was not found?

Неплохо бы для моего GUID(который я пакую в OrderID при вызове PostOrderAsync),  в ошибке(Exception) 30057  хотя бы реальный OrderID биржевой возвращать, если уж заявка дошла.

**Comment by ivan-volnov** [comment]
> Сделал повторную отправку при ошибке 70002 того же реквеста. Еще толком не проверил.

Проверил, не работает:

`error: 70002, message: internal network error, x-tracking-id: 63e5e9190ea4f0e33a59f985541cd5aa, retrying...`
`error: 30057, message: the order is a duplicate, but the order report was not found, x-tracking-id: 63e5e924b48bab6118244b0591912dbf`

Отправлял с тем же nonce. Как иначе мне получить изменившийся order_id, который до меня не дошел?
@AlexanderVolkovTCS Что делать в этом случае?

**Comment by ivan-volnov** [comment]
На сколько я понимаю, не зная систему изнутри, просто догадываясь:

На 70002 (internal network error) надо все же посылать повторно запрос как есть с тем же nonce. Для того что бы исключить потерю пакета от gateway к application server. При успешной повторной отправке запрос просто выполнится и все.

А вот потом обрабатывать 30057 (the order is a duplicate...) в худшем случае когда запрос исполнился но не дошел ответ. Видимо запрашивать список ордеров...

**Comment by ivan-volnov** [comment]
@solalx Повторюсь, 70002 означает что не известно, операция выполнилась или нет. Ждать бессмысленно. Нужно выяснять..

**Comment by solalx** [comment]
"По крайней мере 30057 после 70002 означает что операция выполнилась, но order_id не получили в ответ"
Вот и жду появления заявки или появления акций в портфеле или статуса в журнале операций.

**Comment by ivan-volnov** [comment]
> Может же быть по заявке отказ по другой причине

Действительно, может быть и такое..

**Comment by AlexanderVolkovTCS** [comment]
В сегодняшнем релизе проблему доработали: повторное выставление ордера пройдет корректно, если предыдущий ордер не дошел до биржи например по причине нарушения сетевой связанности.

До релиза такие отбивались кодом 30057

**Comment by ivan-volnov** [comment]
@AlexanderVolkovTCS 24-го в пятницу тестировал, не работает. Это уже после релиза?
