### ISSUE TITLE
Метод GetOperations возвращает операции с id = '-1' и пустым, в некоторых случаях, parentOperationId

### ISSUE THREAD

**Issue by amstedy** [Tinkoff/investAPI#37]
Tracking-id запроса с таким поведением: 1b8d388659707b2a5de3c243de01a315

На примере двух типов операций:

1) Тип операции "Удержание комиссии за операцию", возвращается id = '-1' и корректный parentOperationId, который указывает на ID родительской операции.
2) Тип операции "Выплата дивидендов", возвращается id = '-1' и parentOperationId = ''.

Данное поведение актуально и для некоторых других типов операций (либо есть parentOperationId и id = '-1', либо parentOperationId = '' и id = '-1').

Таким образом, некоторые операции невозможно уникально-идентифицировать. В первой версии API любая операция имела свой уникальный id.

**Comment by dihauti** [comment]
В принципе какие-то дополнительные операции вроде начислений и списаний вариационной маржи по фьючерсам или выплат дивидендов никак не связать с позицией. В прошлой версии АПИ это было легко осуществить, тк у операции был фиги. В текущей версии фиги нет. Никак не сформировать историю позиции (конкретно в моем кейсе нужно для аналитики подробной).

**Comment by AlexanderVolkovTCS** [comment]
Исправлено, вместо -1 возвращается идентификатор.
