### ISSUE TITLE
Нет соединения из-за ошибки: `unknown error tracking_id null`

### ISSUE THREAD

**Issue by Evleaps** [Tinkoff/investAPI#371]
### ApiRuntimeException: io exception tracking_id null

Я и еще один пользователь столкнулись с проблемой, 
Оригинальный issue тут - https://github.com/Tinkoff/invest-api-java-sdk/issues/42 

При любом запросе unknown error tracking_id null. 
Раньше работало, в 2023 перестало работать. 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/26012758/218279034-d0f38bd6-71e2-438b-a0ad-129dda7ca85e.png">

```
Exception in thread "main" ru.tinkoff.piapi.core.exception.ApiRuntimeException: io exception
Channel Pipeline: [HttpProxyHandler$HttpClientCodecWrapper#0, HttpProxyHandler#0, SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0] unknown error tracking_id null
```

-------
upd:
Feel free написать мне в telegram @raymalet, если нужна какая то информация или в реалтайме протестить. 
Уже давненько не могу ничего сделать

**Comment by Dartanum** [comment]
Приветствую! Удалось найти причину или решение?

**Comment by Evleaps** [comment]
> Приветствую! Удалось найти причину или решение?

@Dartanum Здравствуйте. В моем случае проблема была на стороне wifi/провайдера.

**Comment by Dartanum** [comment]
@Evleaps У меня, предполагаю, проблема другая. При первом вызове (использую ru.tinkoff.piapi:java-sdk-core:1.3) `investApi.getInstrumentsService().findInstrumentSync(tickerName);`
запрос проходит без проблем, а при последующих падает с ошибкой, которая указана в этом треде. Может есть мысли на этот счет?

**Comment by Dartanum** [comment]
@Evleaps запрос отправляю не больше 1-2 раза в минуту
