### ISSUE TITLE
50005 order not found

### ISSUE THREAD

**Issue by ivan-volnov** [Tinkoff/investAPI#374]
Приветствую!

Частенько случается данная ошибка когда выставляем ордер и сразу его отменяем. Через какое-то время ордер объявится и его можно будет отменить. Очень сложно за таким уследить и не потерять его.

По хорошему, запросы от каждого клиента должны выстраиваться в отдельную очередь и обрабатываться последовательно.

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер, 

>По хорошему, запросы от каждого клиента должны выстраиваться в отдельную очередь и обрабатываться последовательно.

брокер - не строго консистентная система и такой очереди по клиенту нет, однако если ордер выставился и вы получили его id, то отмена после этого момента уже должна работать.
  
давайте разберем на вашем кейсе, можете указать:

1) trackingID запроса на создание ордера
2) trackingID запроса на отмену, которая заканчивается 50005

**Comment by ivan-volnov** [comment]
К сожалению на данный момент у меня не логируются успешные запросы.
Можно поискать по запросу CancelOrder а дальше по order_id?

Вот tracking-id ошибок:
tracking-id: 6402139ce8f567f43e5920df50dcfe27 (на CancelOrder после PostOrder)
tracking-id: 640213474e83a77276f5a146d16bff84 (на CancelOrder после ReplaceOrder)

**Comment by ivan-volnov** [comment]
@AlexanderVolkovTCS Есть новости?

**Comment by ivan-volnov** [comment]
Эта ошибка случается довольно часто. Есть ли новости? @AlexanderVolkovTCS

**Comment by ivan-volnov** [comment]
Теперь повторно отправляю запрос при этой ошибке через некоторое время.

Иногда хватает задержки в 200ms а иногда сервер не распознает ордер более 12s!!

Это серьезная проблема. Просьба разобраться.

**Comment by AlexanderVolkovTCS** [comment]
>иногда сервер не распознает ордер более 12s!!

По этой части пока без изменений к сожалению( задержка на бэке брокера может быть большой у активно торгующих клиентов с большим количеством поручений. Она проявится не только на API, но на любом интерфейсе - мобилке, терминале и т.д. 
Работаем над асинхронными вариантами методов выставления и отмены заявок.
