### ISSUE TITLE
post order error: Vam zapreshhena operacziya s instrumentom

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#375]
Со вчерашнего дня получаю такую ошибку
```
("StatusCode": InvalidArgument), ("Detail": "30049"), 
("Trailers.message": "post order error: Vam zapreshhena operacziya s instrumentom OrderDirection: prodazha  InstrumentID: MU_SPBXM "), 
("Trailers.x-tracking-id": "63fdc2d191dff1b1c032908b8e91914f"), 
("Trailers.x-envoy-upstream-service-time": "278"), ("Trailers.date": "Tue, 28 Feb 2023 09:01:05 GMT"), 
("Trailers.server": "envoy"), 
("Trailers.x-ratelimit-limit": "300, 300;w=60"), 
("Trailers.x-ratelimit-remaining": "297"), 
("Trailers.x-ratelimit-reset": "55")
```

Вероятно, это стало происходить после введения новых санкций
https://www.tinkoff.ru/help/invest/situation/

Может быть пока эта проблема не будет решена поставить [флаг `api_trade_available_flag`](https://tinkoff.github.io/investAPI/instruments/#instrumentshort) в `false`?

**Comment by AlexanderVolkovTCS** [comment]
>Вероятно, это стало происходить после введения новых санкций

Да, на время переноса активов выставление поручений невозможно.

с ответом о целесообразности закрытия и последующего открытия api_trade_available_flag вернусь завтра.

**Comment by olsh** [comment]
Что-то решилось по поводу `api_trade_available_flag`?

**Comment by AlexanderVolkovTCS** [comment]
Пока решили не трогать флаг api_trade_available_flag SPB бумаг на время переноса и рекомендуем смотреть на buy_available_flag/sell_available_flag.
