### ISSUE TITLE
Исчезли инструменты из списка валют

### ISSUE THREAD

**Issue by dimakor** [Tinkoff/investAPI#379]
В истории операций есть операции с figi BBG0013HJJ31 (EUR_RUB__TOM). Однако при запросе client.instruments.currencies().instruments его нет - даже с флагом INSTRUMENT_STATUS_ALL.

**Comment by AlexanderVolkovTCS** [comment]
Инструмент появился.

**Comment by nonamegithub** [comment]
я знаю. но надо вернуть его туда, где он был. рубль - такая же валюта, как и все остальные и не гоже пользователям API что-то костылить, чтобы иметь возможность использовать его наравне с другими валютами.

**Comment by nonamegithub** [comment]
пропал, ориентировочно, вчера вечером- сегодня утром.
