### ISSUE TITLE
Ошибка Stream removed при запросе свечей

### ISSUE THREAD

**Issue by NikolayXHD** [Tinkoff/investAPI#380]
2023-03-06 17:30 MSK

В среднем один запрос на несколько десятков падает в ошибку, каждый раз разная ценная бумага.

Например

запрос
```
tinkoff.invest.services.MarketDataService
get_candles

figi       = 'BBG000RP8V70'
from_      = datetime.datetime(2023, 3, 6, 0, 0, tzinfo=datetime.timezone.utc)
to         = datetime.datetime(2023, 3, 7, 0, 0, tzinfo=datetime.timezone.utc)
interval   = <CandleInterval.CANDLE_INTERVAL_1_MIN: 1>

metadata = [('authorization', 'Bearer token_was_here'), ('x-app-name', 'tinkoff.invest-python')]
```
ошибка
```
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E               status = StatusCode.UNKNOWN
E               details = "Stream removed"
E               debug_error_string = "UNKNOWN:Error received from peer ipv4:91.194.227.80:443 {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-03-06T17:28:06.248735086+03:00"}"
E           >
```

Ошибка достаточно частая, что прочитать весь список RUB акций до конца никогда не удаётся

**Comment by ivan-volnov** [comment]
Николай, это ошибка самого grpc. Говорит о том что соединение было разорвано. У себя решил немедленной отправкой того же реквеста заново. При этом коннект переоткрывается средствами grpc прозрачно для пользователя.

**Comment by NikolayXHD** [comment]
Нормальный вариант, так и сделаю, если повторится. Issue больше для разработчиков, чтобы они были в курсе проблемы.

**Comment by AlexanderVolkovTCS** [comment]
камрад @ivan-volnov верно посоветовал, спасибо

>создании заявки, то это было бы уже совсем не ОК, не исключён вариант купить в 2 раза больше, чем надо было.

для этих целей в методе PostOrder есть ключ идемпотентности и брокер гарантирует, что заявка с одним и тем же ключом не будет исполнена более 1 раза.

**Comment by ivan-volnov** [comment]
@AlexanderVolkovTCS Однако, как я уже писал здесь #369 ключ идемпотентности по сути не работает.
