### ISSUE TITLE
Пометьте в API иностранные акции, как недоступные для торгов 

### ISSUE THREAD

**Issue by inferrna** [Tinkoff/investAPI#383]
Торговля санкционкой по факту недоступна, но в API отображается как доступная.
Надо бы исправить.

**Comment by olsh** [comment]
https://github.com/Tinkoff/investAPI/issues/375#issuecomment-1457719474

**Comment by inferrna** [comment]
А как же https://tinkoff.github.io/investAPI/marketdata/#gettradingstatusresponse ?
