### ISSUE TITLE
Что такое Position_uid?

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#384]
Уважаемые коллеги! Есть кто-то, кто совсем не понял, что такое Position_uid инструмента?
Определение из документации, на мой взгляд, мало что объясняет:
"Position_uid - внутренний идентификатор позиции финансового инструмента. Представляет собой uuid. Позиция – это совокупность актива и торговой площадки(биржи)."
В чем его отличие от Instrument_uid?

**Comment by nonamegithub** [comment]
Спасибо, Александр. Весьма пространное объяснение, в добавок с ошибками ("средство изменения"), но смысл мне удалось уловить, надеюсь. Получается так, что **position_uid** это **базовый уникальный идентификатор**  ЦБ, используемый в ТИ, с размером лота равным 1, для торговли же  ЦБ на различных площадках используются **дополнительные уникальные идентификаторы** **instrument_uid** со значениями размера лота, равными или отличными от 1.

**Comment by AlexanderVolkovTCS** [comment]
>добавок с ошибками ("средство изменения")

по сути все так как написано - изменение позиций в вашем портфеле производятся действиями с торговыми инструментами.

 >с размером лота равным 1

у позиции нет лотности, лотность как раз является атрибутом торгового инструмента и определяется биржей или дилером.

position_uid  - это уникальный идентификатор позиции у вас в портфеле
instrument_uid  - это идентификатор инструмента, через который можно осуществлять действия с позицией.

Связь position_uid  к instrument_uid - 1 к N

**Comment by nonamegithub** [comment]
Я не настаиваю на своей формулировке, ни в коем случае) Но формулировка, предложенная командой разработчиков, сведет кого угодно с ума. Дайте почитать ее текст адекватному человеку (не программисту!) или нескольким,  и в ответ услышите наверняка немало "теплых" слов в свой адрес.

> position_uid - это уникальный идентификатор позиции у вас в портфеле

не согласен. в портфеле у меня может ничего не быть, а у возвращаемого  по запросу списков bonds, currencies, etfs, futures, shares, options  position_uid есть. как быть?

**Comment by AlexanderVolkovTCS** [comment]
Спасибо, подумаем над формулировками.

>в портфеле у меня может ничего не быть, а у возвращаемых по запросу списков bonds, currencies, etfs, futures, shares, options position_uid есть. как быть?


Верно, позиции в портфеле идентифицируются через position_uid, и списки инструментов тоже содержат position_uid, чтобы вы могли сопоставить их.
