### ISSUE TITLE
Дублирование инструментов

### ISSUE THREAD

**Issue by abubakirov** [Tinkoff/investAPI#385]
Добрый день,
Я запрашиваю список акций, а в ответе получаю несколько записей с одинаковыми инструментами. Например, если посмотреть обыкновенные акции Сбера, то приходит 3 записи, у двух из которых figi начинается на BBG…, а еще у одной на TCS…. Поясните, пожалуйста, чем они отличаются?

**Comment by nonamegithub** [comment]
Дублирования нет. Все три инструмента связывает один и тот же [position_uid](https://github.com/Tinkoff/investAPI/issues/384)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,

Это разные инструменты, которыми можно работать с позицией: некоторые инструменты биржевые, некоторые внебиржевые. В API доступны только биржевые, они определяются флагом api_trade_available_flag=true
