### ISSUE TITLE
Свечи. История и стримы. Вопросы к Волкову Александру

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#388]
Вопросы старые, но крайне актуальные и по сей день. 
Итак, вопросы:
1) [Необходима возможность запрашивать через GetCandles() определенное количество свечей](https://github.com/Tinkoff/investAPI/issues/262)
2) [Реализовать возможность запрашивать и подписываться на свечи с другими таймфреймами (отличными от 1min и 5min).](https://github.com/Tinkoff/investAPI/issues/364)

Нелепость аргументов разработчиков, в обоснование отказа от реализации, просто зашкаливает: ["Архитектура брокера на данный момент позволяет быстро получать свечи с минимальной задержкой только за указанные интервалы времени](https://github.com/Tinkoff/investAPI/issues/262#issuecomment-1249624242)", ["запросов на добавлении новых таймфреймов для стримов очень мало, поэтому реализовывать это в данный момент они не намерены"](https://github.com/Tinkoff/investAPI/issues/364#issuecomment-1452020920).
Для людей, не обладающих аналитическим складом ума, отмечу, что два вышеупомянутых вопроса должны быть фундаментальным функционалом API Тинькофф Инвестиций, реализованным на бэкенде и только на нем. Не покидает ощущение, что команда, осуществляющая разработку и поддержку API v2, просто немного слаба. 
Закреплю все вышесказанное всего лишь одним аргументом: десктопный терминал для TradingView графика использует API, где запросы к истории делаются с указанием количества возвращаемых свечей, а подписки на свечные стримы  работают со всеми имеющимися таймфреймами.  Вот так...

Ваше слово, Александр!

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,

>https://github.com/Tinkoff/investAPI/issues/262

В Тинькофф Инвестициях есть не только API, есть и Терминал и Мобилка и формат хранения исторической маркетдаты и кешей для нее выбран в первую очередь для решения задач этих интерфейсов. Однако отмечу, что коллеги уже разрабатывают новый сервис работы со свечами, который будет позволять в т.ч. получать N последних штук. 
Так что этот функционал будет реализован.

>https://github.com/Tinkoff/investAPI/issues/364

Непонятен сценарий использования подписок на дневные/недельные/месячные свечи:
Зачем подписываться на недельные свечи и неделю ждать приход свечи?
Какую задачу вы решите таким функционалом и почему не запросить ее через GetCandles()?

**Comment by nonamegithub** [comment]
> Однако отмечу, что коллеги уже разрабатывают новый сервис работы со свечами, который будет позволять в т.ч. получать N последних штук.
> Так что этот функционал будет реализован.

Здорово конечно, но уже сам реализовал. Но кто пойдет по [моим стопам](https://www.tradingview.com/x/TDglM2Xs), однозначно скажут вам огромное спасибо.


> Непонятен сценарий использования подписок на дневные/недельные/месячные свечи:
> Зачем подписываться на недельные свечи и неделю ждать приход свечи?
> Какую задачу вы решите таким функционалом и почему не запросить ее через GetCandles()?

Точно такую же, какую решили разработчики терминала при создании TV графика - может есть смысл Вам с ними пообщаться поплотнее?
Естественно, я не собираюсь ждать неделю прихода свечи - новая недельная свеча из стрима должна появляться с каждым трейдом (ну, либо с какой-то небольшой дискретностью), как это и реализовано в терминале. Это справедливо для дневных, месячных, годовых и вообще каких-либо других свеч. И проще всего это сделать именно на бэкенде - ровно по тому же самому алгоритму, что использован для стриминга минутных свечей.

Позвольте уточнить, Александр: то, что Вы в своем ответе не упомянули свечи с интервалами менее дня, означает ли это, что есть планы для реализации стримов с этими интервалами?

**Comment by cia76** [comment]
Присоединюсь к мнению @nonamegithub. Если что резко скажу, просьба не обижаться. Как частный трейдер, хочу получить API, с которым можно реально работать.

Если кратко, то я в хорошую библиотеку BackTrader, написанную на Python, интегрирую российских брокеров. Уже сделана интеграция с API Алор, почти завершена интеграция с API Финама. Т.к. эти задачи успешно завершены/завершаются, то это значит, что для BackTrader не нужно никаких дополнительных специфических функций. Они такие:

1. Получение информации о тикере
2. Получение свободных средств, позиций, заявок
3. Постановка рыночных, лимитных, стоп заявок

К этим пунктам вопросов к вам нет. Все сделано грамотно, работает.

4. Отслеживание изменение статусов заявок

Первая заноза. Стоп заявки у вас живут понятной только им жизнью. Как и когда они перейдут в рыночные/лимитные заявки мы должны определять по косвенным признакам. Также в документации есть идея, чтобы мы организовывали стопы на клиенте. Если идти по такой логике, то тогда вы вообще можете сократить API до отправки заявки. Остальное мы на клиенте посчитаем.

5. Получение времени сервера

Нужно для синхронизации. У вас при подписке в канале раз в 4 минуты приходит пинг со временем. Очень классное решение!

6. Получение исторических данных

У вас очень странные ограничения, которые я ни в Квике, ни в API Алора, Финама не встречал. Запросил часовки за всю историю. Получил. Вот почему ограничение год? Если жалко драгоценные ресурсы, то выдавайте только последний бар. История для тестов и стабилизации индикаторов нужна большая.

7. Подписка на бары

Здесь совсем плохо. Кто вам сказал, что надо выдавать только 1 и 5 минут? Алготрейдинг не ограничивается этими интервалами. Кому-то нужны нестандартные 2 минуты, кто-то на часовках сидит. Дополнительная проблема заключается в том, что нам нужны бары не когда вы выдадите, а когда на основании данных нового бара можно здесь и сейчас выставить заявку. Например, последняя часовка сессии должна прийти на первом тике новой сессии. Аналогично и для клирингов фьючерсов.

Неплохое решение есть у Алора. Они из тиков собирают ЛЮБЫЕ временнЫе интервалы баров, и выдают их сразу после первого тика следующего бара.

Что вижу. Первую версию API без стоп заявок даже не рассматривал для интеграции с серьезными системами. Во второй версии возникает такое ощущение, что разработчики очень далеки от реального трейдинга, и разрабатывают API не для трейдеров, а для себя. Очень хочу в этом ошибаться.

**Comment by nonamegithub** [comment]
> Здесь совсем плохо. Кто вам сказал, что надо выдавать только 1 и 5 минут?

Для себя-то они все по человечески сделали - в терминал транслируют бары с любыми таймфреймами. По сути делать практически ничего не надо - осталось сделанное обернуть в gRPC и отдать нам.



> 3\. Постановка рыночных, лимитных, стоп заявок
> 
> К этим пунктам вопросов к вам нет. Все сделано грамотно, работает.

[Не соглашусь насчет стоп-заявок](https://github.com/Tinkoff/investAPI/issues/124). Если разделить лимиты на опрос и на выставление заявок, то будет приемлемо.




> что разработчики очень далеки от реального трейдинга

Разработчики сами не торгуют, это очевидно. Иначе здесь давно была бы куча тикетов от них открыта.

Начали ребята очень неплохо с API V2, но потом, похоже, заболели звездной болезнью. Сейчас, судя по происходящему, сложилась парадоксальная ситуация: разработчики подавили волю своего заказчика/постановщика задач и нарезают задачи себе сами, как им попроще и правильнее кажется)

**Comment by cia76** [comment]
> [Не соглашусь насчет стоп-заявок](https://github.com/Tinkoff/investAPI/issues/124). Если разделить лимиты на опрос и на выставление заявок, то будет приемлемо.

Чуть выше я написал, что на клиенте, без проблем, сделаю что угодно. Если от брокера заявлен функционал, то я хочу видеть его реализацию. В данном случае, реализации, где не нужно что-то делать по "вторичным признакам заявки", нет.

**Comment by cia76** [comment]
> Разработчики сами не торгуют, это очевидно. Иначе здесь давно была бы куча тикетов от них открыта.
> 
> Начали ребята очень неплохо с API V2, но потом, похоже, заболели звездной болезнью. Сейчас, судя по происходящему, сложилась парадоксальная ситуация: разработчики подавили волю своего заказчика/постановщика задач и нарезают задачи себе сами, как им попроще и правильнее кажется)

Мне есть с чем сравнивать. Алор у меня, без малого, 2 года стабильно работает. Финам очень неплохо темп разработки взял. Если у Тинькофф ничего не изменится, то алготрейдеры будут выбирать для торговли API конкурентов. Зачем ему это, вопрос риторический...

**Comment by cia76** [comment]
В итоге, официальным клиентом на Python пользоваться не стал. Сгенерировал обертку из proto-файлов. Подписки на бары заменю на клиентские таймеры. Сервер стоп заявок к себе перенесу. От Тинькофф останется лишь справочник тикеров и отправка заявок.

**Comment by cia76** [comment]
> А свечи в финаме где? Что-то я не увидел их в описании. Увидел только стакан. Но может и проглядел.

Чуть позже выложат документацию и proto файлы.

**Comment by cia76** [comment]
> Парни, а стакан-то в Финаме хоть нормальный, без [вот такой шляпы?](https://github.com/Tinkoff/investAPI/issues/376)

Проверяли одновременно стакан по инструменту в Алоре и Финаме. Выставляли свои заявки. Все отображалось у них одинаково.

**Comment by cia76** [comment]
> [свечность](https://github.com/Tinkoff/investAPI/issues/259) здесь оставляет желать лучшего.

Брали историю от Алора и Финама на часовках за год. Было 4 различия на 1 тик.

Мне трейдеры подкинули идею брать историю по тикеру у других брокеров, заявки выставлять на Тинькофф. Может, к этому и придем.

**Comment by nonamegithub** [comment]
> заявки выставлять на Тинькофф

То еще удовольствие. Когда в бумаге сильная движуха идет, обратная связь от Тинькова сильно замедляется. Ощущения сродни поездке "по приборам" со скоростью улитки, Операция по сделке может прилететь спустя несколько минут. Заявки выставляются и снимаются с жуткими тормозами, по крайней мере у меня. Народ [писал о чем-то подобном](https://github.com/Tinkoff/investAPI/issues/269)

**Comment by cia76** [comment]
> То еще удовольствие

В любом случае, я сделаю интеграцию с Тинькофф в дополнение к Алору и Финаму. Потом посмотрю, кто чем будет пользоваться, и какие будут нарекания.

**Comment by nonamegithub** [comment]
> Начали ребята очень неплохо с API V2, но потом, похоже, заболели звездной болезнью. Сейчас, судя по происходящему, сложилась парадоксальная ситуация: разработчики подавили волю своего заказчика/постановщика задач и нарезают задачи себе сами, как им попроще и правильнее кажется)

[Прямо в яблочко попал, сам того не ведая](https://www.youtube.com/watch?v=WsGXUQKNctw&t=1620s)

**Comment by inferrna** [comment]
Хочется спросить дорогих разработчиков, почему они реализовали интервалы вот так
```rust 
    CandleInterval1Min = 1,
    CandleInterval5Min = 2,
    CandleInterval15Min = 3,
    Hour = 4,
```
а не вот так
```rust 
    CandleInterval1Min = 1,
    CandleInterval5Min = 5,
    CandleInterval15Min = 15,
    Hour = 60,
```
Ведь в будущем можно было бы, скажем, расширить до
```rust 
    CandleInterval1Min = 1,
    CandleInterval5Min = 5,
    CandleInterval10Min = 10, //Новые значения
    CandleInterval15Min = 15,
    CandleInterval30Min = 30, //вошли как влитые
    Hour = 60,
```
или разработчики считают, что будущего у тинькова, как у брокера, нет?
