### ISSUE TITLE
Правильный запрос PostOrder

### ISSUE THREAD

**Issue by miiiv** [Tinkoff/investAPI#39]
Отправляю запрос на открытие ордера:
print(client.stop_orders.post_stop_order(figi="BBG004730RP0", quantity= 1, price=None, direction=1, account_id="id", stop_order_type=2))

Ответ:
AttributeError: 'int' object has no attribute 'value'

Можно пример правильного запроса?

**Comment by AlexanderVolkovTCS** [comment]
Видимо проблема с price=None
Какой язык программирования или sdk?

**Comment by miiiv** [comment]
Python

**Comment by miiiv** [comment]
Если совсем убрать price, или подставить вместо None число, то ошибка не меняется. В телеграме сказали надо передавать enum, но я не совсем понял, как это реализовать

**Comment by daxartio** [comment]
```python
from tinkoff.invest import StopOrderDirection, StopOrderExpirationType, StopOrderType
# используйте эти enums

print(client.stop_orders.post_stop_order(figi="BBG004730RP0", quantity= 1, price=None, direction=1, account_id="id", stop_order_type=2))
```

например
```python
client.stop_orders.post_stop_order(figi="BBG004730RP0", quantity= 1, price=None, direction=StopOrderDirection.STOP_ORDER_DIRECTION_BUY, account_id="id", stop_order_type=StopOrderType.STOP_ORDER_TYPE_STOP_LOSS)
```

**Comment by daxartio** [comment]
Добавил возможность передавать цифры. Обновите на 0.2.0-beta7
