### ISSUE TITLE
Разные названия в exchange полях в инструментах и в ответе со стрима по данным торгов

### ISSUE THREAD

**Issue by Roy2player** [Tinkoff/investAPI#390]
exchanges {
  exchange: "**spb_hk**"
  days {
    date {
      seconds: 1679875200
    }
    is_trading_day: true
    start_time {
      seconds: 1679875200
    }
    end_time {
      seconds: 1679911200
    }
  }

instruments {
  figi: "BBG000BCHHM0"
  ticker: "338"
  class_code: "SPBHKEX"
  isin: "CNE1000004C8"
  lot: 1000
  currency: "hkd"
  name: "Sinopec Shanghai Petrochemical"
  exchange: "**SPB_HK**"

**Comment by Roy2player** [comment]
```
# 2023-05-22 06:01:48.659273894 <FULLDUMP> Gateway Tinkoff : ParseTradingTime(1101): exchanges {
  exchange: "**ISSUANCE**"
  days {
...
```
Это третий вариант написания, я понимаю, что можно использовать compare без учета регистра, но все же, к одному стандарту надо бы привести.

**Comment by AlexanderVolkovTCS** [comment]
Привели к верхнему регистру, спасибо

>ISSUANCE

это видимо неторгуемая или еще подготавливаемая к торговле бумага. 
Рекомендую смотреть только на торгуемые инструменты с api_trade=true, по ним все заполнено
