### ISSUE TITLE
Метод GetLastPrices возвращает null для некоторых активов

### ISSUE THREAD

**Issue by r-nicolay** [Tinkoff/investAPI#391]
![screen](https://user-images.githubusercontent.com/50655722/229224246-f5fadfc9-dca3-45c2-9c91-b3b14a14566e.png)
Недели три назад этот же запрос возвращал корректные цены.
Теперь из 40 бумаг 8 возвращаются с ценой null.

**Comment by AlexanderVolkovTCS** [comment]
По некоторым неторгуемым (api_trade_available_flag=false) инструментам в базе нет цен, поэтому возвращается NULL.
Доработаем метод, удаляя из результирующего массива инструменты с NULL.

**Comment by AlexanderVolkovTCS** [comment]
>Доработаем метод, удаляя из результирующего массива инструменты с NULL.

если вы передали перечень идентификаторов (например 40), то в ответе вы получите все 40 идентификаторов, даже если по ним нет цен.

Если вы запрашиваете последние цены вообще по всем инструментам, то  инструменты с ценой NULL фильтруются и не будут вам отображены.
