### ISSUE TITLE
Вчера весь день не приходили свечи

### ISSUE THREAD

**Issue by BaryshevS** [Tinkoff/investAPI#392]
Вчера весь день не приходили свечи, только стакан

![Снимок экрана от 2023-04-04 10-09-19](https://user-images.githubusercontent.com/44605985/229727153-450fa2dd-7882-4a5b-9083-8a81cad9b3f2.png)

**Comment by sorc1** [comment]
Это ведь старый API, который закапывают. На новом (gRPC) у меня такое тоже происходило, пока я не добавил проверку периодичности получения пингов с принудительным переподключением при превышении таймаута. Почти каждую ночь происходит от 2 до 4 переподключений по таймауту. Днём - не замечал.

**Comment by BaryshevS** [comment]
Все это делалось, но свечи так и не появлялись. Приходила только первая при подписке и все. Стаканы были.

**Comment by AlexanderVolkovTCS** [comment]
В понедельник была проблема, исправлено.
Рекомендую переходить со старой версии на новую, тк старая в апреле будет отключена.
