### ISSUE TITLE
Одинаковый ISIN у инсрументов и отсутствие свечей со стрима

### ISSUE THREAD

**Issue by Roy2player** [Tinkoff/investAPI#395]
- figi BBG004S682J4,TCS00A0JPVJ0 имеют одинаковый isin RU000A0JPVJ0.
- figi BBG00475JZZ6, TCS00A0JPNN9, TCS10A0JPNN9 - isin RU000A0JPNN9
- figi TCS00A0F5UN3, BBG000F6YPH8, BBG000F6YP24 - isin RU000A0F5UN3
- figi TCS10A0JPKH7, BBG00475K2X9, TCS00A0JPKH7 - isin RU000A0JPKH7
- figi BBG004S687W8, TCS008958863 - isin RU0008958863

Не приходят свечи по запросу на figi:
- BBG004S682J4
- TCS00A0JPVJ0
- BBG00YM3BX27
- BBG011MM3NT8
- TCS10A0JPNN9
- TCS00A0F5UN3
- BBG000F6YP24
- TCS10A0JPKH7

**Comment by Roy2player** [comment]
Это только то, с чем я непосредственно работал и поэтому заметил

**Comment by AlexanderVolkovTCS** [comment]
>Одинаковый ISIN у инструментов

ISIN - это идентификатор эмитента. У одного эмитента может быть много торговых инструментов. Это нормально.

>Не приходят свечи по запросу на figi:

у многих инструментов из перечня нет флага api_trade, например

BBG004S682J4:
"ticker": "RSTI", "class_code": "TQBR","instrument_type": "share","name": "Российские сети"

Свечей и нет, бумага не торгуется: https://www.moex.com/RU/issue.aspx?code=RSTI

Рекомендую при запросе списка инструментов получать базовый (INSTRUMENT_STATUS_BASE) а не все
