### ISSUE TITLE
Что не так с токеном от песочницы?

### ISSUE THREAD

**Issue by AndyPary** [Tinkoff/investAPI#399]
Что не так с токеном от песочницы?

после очередного запуска кода , выдал ошибку: message='authentication token is missing or invalid'
Вероятно истек срок старого. Выпустил новый токен...
ошибка не исчезла.
при запуске кодов как этот, выдает ошибку 16:
```
with SandboxClient(TOKEN) as client:
    x = client.sandbox.get_sandbox_accounts()
    print(x)
```

хотя при запуске кода ниже ошибок нет, запрос выполняется:
```
with Client(TOKEN) as client:
    x = client.instruments.shares().instruments
    print(x)
```

если что, код ниже тоже не выполнился. токен выпускал для песочницы.
```
with Client(TOKEN) as client:
    x = client.users.get_accounts()
    print(x)
```
Кстати, на странице с  кнопками выпуска токенов висела ошибка, что токен был выпущен не корректно (не дословно).

Что не так?

**Comment by AndyPary** [comment]
вот сама ошибкаЖ
tinkoff.invest.exceptions.RequestError: (<StatusCode.UNAUTHENTICATED: (16, 'unauthenticated')>, '40003', Metadata(tracking_id='6437a904983a0a61fd6280d352f5a3e2', ratelimit_limit='100, 100;w=60', ratelimit_remaining=99, ratelimit_reset=32, message='authentication token is missing or invalid'))

**Comment by AlexanderVolkovTCS** [comment]
Примерно это время был инцидент с авторизацией. 
Если проблема актуальна - прошу переоткрыть тикет
