### ISSUE TITLE
Уникальность операций

### ISSUE THREAD

**Issue by SEA99** [Tinkoff/investAPI#40]
Здравствуйте. Думал, что уникальность по id, но оказалось, что есть пары операций с
 id=-1, parentOperationId='', type='Удержание налога по дивидендам' и
 id=-1, parentOperationId='', type='Выплата дивидендов'.
Дата и бумага одна и та же. Соответственно вопросы: 
1)какая правильная уникальность по операциям? 
2)Где уникален id операции?

**Comment by SEA99** [comment]
Прошу прощения, думликат #37

**Comment by SEA99** [comment]
однако хотелось бы услышать мнение разработчиков о правильной уникальности для операций

**Comment by AlexanderVolkovTCS** [comment]
Уже исправлено
