### ISSUE TITLE
PYTHON: Ошибка с кодом 30008 в ответе метода Post_order для опциона

### ISSUE THREAD

**Issue by bkoddo** [Tinkoff/investAPI#401]
Добрый день!
При попытке выставить заявку на покупку опциона через метод Post_order возвращается ошибка 30008: missing parameter: 'figi'

tracking_id='6437a1642e52033c7183b0264a3c8a4f'

Пробовал передавать в параметре figi значение uid опциона. Пробовал передавать в параметре figi пустую строку. Результат одинаковый - 30008 ошибка.

**Comment by AlexanderVolkovTCS** [comment]
Релиз с поддержкой опционов был только сегодня, подождите официального анонса пожалуйста.
