### ISSUE TITLE
FindInstrumentRequest

### ISSUE THREAD

**Issue by bratherem** [Tinkoff/investAPI#402]
В документации указаны еще два, полезных, дополнительных параметра `api_trade_available_flag` и `instrument_kind`
На деле же, их нет.

**Comment by AlexanderVolkovTCS** [comment]
https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/instruments.proto#L1014
В контактах уже поддерживается, sdk - в процессе. рекомендуем подождать новость о релизе
