### ISSUE TITLE
Финальные вопросы к Волкову.

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#405]
Здравствуйте Александр!

[Прошел уже месяц с того момента, как я поднял вопрос](https://github.com/Tinkoff/investAPI/issues/388) о необходимости стриминга свечей с любыми интервалами. И стриминга не в том виде, как у вас сейчас транслируются свечи с интервалом 5min - только "закрывающие", а таких, какие сам Tinkoff использует в своем терминале для построения графиков, в частности. 
За месяц-то можно было не только уже неоднократно реализовать данный функционал в API, но хотя бы снизойти и дать мне какой-нибудь мало-мальски внятный ответ... Но оставлять мои тикеты и вопросы без ответов - Ваше кредо, Александр.
Уверен в одном на 100% - ваша команда не вывозит  и надо с этом что-то делать.
С трансляцией свечей все очевидно - [специалист вашей команды уже сколько времени не может разобраться с минутным интервалом](https://github.com/Tinkoff/investAPI/issues/259), куда ему уже там до остальных? Но ведь это не значит, что должны страдать мы, так ведь? Он давно бы мог сходить в команду разработчиков терминала и подучиться там, [хотя там тоже не все ровно](https://github.com/Tinkoff/investAPI/issues/192#issuecomment-1149494866), но всяко много лучше чем у вас - просто поверьте мне, так как мне вынужденно пришлось стать "свечных дел мастером". Не хочет он там учиться - могли бы давно запубличить  eндпонит /mdstream-public/v1/md-stream/socket.io на известном всем домене и методы работы с ним, и проблема бы решилась раз и навсегда. Но ничего из вышеперечисленного, к сожалению,  не произошло.
Это **ненормально**, что люди допустившие данную ситуацию, при все при этом с важным видом возвращаясь домой каждый вечер с работы, раздувая щеки командуют жене "сделай-ка мне ужин, я сегодня так сильно работал и поэтому я очень устал, ведь я работаю в самом Tinkoff", и когда родственники таких "специалистов" с нескрываемой гордостью шепчут друг-другу: "ты знаешь, он же работает с самом Тинькофф!" В действительности же удел таких "специалистов" - крутить свечи в каком-нибудь гараже в промасленной спецовке, не более.
Не согласны - пишите мне цифры Потанина. Уверен, что сумею раскрыть ему глаза на то, что специалисты Тинькова - не самые лучшие, как он, возможно, считал дор сих пор, а некоторые - вообще не специалисты.

**Comment by AlexanderVolkovTCS** [comment]
Уважаемый nonamegithub, зря вы думаете, что api, Тинькофф и мир вращается только вокруг ваших задач.
Подписки на свечи с большими таймфреймами больше нужны интерфейсам, а не роботам и запросов на добавление этого функционала было действительно мыло. Но задача есть в бэклоге, и мы реализуем ее в соответствии с приоритетами. 

Подобный стиль общения и аргументация не способствует приоритезации ваших задач.

**Comment by nonamegithub** [comment]
Так уж сложилось, Александр, что всегда иду впереди других на несколько лет. Конкретно по этой задаче: ТА на старших таймфреймах невозможен без ее реализации.  Любой пользователь терминала получит информацию о каком-нибудь переломном событии гораздо раньше (до закрытия свечи) , чем тот же робот, торгующий через API на вышеупомянутых интервалах, [да и почему это обязательно должен быть робот](https://youtu.be/WsGXUQKNctw?t=330)?
Сами знаете, трейдинг вещь очень специфическая, умные ребята здесь надолго не задерживаются, к огромному сожалению, по разным причинам. Давайте попробуем научиться предвосхищать неминуемо наступающие события.
