### ISSUE TITLE
Разница между initial_commission и итоговой комиссией по сделке

### ISSUE THREAD

**Issue by Roy2player** [Tinkoff/investAPI#406]
```
# 2023-04-28 16:38:20.473676732 <FULLDUMP> Gateway Tinkoff : ParseSendTradeResponse(538): order_id: "35759546906"
execution_report_status: EXECUTION_REPORT_STATUS_NEW
lots_requested: 2
initial_order_price {
  currency: "rub"
  units: 444
  nano: 200000000
}
executed_order_price {
  currency: "rub"
}
total_order_amount {
  currency: "rub"
}
initial_commission {
  currency: "rub"
  nano: 230000000
}
executed_commission {
  currency: "rub"
}
aci_value {
  currency: "rub"
}
figi: "BBG004730ZJ9"
direction: ORDER_DIRECTION_SELL
initial_security_price {
  currency: "rub"
  nano: 22210000
}
order_type: ORDER_TYPE_LIMIT
17: "8e2b0325-0292-4654-8a18-4f63ed3b0e09"
.
```
![photo_2023-04-29_00-21-55](https://user-images.githubusercontent.com/72526152/235256439-0a8c1fe2-715c-467e-8631-014f9fc4dd82.jpg)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, комиссия рассчитывается асинхронно после исполнения ордера, для новых заявок (со статусом EXECUTION_REPORT_STATUS_NEW) ее еще не будет

**Comment by Roy2player** [comment]
Спасибо за ответ. Может тогда удалить это поле из объекта ответа, чтобы не смущало, если цифры, которые там пишуться не соотвествуют действительности? И добавить это поле в ответ с фактическим трейдом, когда комиссия уже известа.
