### ISSUE TITLE
Несоответствие значений возвращаемых в полях figi  возвращаемых  из  GetOperations и Currencies

### ISSUE THREAD

**Issue by PanAnjey** [Tinkoff/investAPI#41]
Для операций получаемых по GetOperations   типа OPERATION_TYPE_SELL (для USD) в поле figi возвращается значение USD000UTSTOM. Однако, в списке доступных валют, получаемых по Currencies значение USD000UTSTOM выводится в поле ticker а поле figi имеет значение BBG0013HGFT4. Т.е. получается что для операций OPERATION_TYPE_SELL в поле figi возвращается на самом деле не figi а ticker

**Comment by a-treschilov** [comment]
Аналогичная проблема описана https://github.com/Tinkoff/investAPI/issues/25

**Comment by amstedy** [comment]
Также замечал странное поведение метода GetOperations, а именно: figi вовсе возвращается пустой для операций с типом "Продажа ЦБ" (tracking-id: bde1249d7335062e357ca2e4dc8a5318).

**Comment by serejhaaa** [comment]
Будет исправлено в ближайших релизах

**Comment by serejhaaa** [comment]
Исправлено
