### ISSUE TITLE
Добавить дату делистинга инструмента

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#415]
Было бы неплохо знать когда у инструмента произойдет делистинг. Может быть добавить в объект [Share](https://tinkoff.github.io/investAPI/instruments/#share) свойство с датой делистинга?

**Comment by AlexanderVolkovTCS** [comment]
Такого параметра в брокере нет и даже если бы был - ориентироваться на него было бы неправильно, так как ограничения в торговле (запрет на наращивание позиций) могут наступить и ранее.

**Comment by olsh** [comment]
Ну разве тот факт что его у брокера нет этих данных говорит о том что его их нельзя добавить в API?
Рассылку в приложении и по email Тинькофф делает, значит данные есть, откуда их получит API от брокера, или из внутренних источников Тинькофф банка разницы нет.
