### ISSUE TITLE
Идентификаторы Figi и Uid для одного и того же инструмента в GetOperationByCursor при покупке одни, при продаже другие

### ISSUE THREAD

**Issue by Ipsilon91** [Tinkoff/investAPI#417]
В списке операций, получаемых через метод GetOperationByCursor (использую официальный sdk на python https://github.com/Tinkoff/invest-python), при покупке облигаций Быстроденьги 001Р-01 22.05.2020 были одни Figi и uid, при продаже 13.01.2022 другие (см. скриншоты). Из-за этого не могу сопоставить их между собой и посчитать прибыль, получается будто они не проданы. В приложении обе эти операции отображаются (см. скриншоты). Прошу присвоить этим бумагам какой-то один figi и uid.

![uid](https://github.com/Tinkoff/investAPI/assets/20323211/db609b9c-35f8-4205-a738-e9d7aef71c99)
![figi](https://github.com/Tinkoff/investAPI/assets/20323211/09eb8ab1-ac7a-4381-a7bb-098f9f50777c)
![photo_2023-05-12_22-05-00](https://github.com/Tinkoff/investAPI/assets/20323211/7caf7c2b-0dce-4410-b201-e954321c5f2f)
![photo_2023-05-12_22-05-00 (2)](https://github.com/Tinkoff/investAPI/assets/20323211/6e4e1556-259c-4a6b-b3c7-fdb5bd71629b)

**Comment by nonamegithub** [comment]
Знаю, что разработчикам не нравится [моя формулировка](https://github.com/Tinkoff/investAPI/issues/384#issuecomment-1483809881), но тем не менее, надеюсь, что использование position_uid поможет "сопоставить их между собой и посчитать прибыль"

**Comment by Ipsilon91** [comment]
> Знаю, что разработчикам не нравится [моя формулировка](https://github.com/Tinkoff/investAPI/issues/384#issuecomment-1483809881), но тем не менее, надеюсь, что использование position_uid поможет "сопоставить их между собой и посчитать прибыль"

Действительно position_uid у них совпадает. Спасибо, очень выручили. Хотя, ну это же ровно один и тот же бонд, у них должны быть figi одинаковые. 

Разработчики, будьте добры, приведите в соответствие базы.

**Comment by nonamegithub** [comment]
> Спасибо, очень выручили

Пжл, чем смог.

> Хотя, ну это же ровно один и тот же бонд, у них должны быть figi одинаковые.

Немного не так. Хотя это и один инструмент, куплен он был на одной торговой площадке с одними FIGI и instrument_uid, а продан был на другой с другими, соответственно. Ладно еще хоть "лотность" на обоих площадках одинаковая, а то было бы еще больше вопросов... Но в общем-то, должен констатировать, вполне себе рабочая схема.

**Comment by AlexanderVolkovTCS** [comment]
>Ладно еще хоть "лотность" на обоих площадках одинаковая

Это не гарантируется, в общем случае у одной позиции может быть несколько инструментов с разной лотностью.

>Разработчики, будьте добры, приведите в соответствие базы.

Мы улучшили сопоставление разных инструментов в результатах операций, но это не всегда возможно так как у позиции может быть несколько инструментов. Поэтому рекомендую сравнивать по position_uid
