### ISSUE TITLE
Перестала приходить информация о дивидендах

### ISSUE THREAD

**Issue by olsh** [Tinkoff/investAPI#418]
С сегодняшнего дня в респонсе [GetDividendsResponse](https://tinkoff.github.io/investAPI/instruments/#getdividendsresponse) приходит пустой массив.

Пример с AAPL и C# библиотекой.
```csharp
const string appleFigi = "BBG000B9XRY4";
var dividendsResponse = client.Instruments.GetDividends(new GetDividendsRequest() { Figi = appleFigi });

// Пустой массив
dividendsResponse.Dividends.Dump();
```

**Comment by AlexanderVolkovTCS** [comment]
Добрый день
Вероятно пустой массив возвращается если Вы превышаете лимиты на количество запросов в минуту. 
На прошлой неделе временно занизили лимиты на вызов этого метода и метода GetBondCoupons()
Актуальное значение лимита - в заголовке ответа

**Comment by olsh** [comment]
> Вероятно пустой массив возвращается если Вы превышаете лимиты на количество запросов в минуту.
