### ISSUE TITLE
Метод GetOrderState: внутренняя ошибка #7001

### ISSUE THREAD

**Issue by amstedy** [Tinkoff/investAPI#42]
x-tracking-id: 4ad25562f8e46b085b17615a9ee439da

Нашел заявку, по которой GetOrderState возвращает ошибку 7001.

**Comment by serejhaaa** [comment]
к сожаление пока нет технической возможности предоставлять данные по всем старым заявкам (в документации это отразим). Но не смотря на это код ошибки неверным, это исправим в ближайших релизах.
