### ISSUE TITLE
Источники данных для стриминга

### ISSUE THREAD

**Issue by nonamegithub** [Tinkoff/investAPI#420]
В связи с появлением [нового функционала](https://tinkoff.github.io/investAPI/ws/websock/) хотел уточнить: источники данных те же самые, что для gRPC или "терминальщики" со своего ендпоинта "/mdstream-public/v1/md-stream/socket.io" поделились? Даже если это не данные от терминальщиков, то что теперь мешает стримить, в частности, их бары со старшими интервалами с наличием своего WebSocket proxy?

**Comment by AlexanderVolkovTCS** [comment]
Этот стриминг по вебсокетам еще в beta-версии, пока не анонсировался. 
Фактически он работает как proxy, источники и качество данных аналогичное gRPC.

>что теперь мешает стримить, в частности, их бары со старшими интервалами с наличием своего WebSocket proxy?

такая задача есть в бэклоге, будет сделана в соответствии с приоритетом.
