### ISSUE TITLE
Соблюдается ли строгий порядок минутных свечей по времени в grpc stream?

### ISSUE THREAD

**Issue by IvanIvanov1985** [Tinkoff/investAPI#421]
Добрый день. В доке в разделе по особенностям трансляции свечей есть один момент который я не до конца понял

```
Особенности трансляции свечей

Свечи в рамках bidirectional-stream собираются "на лету" 
из ленты обезличенных сделок. 
Свечи отправляются не чаще одного раза в 300мс + свеча закрытия периода сбора. 
Однако, бывают ситуации, что сделки с биржи 
фактически доходят уже после окончания периода сбора свечи,
в таком случае в стрим отправляется ещё одна (или более) "корректирующая" свеча.

В случае если необходимо получать свечи после закрытия интервала, 
то необходимо использовать параметр waiting_close.
```

Верно ли я понял, что эта корректирующая свеча за минуту N может быть отправлена в стрим, когда туда уже была ранее отправлена свеча за минуту N+1? Т.е. строгий порядок минутных свечей в стриме в общем случае не гарантируется? 

Если да, тогда ещё вопросы такие:
1. Есть оценки насколько часто это происходит?
2. Есть ли какой-то период после которого уже точно гарантируется что коррекции не будет? Например через 5/20/60 минут можно считать что свеча уже точно завершена? В теории тут конечно можно ходить в unary GetCandles и там есть флаг завершения, но не хочется только на это тратить лимиты unary запросов. Возможно есть планы добавить флаг завершения свечи в stream протокол? Cейчас там его нет и явным образом нельзя понять через stream, завершена ли свеча.

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер,

>корректирующая свеча за минуту N может быть отправлена в стрим, когда туда уже была ранее отправлена свеча за минуту N+1? Т.е. строгий порядок минутных свечей в стриме в общем случае не гарантируется?

Верно. биржа передает обезличенные сделки по протоколу, не гарантирующему доставку и порядок (UDP).

>Есть оценки насколько часто это происходит?

такой метрики нет


>Есть ли какой-то период после которого уже точно гарантируется что коррекции не будет?

такого периода нет, но обычно он не превышает нескольких секунд.

>Возможно есть планы добавить флаг завершения свечи в stream протокол?

Мы не знаем, будет ли в будущем дополнительная отправка "задержавшегося" трейда. Поэтому:
- такой флаг не несет особого смысла, так как и после "закрытия" свечи может прийти обновление уже закрытой свечи.
- а рассчитывать флаг только на основании текущего времени можно и на клиенте
