### ISSUE TITLE
Разделять операции DIV_EXT на две

### ISSUE THREAD

**Issue by AlexanderVolkovTCS** [Tinkoff/investAPI#423]
Методический вопрос к разработчикам API по видам операций. В случае использования ИИС есть возможность настроить выплату дивидендов на карту. Это супер, спасибо Тинькоффу. В API у вас есть соответствующая операция DIV_EXT (Выплата дивидендов на карту). Примерно в то же время выполняется технически никак с ней не связанная операция по уплате налогов DIVIDEND_TAX или DIVIDEND_TAX_PROGRESSIVE. В итоге получается, что на карту выводится сумма, равная разнице между суммами этих операций. Например, дивиденды 1000 и налог 130. Так как операции не связаны между собой, не получается установить в моменте реальную сумму вывода денежных средств. Это плохо с точки зрения  определения прибылей и убытков по каждой операции. Считать 13% от дивидендов некорректно, потому что могут быть округления и 15%.
Внимание вопрос. Можно ли вместо одной операции DIV_EXT (Выплата дивидендов на карту) передавать две операции: DIVIDEND (Выплата дивидендов) и OUTPUT (Вывод денежных средств)? Тогда с прибылью/убытком все станет понятно.
В примере тогда будет DIVIDEND 1000 OUTPUT 870. DIVIDEND_TAX 130 без изменений.

**Comment by AlexanderVolkovTCS** [comment]
Ответ коллег: Это сделано для наглядности.
Так как операция выплаты дивидендов не проходит по брокерскому счету, то не совсем правильно смотреть на сумму вывода с брокерского счета, так как вывода по факту не было.

**Comment by borrispu** [comment]
Не сходится сумма на брокерском счете из-за "наглядности". Налоги DIVIDEND_TAX тоже удерживаются не с брокерского счета, а с карты, хотя по операции это определить невозможно. Тогда сделайте, пожалуйста, отдельные операции DIVIDEND_TAX_EXT/DIVIDEND_TAX_PROGRESSIVE_EXT вместо DIVIDEND_TAX/DIVIDEND_TAX_PROGRESSIVE в данном случае, чтобы было понятно, что налоги списываются не с брокерского счета, а с карты.
