### ISSUE TITLE
не могу получить корректный figi riot

### ISSUE THREAD

**Issue by KrasoEvg** [Tinkoff/investAPI#428]
день добрый. немогу получить корректный  figi RIOT RIOT PLATFORMS

выдает  этот TCS672921050, но с ним заявки не проходят. 

Подскажите пож-та корректный figi для RIOT

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,

      "isin": "US7672921050",
      "figi": "BBG000BQ4512",
      "ticker": "RIOT",
      "class_code": "SPBXM",
      "instrument_type": "share",
      "name": "Riot Platforms",
      "uid": "80245efd-0cdb-48cc-91e1-702b44e98505",
      "position_uid": "c673e645-fd49-4c85-b494-0dc68d14caf6",
      "instrument_kind": "INSTRUMENT_TYPE_SHARE",
      "api_trade_available_flag": true,


в таких случаях рекомендую вызвать метод FindInstrument() и посмотреть бумаги с api_trade_true
