### ISSUE TITLE
/src/docs/api_protocols.md

### ISSUE THREAD

**Issue by tears-in-rain** [Tinkoff/investAPI#433]
Здравствуйте.
#### C [явно указанными протоколами](https://github.com/Tinkoff/investAPI/blob/main/src/docs/api_protocols.md?plain=1#L8), в песочнице падает соединение.

код ошибки:
```cmd
Error: 14 UNAVAILABLE: Name resolution failed for target dns:https://sandbox-invest-public-api.tinkoff.ru:443
```

```sh
node -v v19.8.1
```

```json
"dependencies": {
    "@grpc/grpc-js": "^1.8.15",
    "google-protobuf": "^3.21.2"
  }
```

примерный сценарий для воспроизведения (опуская детали по генерации контрактов):
```js
const jspb = require("google-protobuf");
const grpc_js = require("@grpc/grpc-js");
/* WORKS >>> */ const endpoint = `sandbox-invest-public-api.tinkoff.ru:443`; 
/* NOT >>> */ // const endpoint = `https://sandbox-invest-public-api.tinkoff.ru:443`;
const ssl = grpc_js.credentials.createSsl();
const metadata = new grpc_js.Metadata();
metadata.add("Authorization", "Bearer " + "");
const metadataCreds = grpc_js.credentials.createFromMetadataGenerator(
  (args, callback) => callback(null, metadata));
const ssl_creds = grpc_js.credentials.combineChannelCredentials(
  ssl, metadataCreds);

const client = new services.grpc_SandboxService.SandboxServiceClient(
  endpoint, ssl_creds);

const request = new services.UsersService.GetAccountsRequest();

client.getSandboxAccounts(request, console.log);
```

их надо убрать из [документации](https://github.com/Tinkoff/investAPI/commit/0bd3ff676ba9068f83fab75ed6fa51241549ec93#diff-d825f0c2cc859df48a4f2d2901393a2a81a71c21d0cd160ffc2abdddc83456cbR9), либо дать пояснения. 👀

**Comment by nonamegithub** [comment]
> ```js
> /* NOT >>> */ // const endpoint = `https://sandbox-invest-public-api.tinkoff.ru:443`;
> ```
А если так 

> ```js
> const endpoint = `https://sandbox-invest-public-api.tinkoff.ru`;
> ```

попробовать ?
