### ISSUE TITLE
Есть ли планы по выходу на международный рынок?

### ISSUE THREAD

**Issue by IvanIvanov1985** [Tinkoff/investAPI#443]
В первую очередь хотел бы сказать огромное спасибо команде tinkoff invest API, вы сделали очень крутой инструмент, и честно говоря я даже не могу найти заграничных аналогов.

Не знаю куда правильно это написать, поэтому напишу здесь. Я разрабатываю довольно сложный клиент на C++ к invest API для личного (и только личного) использования. Сложный, потому что стараюсь максимально использовать лимиты, как unary, так и stream, и при этом не приводить к постоянному limit exhausted. Это интересный pet-project как в качестве развития опыта в разработке, так и с точки зрения автоматизации мониторинга рынка.

Но ситуация вокруг нас, как все хорошо знают, не самая радостная, и к сожалению не исключён вариант, при котором придётся перестать быть клиентом банка Тинькофф в России. Я бы очень не хотел этого. В этом случае результат труда пропадёт, будет очень обидно. Понятно, что можно оставаться клиентом тинькофф инвестиций даже будучи нерезидентом РФ, но кто знает как всё сложится в будущем - сейчас возможно всё.

И если вдруг такое произойдёт, я хотел бы для себя понять: возможно в Тинькофф банке или отдельно Тинькофф инвестициях есть планы по выходу на междунароный рынок, чтобы был доступ в тинькофф инвестиции или хотя бы к API за границей, даже не будучи клиентом банка Тинькофф? 

Либо может быть есть какие-то заграничные аналоги, но честно говоря, я не нашёл настолько же крутого условно бесплатного API по такому большому количеству инструментов, да ещё чтоб realtime меньше минуты. 

Понимаю что вам невыгодно ссылаться на заграничные аналоги, но вдруг кто подскажет))

**Comment by AlexanderVolkovTCS** [comment]
Добрый день!
В ближайшее время выход в другие юрисдикции пока не планируется. 
О возможности работы с Тинькофф Инвестициями в случае потери резидентства РФ лучше уточните у техподдержки.

Отмечу, что работа с API будет возможна, пока у вас есть доступ к личному кабинету с возможностью выпуска токена.

Про аналоги не подскажу, к сожалению
