### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tears-in-rain** [Tinkoff/investAPI#446]
Здравствуйте.
Хотелось бы спросить об планах продукта, 
к примеру что должно выйти в ближайшие несколько недель / месяцев / лет / никогда. 
На какой функционал стоит рассчитывать, и какой скоро будет в EOL.
Хотелось бы продуктивного, двухстороннего механизма фидбека с командой разработки.

Предлагаю закрепить этот вопрос, и относить к нему все вопросы связанные с:
"когда появиться... X?" / "а где... Y?" / тегом "[enhancement]"

![image](https://github.com/Tinkoff/investAPI/assets/113452664/97ee1144-c8a9-41f4-939a-30ad3c88e289)

Пример:
https://github.com/orgs/github/projects/4247/views/7

**Comment by olsh** [comment]
Просто напомню, что обещали сделать, после релиза v2 😉 
https://github.com/Tinkoff/invest-openapi/issues/480#issuecomment-805860936

**Comment by nonamegithub** [comment]
не видать нам никакого roadmapa, так как сразу станет ясно, что команда малопродуктивна

**Comment by AlexanderVolkovTCS** [comment]
@tears-in-rain спасибо за ссылку, обсудим с коллегами включение подобной доски, а пока предлагаю обкатать роадмапу на базе дискуссий: https://github.com/Tinkoff/investAPI/discussions
Скопировал текущие публичные задачи на v1.5 и v1.6 


Комментарии и пожелания приветствуются.
