### ISSUE TITLE
Операция покупки валюты CNY

### ISSUE THREAD

**Issue by horovody** [Tinkoff/investAPI#45]
Добрый день!

Покупал в портфеле валюту CNY. 
Новая версия API возвращает наличие этой валюты в открытых позициях и в балансе валюты, но вот самой сделки покупки нет. При этом с операциями по USD, RUB, EUR таких проблем нет.
Такое же поведение было в первой версии API.

Подскажите, будет ли это добавлено во второй версии? Если нужны какие-то дополнительные данные - пожалуйста, дайте знать.

Спасибо.

**Comment by serejhaaa** [comment]
Добрый день. Да, подскажите tracking_id запроса, будем разбираться. Проверил на своём счёте, операции с юанем отображаются нормально.

**Comment by horovody** [comment]
Добрый день!

Сейчас проблема уже исправлена, спасибо. Закрываю задачу.
