### ISSUE TITLE
Отсутвутет сделка по активу (spo)

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#450]
учавствую в SPO, покупкаем актив (POSI)

как результат, в сделках есть комиссия от актив полученного на SPO
но нет сделки покупки или добавления актива

ид комиссии "4616267759"
комиссия ссылается на некую сделку -  (ParentOperationId) "36787379211", но сделки с таким ид нету

Ид аккаунта "2187082520"

Пожалуйста проверьте

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, в мобильном приложении или терминале такая сделка отображается?

**Comment by WhiteRj** [comment]
Добрый день! 

Во вкладке события в POSI в приложении этой покупки нет

**Comment by AlexanderVolkovTCS** [comment]
Тогда Вам лучше написать в техподдержку приложения. 
Появится там - появится и в API.
