### ISSUE TITLE
Нет текущих свеч 

### ISSUE THREAD

**Issue by AndoInvest** [Tinkoff/investAPI#451]
При использовании метода GetCandle при 1 минутном интервале не выдаются незавершенные (текущие) свечи. Все свечи лишь с       "isComplete": true.  Запросы осуществляю через swagger:

https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles

**Comment by nonamegithub** [comment]
Только через стрим получится, и то только с минутными. Пятиминутные, к примеру, в стриме идут только с "isComplete": true. [Разработчики до недавнего времени считали это нормой](https://github.com/Tinkoff/investAPI/issues/405). Хотя, судя по нежеланию что-то предпринимать, так и продолжают считать.

**Comment by AndoInvest** [comment]
> Только через стрим получится, и то только с минутными. Пятиминутные, к примеру, в стриме идут только с "isComplete": true. [Разработчики до недавнего времени считали это нормой](https://github.com/Tinkoff/investAPI/issues/405). Хотя, судя по нежеланию что-то предпринимать, так и продолжают считать.

Спасибо, очень помог. Раз не хотят делать, значит придётся пользоваться тем, что есть. 
Кстати, ты мог бы 5-минутные и т.д. свечи посчитать самостоятельно, используя минутные, если конечно стратегия позволяет терять несколько секунд времени.

**Comment by nonamegithub** [comment]
> Спасибо, очень помог.

Очень рад - чем смог


> Кстати, ты мог бы 5-минутные и т.д. свечи посчитать самостоятельно,

Да нет проблем. В принципе я очень многое могу, но сейчас я прилагаю усилия в том направлении, чтобы могли и хотели те, кто за это деньги получает
