### ISSUE TITLE
Не хватает свечи 09:59

### ISSUE THREAD

**Issue by panda-tamara** [Tinkoff/investAPI#452]
При запросе свечей методом getCandles нет свечи 09:59. Её можно собрать при запросе сделок, но по сделкам нельзя получить исторические данные (или можно?)

![2023-07-04_12-18-01](https://github.com/Tinkoff/investAPI/assets/4611235/652ce428-bcc9-4dbe-88ff-c6bbfd6042cb)

**Comment by panda-tamara** [comment]
Вопрос в том, как можно получить данные по этой свече?

**Comment by AlexanderVolkovTCS** [comment]
> нет свечи 09:59.

так это же аукцион открытия. Первая свеча и кажется и в мобилке/терминале 10:00 будет

>по сделкам нельзя получить исторические данные

нельзя
