### ISSUE TITLE
Операции из истории без figi и asset_uid

### ISSUE THREAD

**Issue by mild-delirium** [Tinkoff/investAPI#456]
По некоторым операциям некоторых типов (как минимум удержание налога по дивидендам и купонам) история возвращает результаты без figi, asset_uid и instrument_type. parent_operation_id тоже нет.

Пример - ниже. Происходит не по всем операциям налога с дивидендов/купонов, некоторые возвращаются с заполненными полями, некоторые - нет. С течением времени само не фиксится, как-то раз ждал неделю, в результате такие операции приходится добавлять в базу руками, так как бот не может идентифицировать инструмент.

Пример, из недавнего (сегодняшнего, дивы по MTSS):

Operation(
id='REDACTED', 
**parent_operation_id=''**, 
currency='rub', 
payment=MoneyValue(currency='rub', units=-749, nano=0), 
price=MoneyValue(currency='', units=0, nano=0), 
state=<OperationState.OPERATION_STATE_EXECUTED: 1>, 
quantity=0, 
quantity_rest=0, 
**figi=''**, 
**instrument_type=''**, 
date=datetime.datetime(2023, 7, 13, 12, 37, 26, tzinfo=datetime.timezone.utc), 
type='Удержание налога по дивидендам', 
operation_type=<OperationType.OPERATION_TYPE_DIVIDEND_TAX: 8>, 
trades=[], 
**asset_uid=''**
)

**Comment by AlexanderVolkovTCS** [comment]
У коллег уже есть в работе задача по заполнению asset_uid для операций удержания налогов с дивидендов.
Ориентировочный срок доставки - в августе.
Указать конкретный инструмент (uid или figi) в таких операциях не представляется возможным.
