### ISSUE TITLE
Split Adjusted Transactions

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#46]
Добрый день!

Получаем сделки по портфелю через 
/tinkoff.public.invest.api.contract.v1.OperationsService/GetOperationsAsync

Заметил что сделки по AAPL приходят с поправкой на сплит, а по FXUS - нет.
по хорошему, они все должны быть без учёта сплитов

пример
купил 1 акцию AAPL в 2019 году
сейчас API возвращает покупку 4х штук по цене/4
т.е. применяется сплит.

по FXUS тоже были сплиты, он он возвращает сделки правильно, т.е. как они были

Пожалуйста проверьте это

**Comment by AlexanderVolkovTCS** [comment]
В "операциях" в мобильном приложении ответ аналогичный?

**Comment by WhiteRj** [comment]
Да 
Я так понимаю, что в этом случае вопрос не к вам

просто я знаю что эта проблема не только у меня на счёте, а она глобальная..т.е. по факту каждый человек должен осмотреть все свои сделки и писать в саппорт брокера?

**Comment by WhiteRj** [comment]
Задал этот вопрос в поддержке брокера.
Послали к вам
![image](https://user-images.githubusercontent.com/15725406/151181917-e6f88c17-aa95-4fe7-b5c2-90319a656c2e.png)

**Comment by WhiteRj** [comment]
Добрый день!

дайте пожалуйста фидбек

Апи возвращает данные по активам по которым были сплиты очень по разному

пример
1.

**Comment by WhiteRj** [comment]
Добрый день!

дайте пожалуйста апдейт по этой проблеме..сейчас по активам по которым были сплиты происходит какая-то полная каша

1. по этому трек ид 61f7e5317ecded92f832261152c656d5 
были сделки по компании NEE..сделки АПИ отдаёт не аджастнутые на сплит, но при этом потом каким-то левым числом (31 декабря 2020 года) появляется securitiIn транзакция на размер аджасмента сплита

2. другой трек 61f7e5dc5a43eb1e43e1ce4847e34fd4
в этом портфеле AAPL был продан до сплита, АПИ данные отдаёт нормально

3. трек 61f7e662e7150d2fee30b6157e265590
Здесь AAPL не был продан до сплита, и значения до сплита зааджастились на сплит
т.е. количество умножилось на 4, а цена разделилась на 4

при этом, по этому же трек ид можно видеть сделки по FXUS по которому тоже был сплит, но они остались неизменными


Итого мы имеем ситуацию, когда одно и тоже событие (сплит) выглядит абсолютно по разному у 3х активов
такого быть точно не должно

**Comment by horovody** [comment]
Добрый день!

Подтверждаю, та же проблема. По некоторым активам, по которым был сплит сделки отдаются с учетом сплита, а по другим нет( Хочется, чтобы тогда уж у всех транзакций не было adjustment-а  на сплиты, либо наоборот у всех были.

Спасибо.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, фикс подобных проблем делается через техподдержку приложения, здесь не поможем.
При запросе в ТП, лучше не упоминать API(а то сюда перекинут), а указать на ошибки сплита в операциях моб приложения.
