### ISSUE TITLE
9 is not a valid SubscriptionStatus

### ISSUE THREAD

**Issue by mild-delirium** [Tinkoff/investAPI#461]
Часто стал прилетать SubscriptionStatus = 9 при попытке подписаться на OrderBook. В документации такого нет, там последний статус - 8.

SDK (python в моём случае) про SubscriptionStatus 9 тоже ничего не знает и вываливается с исключеним из сабжа при попытке распарсить protobuf из ответа.

**Comment by AlexanderVolkovTCS** [comment]
https://github.com/Tinkoff/investAPI/blob/main/src/docs/contracts/marketdata.proto#L137
Спасибо за репорт, обновили контракты, скоро обновим sdk.
