### ISSUE TITLE
Вопрос по документации  investAPI/instruments/

### ISSUE THREAD

**Issue by Tom-on-mail** [Tinkoff/investAPI#462]
https://tinkoff.github.io/investAPI/instruments/

INSTRUMENT_STATUS_BASE - есть ли разница, между тем, какие облигации доступны через апи, а какие через вэб?
К примеру, возможен ли кейс, что в вэбе бумага доступна для покупки, а в апи нет?

![image](https://github.com/Tinkoff/investAPI/assets/140348941/c25d458a-c8e0-49cc-be22-b6273bfb3aa9)
Если возмонжо, в доке подсветите пожалуйста как нибудь

**Comment by AlexanderVolkovTCS** [comment]
Обновили
