### ISSUE TITLE
Пустой стакан по акциям СПББиржы

### ISSUE THREAD

**Issue by Den4ik94** [Tinkoff/investAPI#466]
Проблема началась примерно с понедельника 31.07 - при попытке получить стакан по акциям СПББиржи разной глубины - массив пустой(

<img width="1112" alt="image" src="https://github.com/Tinkoff/investAPI/assets/52503546/4a0986f8-2632-4b08-9eb4-a7bdcf360ee3">

Пользуюсь питоновским SDK^ , библиотечкой tinkoff-investments
client_tinkoff.market_data.get_order_book(figi = share_figi_, depth = 2)

**Comment by AlexanderVolkovTCS** [comment]
Проблем не видим, в вашем запросе указан неторгуемый инструмент (api_trade=false).
Для FIXP@GS - торгуемый figi TCS0835G2057
