### ISSUE TITLE
InstrumentsService/SharesAsync не возвращает информацию об одном из активов

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#47]
Добрый день!

У меня есть сделка по компании BRZL с FIGI BBG002B24058
пытаюсь понять что это за актив ( вытаскиваю все активы с типом shares)

/tinkoff.public.invest.api.contract.v1.InstrumentsService/SharesAsync

в реквесте передаю, что нужно вернуть все активы

var instrumentReqeust = new InstrumentsRequest();
instrumentReqeust.InstrumentStatus = InstrumentStatus.All;

в результате запроса нет актива с тикером BRZL  или Figi BBG002B24058

При этом если дёрнуть поиск по конкретному FIGI, то он находится

Но как вы понимаете если у меня много активов, то дёргать каждый FIGI отдельно будет довольно неудобно и затратно

Я так понимаю, что в выдаче этот актив не отдаётся потому что он более не доступен к покупке через брокера?

**Comment by serejhaaa** [comment]
Исправлено, теперь методы получения списка инструментов (shares, bods, etfs и т.п.) возвращают все бумаги. В том числе те, которые уже недоступны для торговли.
