### ISSUE TITLE
Как правильно настроить авторизацию через Grpc.Core.Channel в c# ?

### ISSUE THREAD

**Issue by MaximPr** [Tinkoff/investAPI#48]
Я использую nuget пакет Grpc и класс Channel для авторизации. 
```
            Channel channel = new Channel(
                "invest-public-api.tinkoff.ru:443",
                ChannelCredentials.SecureSsl,
                new List<ChannelOption> {new("Authorization", "Bearer " + token)}
            );

            var userServiceClient = new UsersService.UsersServiceClient(channel);
            
            var accounts = await userServiceClient.GetAccountsAsync(new GetAccountsRequest());
```
В процессе выполнения на последней строке возникает ошибка 
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unauthenticated", Detail="", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1643116217.777000000","description":"Error received from pee
r ipv4:91.194.227.80:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1075,"grpc_message":"","grpc_status":16}")
Токен и адрес авторизации проверял в Kreya, там все работает.

**Comment by electronez** [comment]
А если протокол указать?

**Comment by igyrus** [comment]
Как-то так:

    Channel channel = new Channel("invest-public-api.tinkoff.ru:443");
    var userServiceClient = new UsersService.UsersServiceClient(channel);
    Metadata headers = new()
    {
        { "Authorization", $"Bearer {token}" }
    };
    var accounts = await userServiceClient.GetAccountsAsync(new GetAccountsRequest(), headers);

**Comment by VBkh** [comment]
Мне кажется вы не правильно добавляете токен.
В документации написано: Для успешной работы с TINKOFF INVEST API требуется передавать токен доступа в **metadata каждого запроса.**
Т.е. токен должен передоваться в реквесте, а не настройках канала

Мой рабочий пример:

Metadata Header => new Metadata { { "Authorization", $"Bearer {token}" } };
var client = new MarketDataStreamService.MarketDataStreamServiceClient(channel);
using var call = client.MarketDataStream(Header, cancellationToken: cancellationSource.Token);

**Comment by irishrover** [comment]
> Как-то так:
> 
> ```
> Channel channel = new Channel("invest-public-api.tinkoff.ru:443");
> var userServiceClient = new UsersService.UsersServiceClient(channel);
> Metadata headers = new()
> {
>     { "Authorization", $"Bearer {token}" }
> };
> var accounts = await userServiceClient.GetAccountsAsync(new GetAccountsRequest(), headers);
> ```

Я делаю так, и у меня работает:

```
channel = grpc.secure_channel(
    'invest-public-api.tinkoff.ru:443', grpc.ssl_channel_credentials())
users_stub = users_pb2_grpc.UsersServiceStub(channel)
operations_stub = operations_pb2_grpc.OperationsServiceStub(channel)
market_stub = marketdata_pb2_grpc.MarketDataServiceStub(channel)

metadata = (('authorization', 'Bearer ' + TOKEN),)

accounts = users_stub.GetAccounts(equest=users_pb2.GetAccountsRequest(), metadata=metadata)

...
```

**Comment by MaximPr** [comment]
Спасибо. Разобрался. Токен надо в каждый запрос отправлять, а не указывать при создании канала. Пример @igyrus работает
