### ISSUE TITLE
Странная работа токена с ограничением по счёту

### ISSUE THREAD

**Issue by WhiteRj** [Tinkoff/investAPI#55]
Предположим у меня есть токен, который должен отдавать данные только по 1 счёту (я выбрал по какому)

но при этом, если я делаю userService.GetAccounts с этим токеном, то я вижу все счета (а не только тот, что выбран в правах токена)

думаю, что логичнее если этому токену другие счета не будут видны

**Comment by serejhaaa** [comment]
Планируются доработки, чтобы метод GetAccounts отдавал дополнительный параметр access_level для каждого счёта (с уровнем доступа с текущим токеном). Скрывать из ответа счета не планируется. Достаточно будет такой доработки?

**Comment by WhiteRj** [comment]
Да, вполне достаточно

сейчас проблема в том, что имею токен с ограниченными правами по счетам я могу получить все счета, и потом при каком-нибудь запросе ловлю ошибку доступа) т.е. не очевидно что у меня нет доступа к этому счёту и узнать об этом я могу только ткнувшись в ошибку

Решение обозначенное вами вполне подойдёт

**Comment by serejhaaa** [comment]
Будет реализовано в ближайшем обновлении.
