### ISSUE TITLE
Операция списания налогов нет в АПИ

### ISSUE THREAD

**Issue by kordimsan** [Tinkoff/investAPI#56]
В АПИ нет операций по налогу, в отчете Эксель они присутствуют, планируется добавлять? в первой версии апи тоже не было

**Comment by AlexanderVolkovTCS** [comment]
В мобильном приложении в списке операций эти данные есть?

**Comment by kordimsan** [comment]
@AlexanderVolkovTCS в операциях нет, а остаток денег считается с учетом списания налога

**Comment by AlexanderVolkovTCS** [comment]
И в api и в мобильном приложении источник данных в операциях один, и если чего-то не хватает, надо писать запрос коллегам в техподдержку приложения.

Но мы со своей стороны скоро реализуем метод, возвращающий брокерский отчет (который из приложения экселем возвращается), он может помочь в этом вопросе.
