### ISSUE TITLE
Недоступен сервер

### ISSUE THREAD

**Issue by justewg** [Tinkoff/investAPI#57]
Пробую двумя способами работать с API, через свое go-приложение и через утилиту grpcurl, и в том и в другом случае получаю ошибку по таймауту
```
[01:14:42]-@:~/tmp (main)$ grpcurl -plaintext -import-path ./proto -proto ./proto/operations.proto invest-public-api.tinkoff.ru:443 tinkoff.public.invest.api.contract.v1.OperationsService/GetPortfolio
Failed to dial target host "invest-public-api.tinkoff.ru:443": context deadline exceeded
```
что-то я делаю не так или сервис недоступен?

**Comment by amstedy** [comment]
Уберите параметр -plaintext, он указывает на подключение без TLS.

Плюс вы не передаете заголовок с токеном авторизации и данные для метода GetPortfolio.

Вот работающий запрос для grpcurl:

`grpcurl -H "Authorization: Bearer {token}" -d '{"account_id": "111111111"}' -import-path ./proto -proto ./proto/operations.proto invest-public-api.tinkoff.ru:443 tinkoff.public.invest.api.contract.v1.OperationsService/GetPortfolio`
