### ISSUE TITLE
Добавить в Readme список доступных sdk 

### ISSUE THREAD

**Issue by JohnReeze** [Tinkoff/investAPI#58]
Удобнее было бы иметь список официальных/неофициальных sdk как тут https://github.com/Tinkoff/invest-openapi/ сразу в readme чтобы не идти в закреп в телеграмм чате

**Comment by a-treschilov** [comment]
PHP SDK:
https://github.com/metaseller/tinkoff-invest-api-v2-php
https://github.com/a-treschilov/tinkoff-invest-sdk-php

**Comment by AlexanderVolkovTCS** [comment]
Готово
