### ISSUE TITLE
 Доступ к боевым брокерским счетам используя sandbox токен

### ISSUE THREAD

**Issue by roman-struchev** [Tinkoff/investAPI#6]
Добрый день,
Использую grpc java клиент
```java
ManagedChannel channel = ManagedChannelBuilder.forAddress("invest-public-api.tinkoff.ru", 443).build();
```
Сгенерированный через предоставленные proto файлы с помощью protoc. Пример команды на генерацию
```shell
cd src/docs/contracts/
docker run -v $PWD:/defs namely/protoc-all -d . -l java
```

Независимо от того, какой указать Bearer токен (для торговли или для песочницы из https://www.tinkoff.ru/invest/settings), **всегда возвращаются данные по боевым брокерским счетам**.
В openapi такой проблемы нет.

**Comment by AlexanderVolkovTCS** [comment]
Спасибо, 
песочница(sandbox) реализована отдельным сервисом, для нее не нужен отдельный токен.
Проблема с доступом пофикшена.
