### ISSUE TITLE
InstrumentsService::GetInstrumentBy - how to query by ISIN?

### ISSUE THREAD

**Issue by Olegas** [Tinkoff/investAPI#60]
In [InstrumentRequest documentation](https://github.com/Tinkoff/investAPI/blob/main/src/docs/instruments.md#instrumentrequest) description states  it is possible to query by ISIN using `id_type` parameter.
But [InstrumentIdType documentation](https://github.com/Tinkoff/investAPI/blob/main/src/docs/instruments.md#instrumentidtype)  does not offer a way to set type to ISIN.

**Comment by malyginvv** [comment]
Hello Olegas,
Tinkoff Invest API currently doesn't support searching instruments by ISIN. The documentation has been updated.
