### ISSUE TITLE
13 INTERNAL: Response message parsing error: Assertion failed на InstrumentsServiceClient.currencies

### ISSUE THREAD

**Issue by SEA99** [Tinkoff/investAPI#63]
Первое обращение к методу InstrumentsServiceClient.currencies

ts, grpc/grpc-js

исходник:

`let metadata = new grpc.Metadata();`

`const credentials = grpc.credentials.createSsl();`

`  metadata.add('Authorization', 'Bearer '+appConfig.tinkoff.token);`

`  let connected: boolean = await new Promise( (resolve) => {
    setTimeout(() => resolve(false), TINKOFF_FIRST_CONNECTION_TIMEOUT);`

`    const tinkoffInstruments = new InstrumentsServiceClient(TINKOFF_API_URL, credentials);`

`    let req = new InstrumentsRequest();`
`    req.setInstrumentStatus( InstrumentStatus.INSTRUMENT_STATUS_BASE );`
`    tinkoffInstruments.currencies(req, metadata, (error ) => {`
`      if (error) {`
`        resolve(false);`
`        contextFatalError('TINKOFF', new AppError(error.message));`
`      }`
`      else {`
`        resolve(true);`
`      }`
`    });`
`  });`

**Comment by SEA99** [comment]
Удалось повторить проблему? Что-то ещё от меня нужно?

**Comment by GregoryPletnev** [comment]
При этом информация по пользователю отдаётся, а вот инструменты уже не работают.
Воспроизводится в Kreya.

**Comment by GregoryPletnev** [comment]
В общем не знаю у кого как - у нас просто сервис интеграции лежит (

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, попробуйте обновить контракты

**Comment by GregoryPletnev** [comment]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/54290989/151969330-29f67ad4-aa7f-4bf9-9508-d2b3a1555e30.png">

**Comment by AlexanderVolkovTCS** [comment]
В ближайшее время API будет переведен из статуса beta и ломающих изменений протокола не будет. 
Узнавать про обновления - пока да, через git
