### ISSUE TITLE
stream limit

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#64]
ДД.
 
"streamLimits": [
    {
      "limit": 4,
      "streams": [
        "tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream"
      ]
    },

начиная с третьего подключения возвращает

grpc.error ws: Error: 8 RESOURCE_EXHAUSTED: 80001

**Comment by betslus1** [comment]
Пробую ежедневно последние три недели.

**Comment by betslus1** [comment]
более простой код:
`const tinkoff_v2 = require('../tinkoff_v2.js');
const api = new tinkoff_v2({
    'isDebug': false,
    'token': process.argv[2]
});
const instruments = ["BBG005P7Q881", "BBG00WCNDCZ6", "BBG000B9XRY4", "BBG000BXQ7R1" /*, "BBG000BT3HG5"*/ ];
const streams = instruments.length;
const calls = [];
let counter = 0;
let timerId;
for (let i = 0; i < streams; i++) {
	console.log('try connect to socket', i);
    let call = api.MarketDataStreamService.MarketDataStream();
}

timerId = setInterval(() => {
    console.log('Messages received: ' + counter);
}, 30000);`

вернул
`try connect to socket 0
try connect to socket 1
try connect to socket 2
try connect to socket 3
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: 8 RESOURCE_EXHAUSTED: 80001
    at Object.callErrorFromStatus (/root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/client.js:391:49)
    at Object.onReceiveStatus (/root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on ClientDuplexStreamImpl instance at:
    at Object.onReceiveStatus (/root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/client.js:391:28)
    at Object.onReceiveStatus (/root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /root/tgbot/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 8,
  details: '80001',
  metadata: Metadata {
    internalRepr: Map(7) {
      'content-type' => [ 'application/grpc' ],
      'message' => [ 'limit of open streams exceeded' ],
      'date' => [ 'Tue, 01 Feb 2022 16:36:53 GMT' ],
      'server' => [ 'envoy' ],
      'x-ratelimit-limit' => [ '200, 200;w=60' ],
      'x-ratelimit-remaining' => [ '198' ],
      'x-ratelimit-reset' => [ '7' ]
    },
    options: {}
  }
}`

**Comment by betslus1** [comment]
хм... другой токен нормально...
 попробую ночью перезагрузить сервер...
хотя ничего зависшего не вижу

проблемный токен: t.3_w7XDJExt1rNpzD

**Comment by malyginvv** [comment]
Ошибка все еще проявляется?

**Comment by betslus1** [comment]
Сервер полностью не перезагружал, только все программы запущенные на сервере + пробовал запускать скрипт выключая по одной программе. Весь сервер смогу только в субботу перезагрузить во время плановых работ.

Ошибка проявляется и сегодня и вчера. все время с одним и тем же токеном.

**Comment by malyginvv** [comment]
Возможно неправильно определяется тарифный грейд при открытии стрима, посмотрим завтра более детально. Сейчас два стрима параллельно работают без ошибок?

**Comment by nonamegithub** [comment]
@betslus1 можешь подсказать, каким способом лучше инициировать завершение стрима, запущенного через api.OrdersStreamService.TradesStream() ? Для api.MarketDataStreamService.MarketDataStream() без проблем отрабатывает callMarketDataStream.end(), а с TradesStream такой номер уже не проходит(
Из-за этого при перезапусках TradesStream закономерно ловлю  упомянутую здесь  Error: 8 RESOURCE_EXHAUSTED: 80001

**Comment by betslus1** [comment]
Ну по идее call.end()  должен быть
Судя по документации на gRPC/nodejs

Какая ошибка при попытке сделать call.end?

**Comment by nonamegithub** [comment]
callOrdersStream.end();
                         ^

TypeError: callOrdersStream.end is not a function

**Comment by betslus1** [comment]
А console.log(callOrdersStream) что даёт? --Отправлено из мобильной Яндекс.Почты05.02.2022, 12:46, "nonamegithub" ***@***.***>:
callOrdersStream.end();
^
TypeError: callOrdersStream.end is not a function

**Comment by betslus1** [comment]
Разница в контрактах:

service MarketDataStreamService {
  //Bi-directional стрим предоставления биржевой информации.
  rpc MarketDataStream(stream MarketDataRequest) returns (stream MarketDataResponse);
}

service OrdersStreamService {
  //Stream сделок пользователя
  rpc TradesStream(TradesStreamRequest) returns (stream TradesStreamResponse);
}


попробуйте во втором контракте для теста добавить перед TradesStreamRequest "stream"

**Comment by nonamegithub** [comment]
В варианте
rpc TradesStream(**stream** TradesStreamRequest) returns (stream TradesStreamResponse);
call.end() отрабатывает - стрим завершается, хоть и с ошибкой:
Error: 13 INTERNAL: Half-closed without a request

**Comment by betslus1** [comment]
думаю тут нужны комментарии разработчиков Tinkoff, есть ли ошибка во втором контракте или нет

**Comment by betslus1** [comment]
а если дать ему request?

**Comment by nonamegithub** [comment]
call.write({}) проглатывает, но call.end() отрабатывает уже без результата

**Comment by betslus1** [comment]
> call.write({}) проглатывает, но call.end() отрабатывает уже без результата

в смысле не завершает стрим?

**Comment by nonamegithub** [comment]
Да, если был использован call.write({}), то call.end уже не завершает стрим.

С твоего позволения облегчу разработчикам моделирование проблемы:

var tinkoff_v2 = require ('../tinkoff-invest-api_v2-lazy-sdk.js');

var api = new tinkoff_v2({
	'isDebug' : false,
	'token': process.argv[2]
});

var call = api.OrdersStreamService.TradesStream();

call.end();

var msgCount = 0;
call.on('data', function(msg) {
  console.log('msgCount: ', msgCount++, ' | msg: ', msg);
});
call.on('error', function(e) {
  console.log('error: ', e);
});
call.on('status', function(status) {
  console.log('status: ', status);
});
call.on('end', function() {
  console.log('socket end');
});

**Comment by betslus1** [comment]
и все же надо глянуть через console.log(call); какие доступны методы у call при первоначальном контракте.
у меня пока выключен сервер, не могу проверить.

**Comment by nonamegithub** [comment]
пожалуйста:
```
ClientDuplexStreamImpl {
  _readableState: ReadableState {
    objectMode: true,
    highWaterMark: 16,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: true,
    ended: false,
    endEmitted: false,
    reading: true,
    constructed: true,
    sync: false,
    needReadable: true,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: false
  },
  _events: [Object: null prototype] {
    data: [Function (anonymous)],
    error: [Function (anonymous)],
    status: [Function (anonymous)],
    end: [Function (anonymous)]
  },
  _eventsCount: 4,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: true,
    highWaterMark: 16,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    constructed: true,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    errored: null,
    closed: false,
    closeEmitted: false,
    [Symbol(kOnFinished)]: []
  },
  allowHalfOpen: true,
  serialize: [Function: serialize],
  deserialize: [Function: deserialize],
  call: BaseStreamingInterceptingCall {
    call: Http2CallStream {
      methodName: '/tinkoff.public.invest.api.contract.v1.OrdersStreamService/TradesStream',
      channel: [ChannelImplementation],
      options: [Object],
      channelCallCredentials: [SingleCallCredentials],
      callNumber: 1,
      http2Stream: [ClientHttp2Stream],
      pendingRead: true,
      isWriteFilterPending: false,
      pendingWrite: null,
      pendingWriteCallback: null,
      writesClosed: false,
      decoder: [StreamDecoder],
      isReadFilterPending: false,
      canPush: true,
      readsClosed: false,
      statusOutput: false,
      unpushedReadMessages: [],
      unfilteredReadMessages: [],
      mappedStatusCode: 2,
      finalStatus: null,
      subchannel: [Subchannel],
      listener: [Object],
      internalError: null,
      configDeadline: Infinity,
      statusWatchers: [Array],
      streamEndWatchers: [Array],
      callStatsTracker: [Object],
      filterStack: [FilterStack],
      credentials: [SingleCallCredentials],
      disconnectListener: [Function (anonymous)]
    },
    methodDefinition: {
      path: '/tinkoff.public.invest.api.contract.v1.OrdersStreamService/TradesStream',
      requestStream: true,
      responseStream: true,
      requestSerialize: [Function: serialize],
      responseDeserialize: [Function: deserialize]
    }
  },
  [Symbol(kCapture)]: false
}
```

**Comment by betslus1** [comment]
В документации nodejs gRPC сказано что односторонние стримы разрешены, т.е.  в контракте проблемы нет,  но не сказано как их закрывать (issues той библиотеки еще не смотрел). 
И как вариант они закрываются каким нить 

`call = undefined;`

**Comment by betslus1** [comment]
@malyginvv 
после перезагрузки сервера и всех виртуальных машин заработали все 4 стрима,  как ни странно, видимо все таки где то все таки был зависший форк державший соединение или что-то в этом духе.

**Comment by nonamegithub** [comment]
@betslus1 нашел.  [call.cancel()](https://github.com/grpc/grpc/issues/8023) сработало.

**Comment by betslus1** [comment]
@nonamegithub тоже нашел его
https://github.com/grpc/grpc-node/issues/1238
но мне не нравится что оно вызывает исключение.

**Comment by nonamegithub** [comment]
У меня ничего не падает - сначала прилетает ошибка Error: 1 CANCELLED: Cancelled on client, потом нормально все закрывается. Меня вполне устраивает такой вариант. Сделают разрабы TradesStream двунаправленным - тоже сойдет.

**Comment by betslus1** [comment]
```
var tinkoff_v2 = require ('../tinkoff_v2.js');

var api = new tinkoff_v2({
	'isDebug' : false,
	'token': process.argv[2]
});

console.log('try to first connect');
var call = api.OrdersStreamService.TradesStream();

call.cancel();

console.log('try to second connect');

var call = api.OrdersStreamService.TradesStream();

call.cancel();

console.log(finish);
```



вот этот код работает?

**Comment by betslus1** [comment]
хотя работает этот вариант:

```
var tinkoff_v2 = require ('../tinkoff_v2.js');

var api = new tinkoff_v2({
	'isDebug' : false,
	'token': process.argv[2]
});

console.log('try to first connect');
var call = api.OrdersStreamService.TradesStream();

call.on('data', function(msg) {
  console.log('msgCount: ', ' | msg: ', msg);
});
call.on('error', function(e) {
  console.log('error: ', e);
});
call.on('status', function(status) {
  console.log('status: ', status);
});
call.on('end', function() {
  console.log('socket end');
}); 


setTimeout(function(){
	console.log('close first');
	call.cancel();
}, 1000);



setTimeout(function(){
	console.log('try to second connect');
	call = api.OrdersStreamService.TradesStream();

	call.on('data', function(msg) {
	  console.log('msgCount: ', ' | msg: ', msg);
	});
	call.on('error', function(e) {
	  console.log('error: ', e);
	});
	call.on('status', function(status) {
	  console.log('status: ', status);
	});
	call.on('end', function() {
	  console.log('socket end');
	}); 

}, 2000);


setTimeout(function(){
	console.log('close second');
	call.cancel();
}, 3000);

setTimeout(function(){
	console.log('finish');
}, 4000);



```

**Comment by nonamegithub** [comment]
Да, именно так. Подсказка была здесь:
 node:events:342
      throw er; // Unhandled 'error' event
