### ISSUE TITLE
Обработка MoneyValue

### ISSUE THREAD

**Issue by roman-struchev** [Tinkoff/investAPI#7]
Добрый день,
Использую grpc java клиент
```java
ManagedChannel channel = ManagedChannelBuilder.forAddress("invest-public-api.tinkoff.ru", 443).build();
```
Сгенерированный через предоставленные proto файлы с помощью protoc. Пример команды на генерацию
```shell
cd src/docs/contracts/
docker run -v $PWD:/defs namely/protoc-all -d . -l java
```

При работе c обьектом типа MoneyValue (https://tinkoff.github.io/investAPI/operations/#moneyvalue) возникают трудности, например вызов tinkoff.public.invest.api.contract.v1 возвращает одну из позиций
```json
{
      "figi": "TCS00A103VE6",
      "instrumentType": "etf",
      "quantity": 27000,
      "averagePositionPrice": {
        "currency": "EUR",
        "units": "0",
        "nano": 98400000
      },
      "expectedYield": -43.2,
      "currentNkd": {
        "currency": "",
        "units": "0",
        "nano": 0
      }
    },
```
где
1. в **grpc ответе averagePositionPrice.nano = 98400000, в open api возвращается averagePositionPrice.value=0.0984**. Не очень понятно, как однозначно из 98400000 получать 0.0984
2. в grpc может быть отрицательным и units и nano, это имеет смысл, т.к. units может быть 0. Но **не понятно, как работать тогда c averagePositionPrice и создавать из него обьект класса java.math.BigDecimal** например.

Если со стороны API это корректная работа, уточните пожалуйста эти особенности работы с MoneyValue, особенно если это какой-то общепринятый стандарт будет очень полезна ссылка на него или приведите пример работы/комментарий.

**Comment by VBkh** [comment]
Добрый день.

Я делаю по такой формуле: Units + Nano / NanoFactor
NanoFactor как правило равен 1_000_000_000
В вашем случае получается 0 + 98400000 / 1000000000 = 0 + 0.0984 = 0.0984, что сходится со значением из OpenAPI

**Comment by malyginvv** [comment]
Добрый день!
В Java можно проверсти конвертацию из MoneyValue/Quotation в BigDecimal например таким образом:
```java
var value = BigDecimal.valueOf(moneyValue.getUnits()).add(BigDecimal.valueOf(moneyValue.getNano(), 9));
```
Работает для положительних и отрицательных значений.

**Comment by roman-struchev** [comment]
> Добрый день! В Java можно провести конвертацию из MoneyValue/Quotation в BigDecimal например таким образом:
> 
> ```java
> var value = BigDecimal.valueOf(moneyValue.getUnits()).add(BigDecimal.valueOf(moneyValue.getNano(), 9));
> ```
> 
> Работает для положительних и отрицательных значений.

Спасибо!
