### ISSUE TITLE
смена figi

### ISSUE THREAD

**Issue by SEA99** [Tinkoff/investAPI#70]
ситуация:
Была бумага:
isin: FI0009007132
ticker: FORTUM
exchange: helsinki
currency: eur
figi: BBG000G328H7

стало то же, но
figi: BBG000CKYDQ7

Вопросы:
1) Почему так произошло, насколько часто такое происходит?
2) Что с операциями (проверить не могу, истории по бумаге нет), сменяется ли у них figi?
3) Что со старыми свечами?
4) Есть ли рекомендованная уникальность инструментов (без figi)?
5) Не совсем по теме, но тоже связано с уникальностью. Валюта у вас в lower case. А между прочим GBP и GBp разные валюты (хоть и связанные). Нет ли желания перевести валюты в uppercase (кроме GBp)?
6) Примерно в час ночи 4 февраля 2022 скорее всего возвращались обе бумаги, и старая и новая. Такое поведение сохранится или вы что-то поправите?

**Comment by SEA99** [comment]
4) Вопрос в том, что figi не совсем тот, что у Блумберга, поэтому его не получится использовать для связки с другими источниками. Я думал, что возможно, у вас в базе существует уникальность без figi, что вы как то ещё умеете идентифицировать бумагу (без figi). Ну нет так нет, спасибо.
5) Вот список валют Блумберга
https://api.openfigi.com/v3/mapping/values/currency
А вот статья в Википедии:
https://en.wikipedia.org/wiki/Penny_sterling
6)отлично, спасибо

**Comment by AlexanderVolkovTCS** [comment]
Часто наши figi действительно не совпадают с figi Блумберга.

**Comment by SEA99** [comment]
по пункту 2 - в старых операциях отражается старый figi, конкретно BBG005VKB7D7
