### ISSUE TITLE
GetCandles error

### ISSUE THREAD

**Issue by justewg** [Tinkoff/investAPI#71]
Пробую получать по GRPC с помощью текущего API данные свечей.
```
// GetCandles ...
func (api TinkoffInvestGRPCAPI) GetCandles(ctx context.Context, figi string, from time.Time, to time.Time, interval pb.CandleInterval) (*pb.GetCandlesResponse, error) {
	if !api.connected {
		return nil, errors.New("not connected to TinkoffInvestGRPCAPI")
	}

	fromTS := timestamppb.New(from)
	toTS := timestamppb.New(to)
	body, err := api.client.MarketData.GetCandles(ctx, &pb.GetCandlesRequest{
		Figi:     figi,
		From:     fromTS,
		To:       toTS,
		Interval: interval,
	})
```
api.client.MarketData - объект типа MarketDataServiceClient из pb-исходников.
Получаю ответ с ошибкой аргумента, детальнее информации нет.
Пробовал дебажить, добавив дамп переменных method и args в call.go::Invoke() перед return:
```
2022-02-06T00:06:37.061+0300	INFO	grpc@v1.44.0/call.go:41	/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles. figi:"BBG000BKTFN2"  from:{seconds:1643997600}  to:{seconds:1644088216}  interval:CANDLE_INTERVAL_1_MIN  
```
в итоге возвращается ошибка
```
"err": "rpc error: code = InvalidArgument desc = 30014"
```
при этом если запрашивать через grpccurl, передавая туда время from и to в виде строк, то все работает, данные отдаются. Есть ощущение что где-то неправильно готовится payload данных и конвертация timstempppb -> string, но дальше дебажить не получается.

Понимаю, что возможно проблема не в текущем API, а в grpc-библиотеке, но прошу помощи, важный сметод не отрабатывает.

**Comment by AlexanderVolkovTCS** [comment]
https://tinkoff.github.io/investAPI/errors/
Превышен максимальный период запроса для данного интервала свечи.
Укажите корректный интервал.



Вы запрашиваете свечи за слишком большой интервал времени, уменьшите интервал.
Для дневных свечей - год, для минутных - сутки.

**Comment by justewg** [comment]
Понял, больше спасибо

**Comment by pskucherov** [comment]
> Вы запрашиваете свечи за слишком большой интервал времени, уменьшите интервал.
> Для дневных свечей - год, для минутных - сутки.

@AlexanderVolkovTCS в документации написано `Обратите внимание, что максимально допустимый период получения свечей за один запрос — 1 календарный год.`

При этом в ошибке: "Превышен максимальный период запроса для данного интервала свечи.
Укажите корректный интервал.". 

Как сейчас узнать какой максимальный период, кроме как руками подбирать или это ишью найти? :)
