### ISSUE TITLE
Stream состояния торговых поручений пользователя

### ISSUE THREAD

**Issue by fly3110** [Tinkoff/investAPI#72]
Планируется ли введение функционала подписки на статусы торговых поручений чтобы не было необходимости постоянно вызывать GetOrders c некоторым интервалом для отслеживания статусов?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, для получения информации об исполнении ордеров рекомендуем подписку на https://tinkoff.github.io/investAPI/orders/#tradesstream 

+ планируется сделать стриминг операций, включающий отмену поручений.

**Comment by fly3110** [comment]
Спасибо, но хотелось бы еще получать информацию об отмене заявок, которые были отменены вручную через терминал

**Comment by fly3110** [comment]
> планируется сделать стриминг операций, включающий отмену поручений.
отлично, спасибо, будем ждать
