### ISSUE TITLE
Простое получение данныx по счету

### ISSUE THREAD

**Issue by megaryab** [Tinkoff/investAPI#73]
Здравствуйте господа. Решил протестировать tinkoff api invest на nodejs
И столкнулся с простой проблемой, которую не могу разрешить.

Мой код

`var api = new tinkoff_v2({ 'token'   : "t.1wedwedweds34uULdF" })`

`(async () => {  console.log( await api.Users.GetAccounts({}) )  }) () // Получил аккаунты `

`(async () => {  console.log( await api.Users.GetMarginAttributes({account_id: "2142952809"}) )  }) () // Пытаюсь получить данные по счету` 

- Получю ошибку от Tinkoff'a **[Error: 3 INVALID_ARGUMENT: 30051]**

Что я делаю не так? Простая же операция и четко следую протоколу! Помогите пожалуйста

**Comment by AlexanderVolkovTCS** [comment]
См описание кодов ошибок: https://tinkoff.github.io/investAPI/errors/

30051|INVALID_ARGUMENT|account margin status is disabled|Для данного договора недоступна маржинальная торговля.|

Если маржиналка отключена, то и GetMarginAttributes() не сработает.
