### ISSUE TITLE
Торговля валютой

### ISSUE THREAD

**Issue by megaryab** [Tinkoff/investAPI#76]
Господа, у меня вопрос.
Почему в приложении я могу покупать от 1 доллара или евро и прочую валюту.
Но в API установлены ограничения размера покупки валюты кратной 1000.
Это я чего то не понимаю или Tinkoff не дает делать такие операции через API?

**Comment by megaryab** [comment]
Ставлю и такие и такие. Пытаюсь купить 1 доллар, но не могу.

`(async () => {  console.log( await api.Orders.PostOrder({figi: "BBG0013HGFT4", quantity : 1, price : {units : 75, nano: 3}, direction : "ORDER_DIRECTION_BUY",  account_id : "2142952809", order_type : "ORDER_TYPE_LIMIT", order_id : 2 }) ) } ) ()`

`(async () => {  console.log( await api.Orders.PostOrder({figi: "BBG0013HGFT4", quantity : 1, price : {units : 75, nano: 3}, direction : "ORDER_DIRECTION_BUY",  account_id : "2142952809", order_type : "ORDER_TYPE_MARKET", order_id : 3 }) ) } ) ()`

В обоих случаях выдает ошибку.  **UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: 30042** - Недостаточно активов для маржинальной сделки. Проверьте маржинальные показатели счёта.

На счету деньги есть. 
Или я делаю что то не так? Или может какие ограничения или настройки.

Помогите пожалуйста

**Comment by FooBarrior** [comment]
вот я продал только что.
мои request&response:
```figi: "BBG0013HGFT4"
quantity: 1
price {
  units: 75
  nano: 230000000
}
direction: ORDER_DIRECTION_SELL
account_id: "2035159231"
order_type: ORDER_TYPE_MARKET
order_id: "7163836807453460708"
```

```
order_id: "22917997965"
execution_report_status: EXECUTION_REPORT_STATUS_FILL
lots_requested: 1
lots_executed: 1
initial_order_price {
  currency: "rub"
  units: 75185
}
executed_order_price {
  currency: "rub"
  units: 1
}
total_order_amount {
  currency: "rub"
  units: 75185
}
initial_commission {
  currency: "rub"
  units: 18
  nano: 800000000
}
executed_commission {
  currency: "rub"
}
aci_value {
}
figi: "BBG0013HGFT4"
direction: ORDER_DIRECTION_SELL
initial_security_price {
  currency: "rub"
  units: 75
  nano: 185000000
}
order_type: ORDER_TYPE_MARKET
```

**Comment by FooBarrior** [comment]
Да, действительно, у инструмента указано `lot: 1000`.

Я думал, цена за лот будет указана тогда в, ну, хотя бы initial_security_price. А так, мы видим, что ни в запросе, ни в ответе не фигурирует ни общая цена, ни количество акций на лот
```
figi: "BBG0013HGFT4"
 ticker: "USD000UTSTOM"
 class_code: "CETS"
 lot: 1000
 currency: "rub"
 klong {
   units: 2
 }
 kshort {
   units: 2
 }
 dlong {
   nano: 149900000
 }
 dshort {
   nano: 149200000
 }
 dlong_min {
   nano: 78000000
 }
 dshort_min {
   nano: 72000000
 }
 short_enabled_flag: true
 name: "\320\224\320\276\320\273\320\273\320\260\321\200 \320\241\320\250\320\220"
 exchange: "FX"
 nominal {
   currency: "usd"
   units: 1
 }
 trading_status: SECURITY_TRADING_STATUS_NORMAL_TRADING
 buy_available_flag: true
 sell_available_flag: true
 iso_currency_name: "usd"
 min_price_increment {
   nano: 2500000
 }
 api_trade_available_flag: true
```

**Comment by FooBarrior** [comment]
@betslus1 [в документации](https://tinkoff.github.io/investAPI/orders/#postorderrequest) написано, что price в PostOrderRequest это именно цена **лота**

**Comment by betslus1** [comment]
> @betslus1 [в документации](https://tinkoff.github.io/investAPI/orders/#postorderrequest) написано, что price в PostOrderRequest это именно цена **лота**

мне кажется ошибка в документации, лучше дождаться разработчиков или проверить.

>Я думал, цена за лот будет указана тогда в, ну, хотя бы initial_security_price. А так, мы видим, что ни в запросе, ни в ответе не фигурирует ни общая цена, ни количество акций на лот

**Comment by FooBarrior** [comment]
да, initial_order_price правильная.

Разработчикам надо либо исправить докумантацию PostOrderRequest.price, либо исправить хендлинг в соответствии с ней
