### ISSUE TITLE
Некорректный расчёт количества лотов инструментов в портфеле

### ISSUE THREAD

**Issue by g0j** [Tinkoff/investAPI#77]
При запросе портфеля через метод `GetPortfolio` получаю массив объектов `PortfolioPosition`, в элементах которого содержится поле `quantityLots`. Это поле, если верить [документации](https://github.com/Tinkoff/investAPI/blob/main/src/docs/operations.md#portfolioposition), содержит: "Количество лотов в портфеле", и, в теории, должно содержать результат деления количества инструмента (поле "quantity" этого же объекта) на его лотность. На деле же, судя по всему, в поле хранится их произведение.

Например (запрос с tracking-id 813897cecc215a21706680670c27706b):
| FIGI | Лотность | quantity | quantityLots |
| --- | --- | --- | --- |
| BBG000BN56Q9 | 10 | 200 | 2000 (ожидаю 20) |
| BBG004S681M2 | 100 | 100 | 10000 (ожидаю 1) |

**Comment by hondasmx** [comment]
Проблема исправлена
