### ISSUE TITLE
info подписки учитываются при лимите на стрим

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#79]
@malyginvv а info подписки разве входят в общий лимит?? 300 на стрим

Из документации: Важно. В рамках одного stream-соединения [сервиса котировок](https://tinkoff.github.io/investAPI/head-marketdata/) существует ограничение в 300 одновременных подписок на свечи, стаканы и ленту обезличенных сделок. Лимит считается суммарно по всем трём типам данных. Лимитов на количество подписок в рамках одного стрима на торговые статусы инструментов (подписка Info) нет.

[tinkoff.v2.fork[0]]:  [GLASS] subcribe on {"success":2,"limit":147,"other":0}
[tinkoff.v2.fork[0]]:  [INFO] subcribe on {"success":149,"limit":0,"other":0}
[tinkoff.v2.fork[0]]:  [TRADES] subcribe on {"success":149,"limit":0,"other":0}
[tinkoff.v2.fork[1]]:  [GLASS] subcribe on {"success":46,"limit":81,"other":0}
[tinkoff.v2.fork[1]]:  [INFO] subcribe on {"success":127,"limit":0,"other":0}
[tinkoff.v2.fork[1]]:  [TRADES] subcribe on {"success":127,"limit":0,"other":0}
[tinkoff.v2.fork[2]]:  [GLASS] subcribe on {"success":48,"limit":78,"other":0}
[tinkoff.v2.fork[2]]:  [INFO] subcribe on {"success":126,"limit":0,"other":0}
[tinkoff.v2.fork[2]]:  [TRADES] subcribe on {"success":126,"limit":0,"other":0}
[tinkoff.v2.fork[3]]:  [GLASS] subcribe on {"success":66,"limit":51,"other":0}
[tinkoff.v2.fork[3]]:  [INFO] subcribe on {"success":117,"limit":0,"other":0}
[tinkoff.v2.fork[3]]:  [TRADES] subcribe on {"success":117,"limit":0,"other":0}

**Comment by malyginvv** [comment]
Добрый день!
В настоящее время подсчет количества подписок в рамках стрима осуществляется некорректно. Ошибка будет исправлена в течение суток.
В качестве временного решения рекомендуется использовать такую стратегию: подписываться на торговые статусы после успешных подписок на другие типы рыночных данных.

**Comment by betslus1** [comment]
> Добрый день!
> В настоящее время подсчет количества подписок в рамках стрима осуществляется некорректно. Ошибка будет исправлена в течение суток.
> В качестве временного решения рекомендуется использовать такую стратегию: подписываться на торговые статусы после успешных подписок на другие типы рыночных данных.

Спасибо, почему то и подумал, что в этом причина)

**Comment by malyginvv** [comment]
Исправлено, можете проверить?

**Comment by betslus1** [comment]
Вск отлично
