### ISSUE TITLE
В tinkoff.public.invest.api.contract.v1 не возвращаются фонды Тинкофф

### ISSUE THREAD

**Issue by roman-struchev** [Tinkoff/investAPI#8]
Добрый день,
Использую grpc java клиент
```java
ManagedChannel channel = ManagedChannelBuilder.forAddress("invest-public-api.tinkoff.ru", 443).build();
```
Сгенерированный через предоставленные proto файлы с помощью protoc. Пример команды на генерацию
```shell
cd src/docs/contracts/
docker run -v $PWD:/defs namely/protoc-all -d . -l java
```

При **grpc вызове tinkoff.public.invest.api.contract.v1 не возвращаются фонды tinkoff,** из-за этого приходятся их дополнительно запрашивать в openapi.
В openapi такой проблемы нет (https://api-invest.tinkoff.ru/openapi/market/etfs)

**Comment by AlexanderVolkovTCS** [comment]
Так как пока Т-фонды недоступны для покупки, как и в первой версии, то они отсутствуют в базовом списке. Для их получения используйте InstrumentStatus=INSTRUMENT_STATUS_ALL
