### ISSUE TITLE
Значение marketOrderStartTime.

### ISSUE THREAD

**Issue by kitMP** [Tinkoff/investAPI#83]
В TradingSchedules  возвращается для NYSE:
"exchange": "nyse",
      "days": [
        {
          "date": "2022-02-09T00:00:00Z",
          "isTradingDay": true,
          "startTime": "2022-02-09T14:30:00Z",
          "endTime": "2022-02-09T21:00:00Z",
          "marketOrderStartTime": "2022-02-09T15:00:00Z",
          "marketOrderEndTime": "2022-02-10T04:00:00Z"
Почему время начала выставления заявок marketOrderStartTime  позже времени начала торгов startTime ?

**Comment by serejhaaa** [comment]
В этот период на бирже аукцион открытия и доступны только лимитные заявки

**Comment by kitMP** [comment]
Откуда это? Что-то я не нашёл подтверждения этому на сайте nyse. core trading time c 14:30 не содержит такого ограничения. Можно пруф?

**Comment by serejhaaa** [comment]
Прошу прощения, параметр устарел. Уберём его из метода получения расписания в ближайшем релизе. Ориентироваться можно только на startTime
