### ISSUE TITLE
 [BUG] Неверное значение исторической свечи

### ISSUE THREAD

**Issue by a-treschilov** [Tinkoff/investAPI#85]
Метод: getHistoryCandles
Figi: BBG007Z13SN3
From: 2022-02-13 00:00:00
To: 2022-02-14 23:59:59
Interval: 5 (1day)

Фактический результат: 
open: {unit: 99, nono: 854000000}

Ожидаемый результат:
open: {unit: 998, nono: 540000000}

**Comment by serejhaaa** [comment]
Стоимость облигаций и фьючерсов транслируется в пунктах цены. Для облигаций это процент от номинала. 
Подробнее: https://tinkoff.github.io/investAPI/faq_marketdata/#_3

**Comment by a-treschilov** [comment]
Спасибо! Прошу прощения за невнимательность
