### ISSUE TITLE
Нет limitUp/limitDown

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#88]
Только ради этого приходится оставлять первую версию. Хотелось бы info сообщения в стриме по изменениям лимитов в стакане.

**Comment by AlexanderVolkovTCS** [comment]
Добавили https://github.com/Tinkoff/investAPI/releases/tag/v1.0.2

**Comment by betslus1** [comment]
> Добавили https://github.com/Tinkoff/investAPI/releases/tag/v1.0.2

не работает
заметил на акциях СПБ в 00:48 

возвращаются нули в limitUp/Down
днем гляну на спб/moex
через приложение по 1$ акции не выставляются, значит какие то лимиты все такие есть
