### ISSUE TITLE
возвращаемая стоимость облигации в 10 раз меньше реальной [bug]

### ISSUE THREAD

**Issue by alexanderkmd** [Tinkoff/investAPI#9]
Запрос **GetLastPrice** 
```js
{
  "figi": [
    "BBG00ZX8S6G7"
  ]
}
```

**Возвращает**:
tracking-id: 27fdbe7a172d2c6177e31c1c36015f15
```js
{
  "lastPrices": [
    {
      "figi": "BBG00ZX8S6G7",
      "price": {
        "units": "98",
        "nano": 750000000
      },
      "time": "2022-01-06T15:25:05.070302Z"
    }
  ]
}
```

**Ожидается**:

```js
{
  "lastPrices": [
    {
      "figi": "BBG00ZX8S6G7",
      "price": {
        "units": "987",
        "nano": 500000000
      },
      "time": "2022-01-06T15:25:05.070302Z"
    }
  ]
}
```

Такое поведение отмечается только на облигациях - фонды, акции - без проблем.

Аналогичное поведение на **GetCandles**:
```js
{
  "figi": "BBG00ZX8S6G7",
  "from": "2021-12-21T00:02:03.000000123Z",
  "to": "2022-01-02T00:02:03.000000123Z",
  "interval": "CANDLE_INTERVAL_DAY"
}
```
tracking-id: 235d2630656594272422ca9a516b4d04
```js
{
  "candles": [
    {
      "open": {
        "units": "96",
        "nano": 290000000
      },
      "high": {
        "units": "96",
        "nano": 650000000
      },
      "low": {
        "units": "95",
        "nano": 710000000
      },
      "close": {
        "units": "96",
        "nano": 210000000
      },
      "volume": "5044",
      "time": "2021-12-21T07:00:00Z",
      "isComplete": true
    },... ]}
```

**Comment by serejhaaa** [comment]
Здраствуйте, цены облигаций транслируются в пунктах, которые соответствуют проценту номинала. Т.е. для вычисления стоимости облигации следует воспользоваться формулой: 
price/100*nominal

**Comment by alexanderkmd** [comment]
> Здраствуйте, цены облигаций транслируются в пунктах, которые соответствуют проценту номинала. Т.е. для вычисления стоимости лота облигации следует воспользоваться формулой: price/100*nominal

Добрый день! Как то это немного странно. А в документации где-нибудь есть об этом указание? Может плохо ищу - но не могу найти.

**Comment by serejhaaa** [comment]
Документацию обновляем, чтобы это явно было зафиксировано. Именно такой формат цены был выбран, потому что в таком формате цены транслирует биржа. Облигации и фьючерсы торгуются в пунктах, причём они по-разному считаются для фьючей и облигаций (так же зафиксируем в документации).

**Comment by AlexanderVolkovTCS** [comment]
Документация обновлена: https://tinkoff.github.io/investAPI/

**Comment by serejhaaa** [comment]
Для расчёта стоимости фьючерсов дописал в документации: 
https://tinkoff.github.io/investAPI/faq_marketdata#futures

Получать все необходимые для расчёта показатели можно методом https://tinkoff.github.io/investAPI/instruments#getfuturesmargin
