### ISSUE TITLE
Позднее включение SPB на старте торгов

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#90]
Вижу что сообщения о старте торгов на спб приходят с задержкой около 5-25 секунд.
Это ошибка? Или биржа реально включается не в 10:00:00 а в 10:00:05
MOEX включается в 10:00:00

#info #normal_trading #stream

**Comment by AlexanderVolkovTCS** [comment]
Задержки на нашей стороне минимизированы, но наблюдаем, что иногда от биржи приходит старт торгов с запозданием.
