### ISSUE TITLE
Доработка документации Invest API

### ISSUE THREAD

**Issue by serejhaaa** [Tinkoff/investAPI#92]
1. Добавить примеры подключения к Invest API на всех языка. Добавить ссылки на примеры в репозиториях sdk
2. Детальное описание статусов торгов, что они значат и т.п. 
4. Описание расписаний торговли (что значат все эти exchange, куда смотреть и т.п.) 
5. Завести отдельный FAQ по каждому языку, куда переносить все вопросы из ишью, если они касаются определённого языка
6. Расписать подробнее про различия лотов и количеств, где используются, как правильно интерпретировать данные.
7. Описать нюансы торговли валютой
8. Статьи про активы и инструменты 
9. Описать конвертацию цен облигаций и фьючерсов с примерами кода (или так же ссылки на соответствующие примеры в репозиториях sdk)
10. Дописать про ограничение торговлей фондами Тинькофф
11. Переработка структуры. - Выделить раздел "Подключение к Invest API", сделать отдельные FAQ по сервисам, слинковать между собой общий список вопросов и эти разделы.
12. Переработать главную страницу

**Comment by betslus1** [comment]
12) Инструкция по переводу гугловского времени в GRPC на странице где описываются нестандартные типы

**Comment by AlexanderVolkovTCS** [comment]
* собрать отдельный раздел "у меня не работает..." с популярными проблемами и алгоритмом их устранения

**Comment by hommeideal** [comment]
> 3\. Описание расписаний торговли (что значат все эти exchange, куда смотреть и т.п.)

Поддерживаю - очень нужно! Хотел сделать красивый график торгов - а там черт ногу сломит!
