### ISSUE TITLE
Время хранения на стороне брокера поля идемпотентности

### ISSUE THREAD

**Issue by betslus1** [Tinkoff/investAPI#95]
Добрый день,
хочу уточнить по полю идемпотентности при создании заявки
1) Время хранения на стороне брокера, порядок хотя бы (час/день/месяц/год/бесконечно), что бы определить лучший способ его генерации для оптимальной защиты и псевдослучайности.
2) Планируется ли в будущем когда либо возвращать его в методах orderlist/operations etc... В этом случае логичнее было бы его сохранять в своей БД и/или передавать внутренние номера заявок.

**Comment by b1ng0o** [comment]
Добрый день,
1.  На данный момент ключ идемпотентности хранится один год на стороне брокера
2. Пока таких планов нет
